# PostBatchCopyResults
2026-09-29
This notebook moves the results from the individual session output folders to the shared/public `CollectedOutputs` or `AcrossSession` folders

#### Where outputs go
On GL, the intended roots are:
'/nfs/turbo/umms-kdiba/Data/Output/collected_outputs' (first extant path in the notebook)
'…/collected_figures' (sibling of collected_outputs)

In [4]:
%config IPCompleter.use_jedi = False
%pdb off
%load_ext autoreload
%autoreload 3
import os
import sys
import platform
from copy import deepcopy
from typing import Dict, List, Tuple, Optional, Callable, Union, Any

from pathlib import Path
import pathlib
import numpy as np
import pandas as pd
import tables as tb
from datetime import datetime, timedelta
from attrs import define, field, Factory

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from typing_extensions import TypeAlias
from neuropy.utils.result_context import IdentifyingContext
from nptyping import NDArray
import neuropy.utils.type_aliases as types
from collections import defaultdict

import re
from pathlib import Path
from datetime import datetime
from pyphocorehelpers.Filesystem.path_helpers import find_first_extant_path
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import find_csv_files, find_HDF5_files, find_most_recent_files, OldFileArchiver
from pyphoplacecellanalysis.General.Batch.runBatch import ConcreteSessionFolder, BackupMethods
from neuropy.core.user_annotations import UserAnnotationsManager
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionHelpers


# # required to enable non-blocking interaction:
# %gui qt5 ## TODO 2024-01-18 - this causes kernel to crash when running notebook remotely via VSCode's ssh remote

## Pho's Custom Libraries:
from pyphocorehelpers.Filesystem.path_helpers import find_first_extant_path
from pyphocorehelpers.function_helpers import function_attributes
from pyphocorehelpers.exception_helpers import CapturedException

# Jupyter interactivity:
import ipywidgets as widgets
from IPython.display import display
from pyphocorehelpers.gui.Jupyter.JupyterButtonRowWidget import JupyterButtonRowWidget
from pyphocorehelpers.gui.Jupyter.simple_widgets import code_block_widget

# pyPhoPlaceCellAnalysis:
# NeuroPy (Diba Lab Python Repo) Loading
from neuropy.core.session.Formats.BaseDataSessionFormats import DataSessionFormatRegistryHolder
# from neuropy.core.session.Formats.Specific.BapunDataSessionFormat import BapunDataSessionFormatRegisteredClass
from neuropy.core.session.Formats.Specific.KDibaOldDataSessionFormat import KDibaOldDataSessionFormatRegisteredClass
# from neuropy.core.session.Formats.Specific.RachelDataSessionFormat import RachelDataSessionFormat
# from neuropy.core.session.Formats.Specific.HiroDataSessionFormat import HiroDataSessionFormatRegisteredClass
from neuropy.utils.matplotlib_helpers import matplotlib_configuration_update

## For computation parameters:
from neuropy.utils.result_context import IdentifyingContext
from neuropy.core.session.Formats.BaseDataSessionFormats import find_local_session_paths
from neuropy.core import Epoch

from neuropy.core.session.Formats.Specific.KDibaOldDataSessionFormat import KDibaOldDataSessionFormatRegisteredClass
from pyphocorehelpers.assertion_helpers import Assert

from pyphoplacecellanalysis.General.Pipeline.Stages.Loading import saveData, loadData

from neuropy.core.user_annotations import UserAnnotationsManager
from pyphoplacecellanalysis.General.Batch.runBatch import SessionBatchProgress
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionsResults, AcrossSessionTables, AcrossSessionsVisualizations

from pyphocorehelpers.Filesystem.path_helpers import set_posix_windows
from pyphoplacecellanalysis.General.Batch.pythonScriptTemplating import build_vscode_workspace, build_windows_powershell_run_script

from pyphocorehelpers.Filesystem.metadata_helpers import FilesystemMetadata, get_file_metadata
from pyphocorehelpers.Filesystem.path_helpers import discover_data_files, generate_copydict, copy_movedict, copy_file, save_copydict_to_text_file, read_copydict_from_text_file, invert_filedict
from pyphoplacecellanalysis.General.Batch.runBatch import get_file_str_if_file_exists
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import check_output_h5_files, copy_files_in_filelist_to_dest
from pyphoplacecellanalysis.General.Batch.runBatch import ConcreteSessionFolder, BackupMethods

from pyphoplacecellanalysis.General.Batch.NonInteractiveProcessing import batch_perform_all_plots, BatchPhoJonathanFiguresHelper
from pyphoplacecellanalysis.SpecificResults.PhoDiba2023Paper import PAPER_FIGURE_figure_1_add_replay_epoch_rasters, PAPER_FIGURE_figure_1_full, PAPER_FIGURE_figure_3, main_complete_figure_generations

from neuropy.core.neuron_identities import NeuronIdentityDataframeAccessor
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.MultiContextComputationFunctions.LongShortTrackComputations import build_merged_neuron_firing_rate_indicies
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.MultiContextComputationFunctions.DirectionalPlacefieldGlobalComputationFunctions import DirectionalPlacefieldGlobalComputationFunctions, DirectionalLapsHelpers
from pyphocorehelpers.gui.Jupyter.simple_widgets import fullwidth_path_widget, filesystem_path_folder_contents_widget

from pyphoplacecellanalysis.General.Batch.BatchJobCompletion.UserCompletionHelpers.batch_user_completion_helpers import MAIN_get_template_string, write_test_script
from pyphoplacecellanalysis.General.Batch.BatchJobCompletion.UserCompletionHelpers.batch_user_completion_helpers import export_session_h5_file_completion_function, curr_runtime_context_header_template, export_rank_order_results_completion_function, figures_rank_order_results_completion_function, determine_session_t_delta_completion_function, perform_sweep_decoding_time_bin_sizes_marginals_dfs_completion_function, compute_and_export_decoders_epochs_decoding_and_evaluation_dfs_completion_function, compute_and_export_session_wcorr_shuffles_completion_function, compute_and_export_session_instantaneous_spike_rates_completion_function, compute_and_export_session_extended_placefield_peak_information_completion_function, compute_and_export_session_alternative_replay_wcorr_shuffles_completion_function, backup_previous_session_files_completion_function, compute_and_export_session_trial_by_trial_performance_completion_function, save_custom_session_files_completion_function, compute_and_export_cell_first_spikes_characteristics_completion_function, figures_plot_cell_first_spikes_characteristics_completion_function, generalized_decode_epochs_dict_and_export_results_completion_function
from pyphoplacecellanalysis.General.Batch.BatchJobCompletion.UserCompletionHelpers.batch_user_completion_helpers import kdiba_session_post_fixup_completion_function
from pyphoplacecellanalysis.General.Batch.pythonScriptTemplating import ProcessingScriptPhases

from pyphoplacecellanalysis.SpecificResults.PendingNotebookCode import _add_cell_remapping_category
from pyphoplacecellanalysis.General.Batch.pythonScriptTemplating import BatchScriptsCollection, generate_batch_single_session_scripts, display_generated_scripts_ipywidget
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionHelpers

# BATCH_DAY_DATE: str = '2026-08-27'
BATCH_DAY_DATE: str = '2026-09-29'

# BATCH_DATE_TO_USE = f'{BATCH_DAY_DATE}_Apogee' # used for filenames throught the notebook
BATCH_DATE_TO_USE = f'{BATCH_DAY_DATE}_GL' # used for filenames throught the notebook
# BATCH_DATE_TO_USE = f'{BATCH_DAY_DATE}_Lab' # used for filenames throught the notebook
# BATCH_DATE_TO_USE = f'{BATCH_DAY_DATE}_rMBP' # used for filenames throught the notebook

known_scripts_output_paths = [Path(v).resolve() for v in ['/Users/pho/repo/Pho Secondary Workspace/Spike3DEnv/cloud/turbo/Data/Output/gen_scripts', '/home/halechr/cloud/turbo/Data/Output/gen_scripts/', '/Users/pho/University of Michigan Dropbox/MED-DibaLabDropbox/Data/Pho/Outputs/output/collected_outputs', '/home/halechr/FastData/gen_scripts/', 'output/gen_scripts/', "K:/scratch/gen_scripts"]]
scripts_output_path = find_first_extant_path(known_scripts_output_paths)
assert scripts_output_path.exists(), f"scripts_output_path: {scripts_output_path} does not exist! Is the right computer's config commented out above?"
# fullwidth_path_widget(scripts_output_path, file_name_label='Scripts Output Path:')
print(f'scripts_output_path: {scripts_output_path}')

known_collected_output_paths = [Path(v).resolve() for v in ['/nfs/turbo/umms-kdiba/Data/Output/collected_outputs', '/home/halechr/FastData/collected_outputs/', '/home/halechr/cloud/turbo/Data/Output/collected_outputs', r"K:/scratch/collected_outputs", '/Users/pho/data/collected_outputs', 'output/gen_scripts/', 
															'/Volumes/SwapSSD/Data/collected_outputs', '/Users/pho/Dropbox (University of Michigan)/MED-DibaLabDropbox/Data/Pho/Outputs/output/collected_outputs', r'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/collected_outputs', '/home/halechr/FastData/collected_outputs/',
															'/home/halechr/cloud/turbo/Data/Output/collected_outputs', scripts_output_path.joinpath('../collected_outputs').resolve()]]
collected_outputs_path = find_first_extant_path(known_collected_output_paths)
Assert.path_exists(collected_outputs_path) # f"collected_outputs_path: {collected_outputs_path} does not exist! Is the right computer's config commented out above?"
# fullwidth_path_widget(scripts_output_path, file_name_label='Scripts Output Path:')
collected_outputs_path.mkdir(exist_ok=True)
print(f'collected_outputs_path: {collected_outputs_path}')

collected_figures_path = collected_outputs_path.parent.joinpath('collected_figures')
collected_figures_path.mkdir(exist_ok=True)
print(f'collected_figures_path: {collected_figures_path}')
Assert.path_exists(collected_figures_path)

# Hardcoded included_session_contexts:
all_session_contexts: List[IdentifyingContext] = UserAnnotationsManager.get_hardcoded_good_sessions()
# included_session_contexts
# excluded_session_keys = ['kdiba_gor01_one_2006-6-08_14-26-15', 'kdiba_gor01_one_2006-6-09_1-22-43',
#     # 'kdiba_gor01_one_2006-6-08_14-26-15', 'kdiba_gor01_two_2006-6-07_16-40-19', 'kdiba_pin01_one_fet11-01_12-58-54',
# ]
# excluded_session_keys = ['2006-6-08_14-26-15', '2006-6-09_1-22-43']
excluded_session_keys = []
excluded_session_contexts = [IdentifyingContext.try_init_from_session_key(session_str=v) for v in excluded_session_keys]
print(f'excluded_session_contexts: {excluded_session_contexts}')
included_session_contexts: List[IdentifyingContext] = [v for v in all_session_contexts if v not in excluded_session_contexts]
print(f'included_session_context: {included_session_contexts}')

debug_print = True
# debug_print = False
all_known_session_contexts: List[IdentifyingContext] = UserAnnotationsManager.get_all_known_sessions()
known_global_data_root_parent_paths = [Path('/home/halechr/cloud/turbo/Data'), Path('/Users/pho/data'), Path(r'/nfs/turbo/umms-kdiba/Data'), Path(r'/media/halechr/BETAMAX/Data'), Path(r'/media/halechr/MAX/Data'), Path(r'W:/Data'), Path(r'/home/halechr/FastData'), Path(r'/Volumes/MoverNew/data')] # Path(r'/home/halechr/cloud/turbo/Data'), , Path(r'/nfs/turbo/umms-kdiba/Data'), Path(r'/home/halechr/turbo/Data'), 
global_data_root_parent_path = find_first_extant_path(known_global_data_root_parent_paths)
assert global_data_root_parent_path.exists(), f"global_data_root_parent_path: {global_data_root_parent_path} does not exist! Is the right computer's config commented out above?"
print(f'global_data_root_parent_path: {global_data_root_parent_path}')
all_known_session_concrete_folders = ConcreteSessionFolder.build_concrete_session_folders(global_data_root_parent_path, all_known_session_contexts)
good_session_concrete_folders = ConcreteSessionFolder.build_concrete_session_folders(global_data_root_parent_path, included_session_contexts)
session_basedirs_dict: Dict[IdentifyingContext, Path] = {a_session_folder.context:a_session_folder.path for a_session_folder in good_session_concrete_folders}

Automatic pdb calling has been turned OFF
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/hdf5storage/utilities.py:44: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version

scripts_output_path: /nfs/turbo/umms-kdiba/Pho/Output/gen_scripts
collected_outputs_path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs
collected_figures_path: /nfs/turbo/umms-kdiba/Pho/Output/collected_figures
excluded_session_contexts: []
included_session_context: [IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-08_14-26-15')>, IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-09_1-22-43')>, IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-12_15-55-31')>, IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-07_16-40-19')>, IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-08_21-16-25')>, IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-09_22-24-40')>, IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-12_16-53-46')>, IdentifyingContext<('kdiba', 'vvp01', 'two', '2006-4-09_16-40-54')>, IdentifyingContext<('kdiba', 'vvp01', 'two', '2006-4-10_12-58-3')>, IdentifyingContext<('kdiba', 'pin01', 'one', '11-03_12-3-25')>, IdentifyingContext<('kdiba', 'pin01', 'one', 'fet11-01_12-58-54')>]
global_data_root_parent_path: /home/halechr/cloud/turbo/Data

In [5]:

## Different run configurations:
active_phase_dict = {}
# ==================================================================================================================== #
# Custom Suffix and overrides                                                                                          #
# ==================================================================================================================== #
# # '_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2]' ___________________________________________________________ #
# active_phase_dict['override_custom_pickle_suffix'] = '_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0'
# included_qclu_values = [1,2]
# minimum_inclusion_fr_Hz = 5.0
# job_suffix = f"_withNormalComputedReplays-qclu_12-frateThresh_5.0" ## ends up being something like # job_suffix = f"_withNormalComputedReplays-qclu_12-frateThresh_5.0_tbin_25ms"

# # # "_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2, 4, 6, 7, 9]" _______________________________________________ #
# active_phase_dict['override_custom_pickle_suffix'] = "_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_5.0" ##
# included_qclu_values = [1, 2, 4, 6, 7, 9]
# minimum_inclusion_fr_Hz = 5.0
# job_suffix = f"_withNormalComputedReplays-qclu_124679-frateThresh_5.0"


# # "_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2]" _______________________________________________ #
# active_phase_dict['override_custom_pickle_suffix'] = "_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0" 
# included_qclu_values = [1, 2]
# minimum_inclusion_fr_Hz = 5.0
# job_suffix = f"_withNormalComputedReplays-qclu_12-frateThresh_5.0"

# # # # "_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2, 4, 6, 7, 8, 9]" _______________________________________________ #
# # active_phase_dict['override_custom_pickle_suffix'] = "_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0"
# included_qclu_values = [1, 2, 4, 6, 7, 8, 9]
# minimum_inclusion_fr_Hz = 5.0
# job_suffix = f"_withNormalComputedReplays-qclu_1246789-frateThresh_5.0"


# # "_withNormalComputedReplays-frateThresh_2.0-qclu_[1, 2, 4, 6, 7, 8, 9]" _______________________________________________ #
active_phase_dict['override_custom_pickle_suffix'] = "_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0"
included_qclu_values = [1, 2, 4, 6, 7, 8, 9]
minimum_inclusion_fr_Hz = 2.0
job_suffix = f"_withNormalComputedReplays-qclu_1246789-frateThresh_2.0"


# # # # "_withNormalComputedReplays-frateThresh_2.0-qclu_[1, 2, 4, 6, 7, 8, 9]" _______________________________________________ #
# # active_phase_dict['override_custom_pickle_suffix'] = "_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.2"
# included_qclu_values = [1, 2, 4, 6, 7, 8, 9]
# minimum_inclusion_fr_Hz = 0.2
# job_suffix = f"_withNormalComputedReplays-qclu_1246789-frateThresh_0.2"

# ==================================================================================================================== #
# Common:                                                                                                              #
# ==================================================================================================================== #

# laps_decoding_time_bin_size = None
laps_decoding_time_bin_size = 0.025
# laps_decoding_time_bin_size = 0.050
# laps_decoding_time_bin_size = 0.075
# laps_decoding_time_bin_size = 0.5

ripple_decoding_time_bin_size = 0.025
# ripple_decoding_time_bin_size = 0.050
# ripple_decoding_time_bin_size = 0.058
# ripple_decoding_time_bin_size = 0.075

# job_suffix = f"{active_phase_dict['override_custom_pickle_suffix']}_tbin_25ms"
# job_suffix = f"{job_suffix}_tbin_20ms"
job_suffix = f"{job_suffix}_tbin_25ms"
# job_suffix = f"{job_suffix}_tbin_50ms"
# job_suffix = f"{job_suffix}_tbin_60ms"
# job_suffix = f"{job_suffix}_tbin_75ms"

# END ________________________________________________________________________________________________________________ #
print(f'job_suffix: {job_suffix}')

job_suffix: _withNormalComputedReplays-qclu_1246789-frateThresh_2.0_tbin_25ms

# 🔷 Maintenence and File Management

## Move misplaced files to session folders

### 2025-06-10 - Works to copy the .h5 files in each session after batch compute/export into the `collected_outputs_path`

In [6]:
from pyphocorehelpers.gui.Jupyter.IPythonDryrunExecutionWidget import DryRunExecutionWidget
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import find_most_recent_files
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionHelpers

## INPUTS: good_session_concrete_folders, session_basedirs_dict, computation_script_paths
## INPUTS: BATCH_DATE_TO_USE
print(F'BATCH_DATE_TO_USE: "{BATCH_DATE_TO_USE}"')
# BATCH_DATE_TO_USE='2025-04-18'

print(f'collected_outputs_path: "{collected_outputs_path.as_posix()}"')
# session_basedirs_dict: Dict[IdentifyingContext, Path] = {a_session_folder.context:a_session_folder.path for a_session_folder in good_session_concrete_folders}
is_dryrun: bool = True
# is_dryrun: bool = False
debug_print: bool = False

# cuttoff_date = datetime(2025, 6, 16)
# cuttoff_date = datetime(2025, 7, 16)
# cuttoff_date = datetime(2025, 8, 26)
# cuttoff_date = datetime(2026, 8, 26)
cuttoff_date = datetime(2026, 9, 29)
# cuttoff_date = None

def _across_session_h5_output_basename_fn(session_context: Optional[IdentifyingContext], session_descr: Optional[str], basename: str, *args, separator_char: str = "_"):
    """ Builds output HDF5 file name
    Captures `BATCH_DATE_TO_USE`
    """
    # a_session_folder.context
    if session_context is not None:
        session_descr = session_context.session_name # '2006-6-07_16-40-19'
    _filename_list = [BATCH_DATE_TO_USE, session_descr, basename]
    if len(args) > 0:
        _filename_list.extend([str(a_part) for a_part in args if a_part is not None])
    return separator_char.join(_filename_list)


_copy_exported_files_from_session_folder_to_collected_outputs_kwargs = dict(BATCH_DATE_TO_USE=BATCH_DATE_TO_USE, 
        cuttoff_date=cuttoff_date, 
        target_dir=collected_outputs_path, 
        custom_file_globs_dict={'h5': '*.h5'}, 
        rename_backup_basename_fn=_across_session_h5_output_basename_fn,
)



# Define the operation as a function that takes is_dryrun parameter
def copy_session_files(is_dryrun=True):
    """
    Captures: BATCH_DATE_TO_USE, cuttoff_date, collected_outputs_path, is_dryrun
    """
    from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionHelpers
    
    print(F'BATCH_DATE_TO_USE: "{BATCH_DATE_TO_USE}"')
    print(f'collected_outputs_path: "{collected_outputs_path.as_posix()}"')
    
    # Use the provided is_dryrun parameter
    copy_dict, moved_files_dict_files = AcrossSessionHelpers._copy_exported_files_from_session_folder_to_collected_outputs(
        BATCH_DATE_TO_USE=BATCH_DATE_TO_USE, 
        cuttoff_date=cuttoff_date, 
        target_dir=collected_outputs_path, 
        custom_file_globs_dict={'h5': '*.h5'}, 
        is_dry_run=is_dryrun, rename_backup_basename_fn=_across_session_h5_output_basename_fn,
    )
    
    return (copy_dict, moved_files_dict_files)

# Create the widget with your operation function
# widget = DryRunExecutionWidget(copy_session_files)


## OUTPUTS: _copy_exported_files_from_session_folder_to_collected_outputs_kwargs

BATCH_DATE_TO_USE: "2026-09-29_GL"
collected_outputs_path: "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs"

In [7]:


# copy_dict, moved_dict, (all_found_pipeline_pkl_files_dict, all_found_global_pkl_files_dict, all_found_pipeline_h5_files_dict) = try_move_pickle_files_on_GL(good_session_concrete_folders, session_basedirs_dict, computation_script_paths,
# 			is_dryrun=is_dryrun, debug_print=debug_print)

## Specify which files to match:    
# copy_dict, moved_files_dict_files = AcrossSessionHelpers._copy_exported_files_from_session_folder_to_collected_outputs(BATCH_DATE_TO_USE=BATCH_DATE_TO_USE, cuttoff_date=cuttoff_date, target_dir=collected_outputs_path, custom_file_globs_dict={
#     # 'pkl': '*standalone_wcorr_ripple_shuffle_data_only*.pkl',
#     # 'csv': '*ripple_WCorrShuffle_df*.csv',
#     'h5': '*.h5',
# }, is_dry_run=is_dryrun)

copy_dict, moved_files_dict_files = AcrossSessionHelpers._copy_exported_files_from_session_folder_to_collected_outputs(**(_copy_exported_files_from_session_folder_to_collected_outputs_kwargs | dict(custom_file_globs_dict={
    # 'pkl': '*standalone_wcorr_ripple_shuffle_data_only*.pkl',
    'csv': '*ripple_WCorrShuffle_df*.csv',
    # 'h5': '*.h5',
})), is_dry_run=is_dryrun)

copy_dict

is_dry_run == True, so not actually copying...

{}

In [8]:
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionHelpers

def _across_session_h5_output_basename_fn(session_context: Optional[IdentifyingContext], session_descr: Optional[str], basename: str, *args, separator_char: str = "_"):
	""" Builds output HDF5 file name
	Captures `BATCH_DATE_TO_USE`
	"""
	# a_session_folder.context
	if session_context is not None:
		session_descr = session_context.session_name # '2006-6-07_16-40-19'
	_filename_list = [BATCH_DATE_TO_USE, session_descr, basename]
	if len(args) > 0:
		_filename_list.extend([str(a_part) for a_part in args if a_part is not None])
	return separator_char.join(_filename_list)


is_dryrun: bool = True
# is_dryrun: bool = False

assert collected_outputs_path.exists()
copy_dict, moved_files_dict_files = AcrossSessionHelpers._copy_exported_files_from_session_folder_to_collected_outputs(BATCH_DATE_TO_USE=BATCH_DATE_TO_USE, cuttoff_date=cuttoff_date, target_dir=collected_outputs_path, is_dry_run=is_dryrun, rename_backup_basename_fn=_across_session_h5_output_basename_fn)
copy_dict

is_dry_run == True, so not actually copying...

{}

# BATCH FIGURES: `gen_scripts` batch figure export copy to `collected_figures` folder via `copy_batch_output_figures_to_common_figures_dir(...)`

In [ ]:
import shutil
from pathlib import Path
from typing import List, Optional
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import copy_batch_output_figures_to_common_figures_dir

## Move figures
# generate_figures_script_paths = [Path(v) for v in ['C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_gor01_one_2006-6-07_11-26-53/figures_kdiba_gor01_one_2006-6-07_11-26-53.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_gor01_one_2006-6-08_14-26-15/figures_kdiba_gor01_one_2006-6-08_14-26-15.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_gor01_one_2006-6-09_1-22-43/figures_kdiba_gor01_one_2006-6-09_1-22-43.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_gor01_one_2006-6-12_15-55-31/figures_kdiba_gor01_one_2006-6-12_15-55-31.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_gor01_two_2006-6-07_16-40-19/figures_kdiba_gor01_two_2006-6-07_16-40-19.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_gor01_two_2006-6-08_21-16-25/figures_kdiba_gor01_two_2006-6-08_21-16-25.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_gor01_two_2006-6-09_22-24-40/figures_kdiba_gor01_two_2006-6-09_22-24-40.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_gor01_two_2006-6-12_16-53-46/figures_kdiba_gor01_two_2006-6-12_16-53-46.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_vvp01_one_2006-4-09_17-29-30/figures_kdiba_vvp01_one_2006-4-09_17-29-30.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_vvp01_one_2006-4-10_12-25-50/figures_kdiba_vvp01_one_2006-4-10_12-25-50.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_vvp01_two_2006-4-09_16-40-54/figures_kdiba_vvp01_two_2006-4-09_16-40-54.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_vvp01_two_2006-4-10_12-58-3/figures_kdiba_vvp01_two_2006-4-10_12-58-3.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_pin01_one_11-02_17-46-44/figures_kdiba_pin01_one_11-02_17-46-44.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_pin01_one_11-02_19-28-0/figures_kdiba_pin01_one_11-02_19-28-0.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_pin01_one_11-03_12-3-25/figures_kdiba_pin01_one_11-03_12-3-25.py',
#  'C:/Users/pho/repos/Spike3DWorkEnv/Spike3D/output/gen_scripts/run_kdiba_pin01_one_fet11-01_12-58-54/figures_kdiba_pin01_one_fet11-01_12-58-54.py']]

# from pathlib import Path as PosixPath
# script_folders = [PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_one_2006-6-07_11-26-53'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_one_2006-6-08_14-26-15'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_one_2006-6-09_1-22-43'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_one_2006-6-12_15-55-31'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_two_2006-6-07_16-40-19'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_two_2006-6-08_21-16-25'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_two_2006-6-09_22-24-40'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_two_2006-6-12_16-53-46'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_vvp01_one_2006-4-09_17-29-30'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_vvp01_one_2006-4-10_12-25-50'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_vvp01_two_2006-4-09_16-40-54'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_vvp01_two_2006-4-10_12-58-3'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_pin01_one_11-02_17-46-44'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_pin01_one_11-02_19-28-0'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_pin01_one_11-03_12-3-25'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_pin01_one_fet11-01_12-58-54')]

generate_figures_script_paths = ['/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_one_2006-6-07_11-26-53/figures_kdiba_gor01_one_2006-6-07_11-26-53.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_one_2006-6-08_14-26-15/figures_kdiba_gor01_one_2006-6-08_14-26-15.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_one_2006-6-09_1-22-43/figures_kdiba_gor01_one_2006-6-09_1-22-43.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_one_2006-6-12_15-55-31/figures_kdiba_gor01_one_2006-6-12_15-55-31.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_two_2006-6-07_16-40-19/figures_kdiba_gor01_two_2006-6-07_16-40-19.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_two_2006-6-08_21-16-25/figures_kdiba_gor01_two_2006-6-08_21-16-25.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_two_2006-6-09_22-24-40/figures_kdiba_gor01_two_2006-6-09_22-24-40.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_gor01_two_2006-6-12_16-53-46/figures_kdiba_gor01_two_2006-6-12_16-53-46.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_vvp01_one_2006-4-09_17-29-30/figures_kdiba_vvp01_one_2006-4-09_17-29-30.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_vvp01_one_2006-4-10_12-25-50/figures_kdiba_vvp01_one_2006-4-10_12-25-50.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_vvp01_two_2006-4-09_16-40-54/figures_kdiba_vvp01_two_2006-4-09_16-40-54.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_vvp01_two_2006-4-10_12-58-3/figures_kdiba_vvp01_two_2006-4-10_12-58-3.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_pin01_one_11-02_17-46-44/figures_kdiba_pin01_one_11-02_17-46-44.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_pin01_one_11-02_19-28-0/figures_kdiba_pin01_one_11-02_19-28-0.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_pin01_one_11-03_12-3-25/figures_kdiba_pin01_one_11-03_12-3-25.py', '/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts/run_kdiba_pin01_one_fet11-01_12-58-54/figures_kdiba_pin01_one_fet11-01_12-58-54.py']
generate_figures_script_paths = [Path(v) for v in generate_figures_script_paths]

_copied_outputs = copy_batch_output_figures_to_common_figures_dir(generate_figures_script_paths=generate_figures_script_paths, common_destination=collected_figures_path,
																   previous_gen_scripts_path=Path('/nfs/turbo/umms-kdiba/Pho/Output/gen_scripts'), curr_gen_scripts_path=None,
																    batch_export_folder_date='2026-04-09',
																	# is_dryrun=True,
																	)
_copied_outputs

## ⛓️🟢 Post-Processing of batch outputs:

In [32]:
from pyphocorehelpers.Filesystem.path_helpers import save_filelist_to_text_file


#TODO 2025-04-18 07:07: - [ ] Also move .h5 files with parameter-included filenames, like 'pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_5.0.h5'
# Example:    "W:\Data\KDIBA\gor01\one\2006-6-09_1-22-43\output\pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_5.0.h5

debug_print = False
known_global_data_root_parent_paths = [Path(r'/nfs/turbo/umms-kdiba/Data'), Path(r'W:\Data'), Path(r'/home/halechr/cloud/turbo/Data'), Path(r'/media/halechr/MAX/Data'), Path(r'/Volumes/MoverNew/data')] # , Path(r'/home/halechr/FastData'), Path(r'/home/halechr/turbo/Data'), Path(r'W:\Data'), Path(r'/home/halechr/cloud/turbo/Data')
global_data_root_parent_path = find_first_extant_path(known_global_data_root_parent_paths)
assert global_data_root_parent_path.exists(), f"global_data_root_parent_path: {global_data_root_parent_path} does not exist! Is the right computer's config commented out above?"
# Hardcoded included_session_contexts:
included_session_contexts = UserAnnotationsManager.get_hardcoded_good_sessions()
good_session_concrete_folders = ConcreteSessionFolder.build_concrete_session_folders(global_data_root_parent_path, included_session_contexts)

# Output Paths:
## OUTPUTS: included_h5_paths, included_session_contexts, good_session_concrete_folders

## INPUTS: good_session_concrete_folders, target_dir, BATCH_DATE_TO_USE

# target_dir: Path = Path(global_data_root_parent_path)
target_dir: Path = collected_outputs_path

# included_h5_paths = [Path(get_file_str_if_file_exists(v.pipeline_results_h5)).resolve() for v in good_session_concrete_folders] # 2025-04-18 07:25 - Old style 'pipeline_.h5'
included_h5_paths = []
for v in good_session_concrete_folders:
    ## find all relevant 'pipeline_*.h5' files
    matching_files = list(v.output_folder.glob('pipeline_*.h5'))
    included_h5_paths.extend([p.resolve() for p in matching_files])
	
check_output_h5_files(included_h5_paths)
if debug_print:
    included_h5_paths

## OUTPUTS: included_h5_paths

# def _across_session_h5_output_basename_fn(session_context: Optional[IdentifyingContext], session_descr: Optional[str], basename: str, *args, separator_char: str = "_"):
# 	""" Captures `BATCH_DATE_TO_USE` """
# 	# a_session_folder.context
# 	if session_context is not None:
# 		session_descr = session_context.session_name # '2006-6-07_16-40-19'
# 	_filename_list = [BATCH_DATE_TO_USE, session_descr, basename]
# 	if len(args) > 0:
# 		_filename_list.extend([str(a_part) for a_part in args if a_part is not None])
# 	return separator_char.join(_filename_list)


def _across_session_h5_output_basename_fn(session_context: Optional[IdentifyingContext], session_descr: Optional[str], basename: str, *args, separator_char: str = "_"):
	""" Builds output HDF5 file name
	Captures `BATCH_DATE_TO_USE`
	"""
	# a_session_folder.context
	if session_context is not None:
		session_descr = session_context.session_name # '2006-6-07_16-40-19'
	_filename_list = [BATCH_DATE_TO_USE, session_descr, basename]
	if len(args) > 0:
		_filename_list.extend([str(a_part) for a_part in args if a_part is not None])
	return separator_char.join(_filename_list)


# copy_h5_dict = ConcreteSessionFolder.build_backup_copydict(good_session_concrete_folders, target_dir=collected_outputs_path, backup_mode=BackupMethods.CommonTargetDirectory, rename_backup_basename_fn=_across_session_h5_output_basename_fn, only_include_file_types=['h5']) # , rename_backup_suffix=BATCH_DATE_TO_USE
# copy_h5_dict

from pyphoplacecellanalysis.General.Batch.runBatch import get_file_path_if_file_exists
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import copy_session_folder_files_to_target_dir

custom_file_types_dict = {
	                    # 'custom_h5': (lambda a_session_folder: get_file_path_if_file_exists(a_session_folder.output_folder.joinpath(f'pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5').resolve())),
						'custom_h5': (lambda a_session_folder: get_file_path_if_file_exists(a_session_folder.output_folder.joinpath(f'pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5').resolve())),
                        #   'PHONEW.evt': (lambda a_session_folder: get_file_path_if_file_exists(a_session_folder.output_folder.joinpath(f'{a_session_folder.context.session_name}.PHONEW.evt').resolve())),
                        }

copy_h5_dict = ConcreteSessionFolder.build_backup_copydict(good_session_concrete_folders, target_dir=collected_outputs_path, backup_mode=BackupMethods.CommonTargetDirectory, rename_backup_basename_fn=_across_session_h5_output_basename_fn,
    only_include_file_types=['h5'],
    # only_include_file_types=[], # exclude the un-parameterized pipeline_results.h5
    custom_file_types_dict=custom_file_types_dict) # , rename_backup_suffix=BATCH_DATE_TO_USE

# if debug_print:
#     copy_h5_dict


## INPUTS: target_dir, BATCH_DATE_TO_USE
h5_filelist_output_filename=f'{BATCH_DATE_TO_USE}_all_sessions_h5_filelist.txt'
h5_filelist_output_file_path = Path(target_dir).joinpath(h5_filelist_output_filename).resolve() # Use Default
print(f'h5_filelist_output_file_path: {h5_filelist_output_file_path}')
_out_string, filelist_path = save_filelist_to_text_file(included_h5_paths, filelist_path=h5_filelist_output_file_path, debug_print=True) # r"W:\Data\all_sessions_h5_filelist_2024-03-28_Apogee.txt"

# filelist_path

copy_h5_dict

## OUTPUTS: copy_h5_dict,

WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_2024-09-11_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_2024-09-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_2026-09-23.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_Pre2024-07-16.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-tbin_75ms.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-variant_trackBodyPeakOnly.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0-tbin_75ms.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results_2024-09-11_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results_2024-09-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_results_2023-10-26_GL.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5!
WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_results_2023-10-25_BidirectionalOnly.h5!

,path,modification_time,creation_time,file_size
0,/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-0...,2025-02-13 11:57:17.012204,2025-02-13 11:57:17.012204,3.49
1,/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-0...,2025-08-13 18:52:41.218800,2025-08-13 18:52:41.218800,3.54
2,/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-0...,2024-07-09 06:44:33.358639,2024-07-09 06:44:34.411360,1.08
3,/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-0...,2024-10-23 15:14:35.298242,2024-10-23 15:14:37.249986,1.09
4,/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-0...,2025-07-04 02:22:41.611031,2025-07-04 02:22:41.611031,2.70
...,...,...,...,...
193,/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01...,2024-09-27 03:57:28.802014,2024-09-27 03:57:31.138912,0.82
194,/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01...,2025-01-21 16:12:00.272603,2025-01-21 16:12:00.272603,1.41
195,/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01...,2026-08-28 20:14:24.837000,2026-08-28 20:14:54.584003,1.82
196,/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01...,2026-09-29 15:35:45.499283,2026-09-29 15:35:45.499283,1.15
197,/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01...,2026-09-22 14:31:12.810804,2026-09-23 15:20:03.376784,1.82

h5_filelist_output_file_path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_all_sessions_h5_filelist.txt
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results_2023-10-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.2.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results_Pre2024-07-09.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results_2024-10-23_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results_2026-09-23.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2, 4, 6, 7, 9].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results_2024-09-11_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.5.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results_2023-10-25_BidirectionalOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNewComputedReplays.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results_Pre2024-07-16.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results_2024-09-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-variant_trackBodyPeakOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results_2023-10-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.2.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results_2024-10-23_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results_2026-09-23.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2, 4, 6, 7, 9].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results_2024-09-11_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.5.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results_Pre2024-07-16.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results_2024-09-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-variant_trackBodyPeakOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_2023-10-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.2.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_Pre2024-07-09.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_2024-10-23_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_2026-09-23.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2, 4, 6, 7, 9].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_2024-09-11_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.5.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_2023-10-25_BidirectionalOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_Pre2024-07-16.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results_2024-09-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-variant_trackBodyPeakOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results_2023-10-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.2.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results_Pre2024-07-09.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results_2024-10-23_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results_2026-09-23.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2, 4, 6, 7, 9].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results_2024-09-11_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.5.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results_2023-10-25_BidirectionalOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results_Pre2024-07-16.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results_2024-09-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-variant_trackBodyPeakOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_2023-10-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.2.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_Pre2024-07-09.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_2026-09-23.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_2024-09-11_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.5.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_2023-10-25_BidirectionalOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_Pre2024-07-16.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results_2024-09-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-variant_trackBodyPeakOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results_2023-10-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.2.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results_Pre2024-07-09.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results_2026-09-23.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results_2024-09-11_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.5.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results_2023-10-25_BidirectionalOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results_Pre2024-07-16.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results_2024-09-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-variant_trackBodyPeakOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.2.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results_2024-10-23_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results_2026-09-23.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2, 4, 6, 7, 9].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results_2024-09-11_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.5.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results_Pre2024-07-16.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2].h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results_2024-09-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-variant_trackBodyPeakOnly.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results_2023-10-26_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.2.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results_Pre2024-07-09.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results_2024-10-23_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0-tbin_75ms.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results_2026-09-23.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2]-frateThresh_2.0.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_[1, 2, 4, 6, 7, 9].h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results_2024-09-11_GL.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 9]-frateThresh_4.0.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_0.5.h5
/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results_2023-10-25_BidirectionalOnly.h5

{PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')}

In [33]:
copy_h5_dict

{PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')}

# Output File Processing Helpers

## Copy exported `pipeline_results.h5` files into the `collected_outputs` folder, adding the current date
```
copying "W:\Data\KDIBA\gor01\one\2006-6-08_14-26-15\output\pipeline_results.h5"
		 -> "K:\scratch\collected_outputs\2024-06-12_Apogee_2006-6-08_14-26-15_pipeline_results.h5"...
```

In [34]:
## INPUTS: copy_h5_dict

a_copy_dict = copy_h5_dict

# Copies each file sequentially to the collected_outputs directory, and then builds an output file list
## INPUT a_copy_dict
moved_files_dict_h5_files = copy_movedict(a_copy_dict)
moved_files_dict_h5_files
# INPUTS: active_filelist_prefix, target_dir
# active_filelist_prefix: str = 'backed_up_files'
active_filelist_prefix: str = 'session_h5_files'

# target_dir: Path = Path(global_data_root_parent_path)
target_dir: Path = collected_outputs_path

moved_files_copydict_output_filename=f'{active_filelist_prefix}_copydict_{BATCH_DATE_TO_USE}.csv'
moved_files_copydict_file_path = target_dir.joinpath(moved_files_copydict_output_filename).resolve() # Use Default
print(f'moved_files_copydict_file_path: "{moved_files_copydict_file_path}"')

_out_string, filedict_out_path = save_copydict_to_text_file(moved_files_dict_h5_files, moved_files_copydict_file_path, debug_print=True)
print(f'filedict_out_path: "{filedict_out_path.as_posix()}"')

copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_results.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_results.h5"...
done.
copying "/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
		 -> "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"...
done.
done copying 22 of 22 files.

{PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_results.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')}

moved_files_copydict_file_path: "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/session_h5_files_copydict_2026-09-29_GL.csv"
src_file, operation, _out_path
"/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
"/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_results.h5"
"/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5"
saving out to "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/session_h5_files_copydict_2026-09-29_GL.csv"...
filedict_out_path: "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/session_h5_files_copydict_2026-09-29_GL.csv"

In [35]:
Path('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/session_h5_files_copydict_2026-09-29_GL.csv')

PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/session_h5_files_copydict_2026-09-29_GL.csv')

## 2024-09-04 - Batch Output Files

In [15]:
collected_outputs_path

PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs')

In [ ]:
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import copy_session_inst_fr_data_to_across_session_pkl

## Complete Concise Run:
# RESULT_DATE_TO_USE = '2025-10-22'
RESULT_DATE_TO_USE = '2026-09-29' # Working: '2026-09-25', '2026-09-29'
# RESULT_DATE_TO_USE: str = BATCH_DAY_DATE

print(f'RESULT_DATE_TO_USE: {RESULT_DATE_TO_USE}')

instantaneous_time_bin_size_seconds_list = [0.001, 1000.0]
# instantaneous_time_bin_size_seconds_list = [1000.0]

across_sessions_recomputed_instantaneous_fr_dict, moved_files_dict_files, (filelist_path, filedict_out_path) = copy_session_inst_fr_data_to_across_session_pkl(RESULT_DATE_TO_USE=RESULT_DATE_TO_USE, collected_outputs_path=collected_outputs_path, instantaneous_time_bin_size_seconds_list=instantaneous_time_bin_size_seconds_list)

# '/nfs/turbo/umms-kdiba/Data/across_session_result_long_short_recomputed_inst_firing_rate_2024-06-10_GL.pkl'
# Path('/nfs/turbo/umms-kdiba/Data/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2024-06-11_GL.pkl').resolve()
# ## Save pickle:
# inst_fr_output_filename=f'across_session_result_long_short_inst_firing_rate_{BATCH_DATE_TO_USE}.pkl'
# global_batch_result_inst_fr_file_path = Path(global_data_root_parent_path).joinpath(inst_fr_output_filename).resolve() # Use Default
# print(f'global_batch_result_inst_fr_file_path: {global_batch_result_inst_fr_file_path}')
# # Save the all sessions instantaneous firing rate dict to the path:
# saveData(global_batch_result_inst_fr_file_path, across_sessions_instantaneous_fr_dict)

In [ ]:
across_sessions_recomputed_instantaneous_fr_dict

# ! After Sessions are processed and their `.h5` files are exported, build the combined tables
The combined (across session) tables are saved out into .csv and .pkl formats: `W:\Data\2024-06-12_Apogee\neuron_identities_table.csv` -- ideally this would be in the combined outputs folder

In [ ]:
from pyphocorehelpers.Filesystem.path_helpers import read_filelist_from_text_file

# filelist_path = Path(r"K:/scratch/collected_outputs/2025-06-11_GL_all_sessions_h5_filelist.txt").resolve() # APOGEE
# filelist_path = Path('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2025-06-17_GL_all_sessions_h5_filelist.txt').resolve() # GL
# filelist_path = Path('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_all_sessions_h5_filelist.txt').resolve() # GL 2026-09-29
filelist_path = Path('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/session_h5_files_copydict_2026-09-29_GL.csv').resolve() # GL 2026-09-29
# /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/session_h5_files_copydict_2025-07-17_GL.csv
read_hdf5_output_paths = read_filelist_from_text_file(filelist_path=filelist_path, debug_print=False)
read_hdf5_output_paths

[PosixPath('/gpfs/accounts/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/src_file, operation, _out_path'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')]

In [38]:
read_hdf5_output_paths

[PosixPath('/gpfs/accounts/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/src_file, operation, _out_path'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-09_1-22-43/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-12_15-55-31/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-07_16-40-19/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-08_21-16-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-09_22-24-40/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/gor01/two/2006-6-12_16-53-46/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-09_16-40-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/vvp01/two/2006-4-10_12-58-3/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/11-03_12-3-25/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_results.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_results.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/KDIBA/pin01/one/fet11-01_12-58-54/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5", "->", "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')]

### 2025-06-11 - Get the .h5 files that were previously output (or transferred) to the CollectedOutputs directory

In [75]:
## INPUTS: cuttoff_date

included_h5_paths = []
## find all relevant 'pipeline_*.h5' files
# matching_files = list(collected_outputs_path.glob('*_pipeline_results.h5'))
# matching_files = list(collected_outputs_path.glob('2026-09-29_GL_*_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'))
matching_files = list(collected_outputs_path.glob('*_pipeline_with*.h5'))
included_h5_paths = deepcopy(matching_files)
included_h5_paths

# ## Doesn't work at all
# find_most_recent_files_kwargs = dict(should_fallback_to_filesystem_modification_datetime=True, should_print_unparsable_filenames=False, debug_print=debug_print)
# _, a_most_recent_parsed_files_df, all_parsed_files_df  = find_most_recent_files(found_session_export_paths=matching_files, cuttoff_date=cuttoff_date, **find_most_recent_files_kwargs)
# a_most_recent_parsed_files_df['filename'] = a_most_recent_parsed_files_df['path'].map(lambda x: x.name)
# a_most_recent_parsed_files_df

# all_parsed_files_df
output_h5_files_df: pd.DataFrame = check_output_h5_files(included_h5_paths)
output_h5_files_df['filename'] = output_h5_files_df['path'].map(lambda x: Path(x).name)
output_h5_files_df = output_h5_files_df.sort_values(['creation_time', 'modification_time', 'file_size'], ascending=[False, False, False], inplace=False)
output_h5_files_df.head(50)

[PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')]

WARN: file_size < 0.01 for /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5!

,path,modification_time,creation_time,file_size,filename
3,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:21:04.103710,2026-09-29 17:21:05.107430,1.15,2026-09-29_GL_fet11-01_12-58-54_pipeline_withN...
9,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:20:42.171106,2026-09-29 17:20:43.280980,0.51,2026-09-29_GL_11-03_12-3-25_pipeline_withNorma...
0,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:20:32.668155,2026-09-29 17:20:33.924193,0.71,2026-09-29_GL_2006-4-10_12-58-3_pipeline_withN...
7,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:20:20.627580,2026-09-29 17:20:21.814755,0.90,2026-09-29_GL_2006-4-09_16-40-54_pipeline_with...
1,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:19:57.837841,2026-09-29 17:19:58.391968,2.92,2026-09-29_GL_2006-6-09_22-24-40_pipeline_with...
5,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:19:21.608635,2026-09-29 17:19:22.168998,1.57,2026-09-29_GL_2006-6-08_21-16-25_pipeline_with...
4,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:19:10.168581,2026-09-29 17:19:10.762101,2.47,2026-09-29_GL_2006-6-07_16-40-19_pipeline_with...
8,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:18:37.320320,2026-09-29 17:18:38.476790,0.89,2026-09-29_GL_2006-6-12_15-55-31_pipeline_with...
6,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:18:23.848486,2026-09-29 17:18:24.440928,2.15,2026-09-29_GL_2006-6-09_1-22-43_pipeline_withN...
2,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:18:08.620817,2026-09-29 17:18:09.275753,2.39,2026-09-29_GL_2006-6-08_14-26-15_pipeline_with...

In [76]:
active_output_h5_files_df: pd.DataFrame = output_h5_files_df[output_h5_files_df['creation_time'] >= datetime(2026, 9, 29, 0, 0, 0, 0)]
active_output_h5_files_df

active_included_h5_paths = active_output_h5_files_df['path'].map(lambda v: Path(v)).to_list()

## OUTPUTS: active_output_h5_files_df, active_included_h5_paths
active_included_h5_paths

,path,modification_time,creation_time,file_size,filename
3,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:21:04.103710,2026-09-29 17:21:05.107430,1.15,2026-09-29_GL_fet11-01_12-58-54_pipeline_withN...
9,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:20:42.171106,2026-09-29 17:20:43.280980,0.51,2026-09-29_GL_11-03_12-3-25_pipeline_withNorma...
0,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:20:32.668155,2026-09-29 17:20:33.924193,0.71,2026-09-29_GL_2006-4-10_12-58-3_pipeline_withN...
7,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:20:20.627580,2026-09-29 17:20:21.814755,0.90,2026-09-29_GL_2006-4-09_16-40-54_pipeline_with...
1,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:19:57.837841,2026-09-29 17:19:58.391968,2.92,2026-09-29_GL_2006-6-09_22-24-40_pipeline_with...
5,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:19:21.608635,2026-09-29 17:19:22.168998,1.57,2026-09-29_GL_2006-6-08_21-16-25_pipeline_with...
4,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:19:10.168581,2026-09-29 17:19:10.762101,2.47,2026-09-29_GL_2006-6-07_16-40-19_pipeline_with...
8,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:18:37.320320,2026-09-29 17:18:38.476790,0.89,2026-09-29_GL_2006-6-12_15-55-31_pipeline_with...
6,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:18:23.848486,2026-09-29 17:18:24.440928,2.15,2026-09-29_GL_2006-6-09_1-22-43_pipeline_withN...
2,/nfs/turbo/umms-kdiba/Pho/Output/collected_out...,2026-09-29 17:18:08.620817,2026-09-29 17:18:09.275753,2.39,2026-09-29_GL_2006-6-08_14-26-15_pipeline_with...

[PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')]

In [77]:
## INPUTS: active_included_h5_paths, active_output_h5_files_df
[v.as_posix() for v in active_included_h5_paths]

['/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5',
 '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5',
 '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5',
 '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5',
 '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5',
 '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5',
 '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5',
 '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5',
 '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5',
 '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5']

In [78]:
## Compare the path's filename with the `job_suffix` to see if it's a match. Filenames might contain extra spaces, commas (',') or hard-brackets ('[]') that should be ignored for comparison's sake:
# a_path: Path = Path('/nfs/turbo/umms-kdiba/KDIBA/gor01/one/2006-6-08_14-26-15/output/pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5')
# 'pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_5.0.h5'
# Normalize the strings by removing spaces, commas and brackets
def normalize_str(s: str) -> str:
    return s.replace(' ', '').replace(',', '').replace('[', '').replace(']', '')

# display(included_h5_paths)
# filename_normalized_job_suffix: str = normalize_str(job_suffix)
# filename_normalized_job_suffix.split('-'

# filename_normalized_job_suffix: str = '_withNormalComputedReplays-qclu_1246789-frateThresh_5.0' # #TODO 2025-06-11 13:55: - [ ] HARDCODED
filename_normalized_job_suffix: str = '_withNormalComputedReplays-qclu_1246789-frateThresh_2.0' # #TODO 2025-06-11 13:55: - [ ] HARDCODED
# filename_normalized_job_suffix: str = '_withNormalComputedReplays-qclu_12-frateThresh_5.0' # #TODO 2025-06-11 13:55: - [ ] HARDCODED


display(filename_normalized_job_suffix) # '_withNormalComputedReplays-qclu_1246789-frateThresh_5.0_tbin_25ms'
# [normalize_str(a_path.name) for a_path in included_h5_paths] 


# ## Use all `included_h5_paths`
# active_included_h5_paths = deepcopy(included_h5_paths)
## use filtered paths:
included_h5_paths = deepcopy(active_included_h5_paths)

initial_included_h5_paths: int = len(included_h5_paths)

# '_withNormalComputedReplays-qclu_1246789-frateThresh_5.0_tbin_25ms' in 'pipeline_withNormalComputedReplays-qclu_1246789-frateThresh_5.0.h5'

# 'pipeline_withNormalComputedReplays-qclu_1246789-frateThresh_5.0.h5',
#  'pipeline_withNormalComputedReplays-qclu_12-frateThresh_5.0.h5',
#  'pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_124679.h5',
#  'pipeline_results_2024-09-11_GL.h5',
#  'pipeline_withNormalComputedReplays-qclu_124679-frateThresh_4.0.h5',
#  'pipeline_results_2023-10-25_BidirectionalOnly.h5',
#  'pipeline_results.h5',
#  'pipeline_results_Pre2024-07-16.h5',
#  'pipeline_withNormalComputedReplays-frateThresh_5.0-qclu_12.h5',
#  'pipeline_results_2024-09-26_GL.h5',
#  'pipeline_withNormalComputedReplays-qclu_12-frateThresh_4.0.h5',
# Check if normalized suffix is in normalized filename
active_included_h5_paths = [a_path for a_path in included_h5_paths if (filename_normalized_job_suffix in normalize_str(a_path.stem))]
print(f'including: {len(active_included_h5_paths)}/{initial_included_h5_paths} h5 paths for job_suffix: {job_suffix}')
active_included_h5_paths

'_withNormalComputedReplays-qclu_1246789-frateThresh_2.0'

including: 10/10 h5 paths for job_suffix: _withNormalComputedReplays-qclu_1246789-frateThresh_2.0_tbin_25ms

[PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')]

In [ ]:
# ## Use all `included_h5_paths`
# active_included_h5_paths = deepcopy(included_h5_paths)

## Use only recent ones in 'active_included_h5_paths'
active_included_h5_paths = deepcopy(active_included_h5_paths)
active_included_h5_paths

# [PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
#  PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
#  PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
#  PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
#  PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
#  PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
#  PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
#  PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
#  PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
#  PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')]

[PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')]

In [ ]:
['kdiba_gor01_one_2006-6-08_14-26-15', 'kdiba_gor01_one_2006-6-09_1-22-43', 'kdiba_gor01_one_2006-6-12_15-55-31', 'kdiba_gor01_two_2006-6-07_16-40-19', 'kdiba_gor01_two_2006-6-08_21-16-25', 'kdiba_gor01_two_2006-6-09_22-24-40', 'kdiba_gor01_two_2006-6-12_16-53-46', 'kdiba_vvp01_two_2006-4-09_16-40-54', 'kdiba_vvp01_two_2006-4-10_12-58-3', 'kdiba_pin01_one_11-03_12-3-25', 'kdiba_pin01_one_fet11-01_12-58-54'] is not equal length to file_list: 
[PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_results.h5'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_results.h5'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_results.h5'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_results.h5'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_16-53-46_pipeline_results.h5'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_results.h5'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_results.h5'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_results.h5'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_results.h5'), PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_results.h5')]

In [80]:
## INPUTS:active_included_h5_paths
[len(v) for v in (included_session_contexts, active_included_h5_paths)]

print([v.session_name for v in included_session_contexts])

if len(included_session_contexts) != len(active_included_h5_paths):
    print(f'initially len(included_session_contexts): {len(included_session_contexts)} != len(active_included_h5_paths): {len(active_included_h5_paths)}')
    print(f'\tfixing...')
    # 2026-09-29 3pm Missing Session: '21-16-25'
    missing_session_contexts = [IdentifyingContext(format_name= 'kdiba', animal= 'gor01', exper_name= 'two', session_name= '2006-6-08_21-16-25')]
    included_session_contexts = [v for v in included_session_contexts if (v not in missing_session_contexts)]
    active_included_h5_paths.reverse() ## do exactly once!
    
assert (len(included_session_contexts) == len(active_included_h5_paths)), f'len(included_session_contexts): {len(included_session_contexts)} != len(active_included_h5_paths): {len(active_included_h5_paths)}'
print(f'good.')
included_session_contexts
active_included_h5_paths

[10, 10]

['2006-6-08_14-26-15', '2006-6-09_1-22-43', '2006-6-12_15-55-31', '2006-6-07_16-40-19', '2006-6-09_22-24-40', '2006-6-12_16-53-46', '2006-4-09_16-40-54', '2006-4-10_12-58-3', '11-03_12-3-25', 'fet11-01_12-58-54']
good.

[Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'one', session_name= '2006-6-08_14-26-15'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'one', session_name= '2006-6-09_1-22-43'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'one', session_name= '2006-6-12_15-55-31'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'two', session_name= '2006-6-07_16-40-19'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'two', session_name= '2006-6-09_22-24-40'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'two', session_name= '2006-6-12_16-53-46'),
 Context(format_name= 'kdiba', animal= 'vvp01', exper_name= 'two', session_name= '2006-4-09_16-40-54'),
 Context(format_name= 'kdiba', animal= 'vvp01', exper_name= 'two', session_name= '2006-4-10_12-58-3'),
 Context(format_name= 'kdiba', animal= 'pin01', exper_name= 'one', session_name= '11-03_12-3-25'),
 Context(format_name= 'kdiba', animal= 'pin01', exper_name= 'one', session_name= 'fet11-01_12-58-54')]

[PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')]

In [83]:
active_included_h5_paths.reverse()

In [84]:
dict(zip(included_session_contexts, active_included_h5_paths))

{Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'one', session_name= '2006-6-08_14-26-15'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_14-26-15_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'one', session_name= '2006-6-09_1-22-43'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_1-22-43_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'one', session_name= '2006-6-12_15-55-31'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-12_15-55-31_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'two', session_name= '2006-6-07_16-40-19'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-07_16-40-19_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'two', session_name= '2006-6-09_22-24-40'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 Context(format_name= 'kdiba', animal= 'gor01', exper_name= 'two', session_name= '2006-6-12_16-53-46'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 Context(format_name= 'kdiba', animal= 'vvp01', exper_name= 'two', session_name= '2006-4-09_16-40-54'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-09_16-40-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 Context(format_name= 'kdiba', animal= 'vvp01', exper_name= 'two', session_name= '2006-4-10_12-58-3'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-4-10_12-58-3_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 Context(format_name= 'kdiba', animal= 'pin01', exper_name= 'one', session_name= '11-03_12-3-25'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_11-03_12-3-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5'),
 Context(format_name= 'kdiba', animal= 'pin01', exper_name= 'one', session_name= 'fet11-01_12-58-54'): PosixPath('/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_fet11-01_12-58-54_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5')}

In [85]:
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionTables

## FILE_OUTPUTS: '/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2024-10-22_GL'

## INPUTS: included_session_contexts, active_included_h5_paths, global_data_root_parent_path, BATCH_DATE_TO_USE, job_suffix
# neuron_identities_table, long_short_fr_indicies_analysis_table, neuron_replay_stats_table = AcrossSessionTables.build_all_known_tables(included_session_contexts, active_included_h5_paths, should_restore_native_column_types=True, )

assert (len(included_session_contexts) == len(active_included_h5_paths)), f'len(included_session_contexts): {len(included_session_contexts)} != len(active_included_h5_paths): {len(active_included_h5_paths)}'

# target_dir: Path = Path(global_data_root_parent_path)
target_dir: Path = collected_outputs_path
assert target_dir.exists(), f'target_dir: "{target_dir}" does not exist!'
(neuron_identities_table, long_short_fr_indicies_analysis_table, neuron_replay_stats_table), output_path_dicts = AcrossSessionTables.build_and_save_all_combined_tables(included_session_contexts, active_included_h5_paths, override_output_parent_path=target_dir, output_path_suffix=f'{BATCH_DATE_TO_USE}')
curr_collected_outputs_folder = Path(output_path_dicts['neuron_replay_stats_table']['.csv']).resolve().parent
filesystem_path_folder_contents_widget(curr_collected_outputs_folder)

failed for file path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5, table_key: /kdiba/gor01/two/2006-6-09_22-24-40/neuron_identities/table. wth exception group ``/`` does not have a child named ``/kdiba/gor01/two/2006-6-09_22-24-40/neuron_identities/table``. Skipping.
failed for file path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5, table_key: /kdiba/gor01/two/2006-6-12_16-53-46/neuron_identities/table. wth exception group ``/`` does not have a child named ``/kdiba/gor01/two/2006-6-12_16-53-46/neuron_identities/table``. Skipping.
concatenating dataframes from 8 of 10 files
failed for file path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5, table_key: /kdiba/gor01/two/2006-6-09_22-24-40/global_computations/long_short_fr_indicies_analysis/table. wth exception group ``/`` does not have a child named ``/kdiba/gor01/two/2006-6-09_22-24-40/global_computations/long_short_fr_indicies_analysis/table``. Skipping.
failed for file path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5, table_key: /kdiba/gor01/two/2006-6-12_16-53-46/global_computations/long_short_fr_indicies_analysis/table. wth exception group ``/`` does not have a child named ``/kdiba/gor01/two/2006-6-12_16-53-46/global_computations/long_short_fr_indicies_analysis/table``. Skipping.
concatenating dataframes from 8 of 10 files
failed for file path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-08_21-16-25_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5, table_key: /kdiba/gor01/two/2006-6-09_22-24-40/global_computations/jonathan_fr_analysis/neuron_replay_stats_df/table. wth exception group ``/`` does not have a child named ``/kdiba/gor01/two/2006-6-09_22-24-40/global_computations/jonathan_fr_analysis/neuron_replay_stats_df/table``. Skipping.
failed for file path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL_2006-6-09_22-24-40_pipeline_withNormalComputedReplays-qclu_[1, 2, 4, 6, 7, 8, 9]-frateThresh_2.0.h5, table_key: /kdiba/gor01/two/2006-6-12_16-53-46/global_computations/jonathan_fr_analysis/neuron_replay_stats_df/table. wth exception group ``/`` does not have a child named ``/kdiba/gor01/two/2006-6-12_16-53-46/global_computations/jonathan_fr_analysis/neuron_replay_stats_df/table``. Skipping.
concatenating dataframes from 8 of 10 files
table: "neuron_identities_table"
writing /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL/neuron_identities_table.csv
writing /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL/neuron_identities_table.pkl
Saving (file mode 'w+b') pickle file results : "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL/neuron_identities_table.pkl"... saved pickle file
table: "long_short_fr_indicies_analysis_table"
writing /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL/long_short_fr_indicies_analysis_table.csv
writing /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL/long_short_fr_indicies_analysis_table.pkl
Saving (file mode 'w+b') pickle file results : "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL/long_short_fr_indicies_analysis_table.pkl"... saved pickle file
table: "neuron_replay_stats_table"
writing /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL/neuron_replay_stats_table.csv
writing /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL/neuron_replay_stats_table.pkl
Saving (file mode 'w+b') pickle file results : "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/2026-09-29_GL/neuron_replay_stats_table.pkl"... saved pickle file

VBox(children=(Container(value=None, children=(Html(children=[Html(children=['/nfs/turbo/umms-kdiba/Pho/Output…

In [86]:
neuron_replay_stats_table

,format_name,animal,exper_name,session_name,long_pf_peak_x,short_pf_peak_x,track_membership,long_non_replay_mean,short_non_replay_mean,non_replay_diff,...,short_LR_pf2D_peak_x,short_LR_pf2D_peak_y,short_RL_pf2D_peak_x,short_RL_pf2D_peak_y,session_uid,neuron_uid,session_datetime,session_experience_rank,session_experience_orientation_rank,is_novel_exposure
0,kdiba,gor01,one,2006-6-08_14-26-15,217.046702,NaN,LEFT_ONLY,0.433244,0.12669050118673297,-0.30655375717624345,...,NaN,NaN,NaN,NaN,kdiba|gor01|one|2006-6-08_14-26-15,kdiba|gor01|one|2006-6-08_14-26-15|2,2006-06-08 14:26:15,2,1,False
1,kdiba,gor01,one,2006-6-08_14-26-15,143.884892,202.414340,SHARED,0.283147,1.4112036762827214,1.128056393734597,...,NaN,NaN,196.779411,136.087514,kdiba|gor01|one|2006-6-08_14-26-15,kdiba|gor01|one|2006-6-08_14-26-15|3,2006-06-08 14:26:15,2,1,False
2,kdiba,gor01,one,2006-6-08_14-26-15,NaN,182.904524,RIGHT_ONLY,0.119382,0.9270008099922431,0.8076187563564371,...,NaN,NaN,175.055438,141.416338,kdiba|gor01|one|2006-6-08_14-26-15,kdiba|gor01|one|2006-6-08_14-26-15|4,2006-06-08 14:26:15,2,1,False
3,kdiba,gor01,one,2006-6-08_14-26-15,95.110352,109.742714,SHARED,2.381782,2.005994611336482,-0.37578713963689525,...,202.394818,148.505775,114.398431,143.881681,kdiba|gor01|one|2006-6-08_14-26-15,kdiba|gor01|one|2006-6-08_14-26-15|5,2006-06-08 14:26:15,2,1,False
4,kdiba,gor01,one,2006-6-08_14-26-15,NaN,NaN,SHARED,25.582706,12.679101263845226,-12.90360464805143,...,NaN,NaN,NaN,NaN,kdiba|gor01|one|2006-6-08_14-26-15,kdiba|gor01|one|2006-6-08_14-26-15|6,2006-06-08 14:26:15,2,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,kdiba,pin01,one,fet11-01_12-58-54,158.517254,148.762346,SHARED,1.105528,1.3600833110176862,0.25455494569182147,...,157.890100,136.258852,154.439905,145.607477,kdiba|pin01|one|fet11-01_12-58-54,kdiba|pin01|one|fet11-01_12-58-54|28,2009-11-01 12:58:54,0,0,True
464,kdiba,pin01,one,fet11-01_12-58-54,60.968175,104.865260,SHARED,0.930103,0.853956478280453,-0.0761465443293945,...,NaN,NaN,112.693793,143.176885,kdiba|pin01|one|fet11-01_12-58-54,kdiba|pin01|one|fet11-01_12-58-54|29,2009-11-01 12:58:54,0,0,True
465,kdiba,pin01,one,fet11-01_12-58-54,124.375076,129.252530,SHARED,0.868896,0.7496376074658525,-0.11925791321906098,...,NaN,NaN,139.373313,141.233214,kdiba|pin01|one|fet11-01_12-58-54,kdiba|pin01|one|fet11-01_12-58-54|30,2009-11-01 12:58:54,0,0,True
466,kdiba,pin01,one,fet11-01_12-58-54,221.924156,197.536886,SHARED,1.168424,1.064381225243104,-0.10404268354536783,...,NaN,NaN,NaN,NaN,kdiba|pin01|one|fet11-01_12-58-54,kdiba|pin01|one|fet11-01_12-58-54|31,2009-11-01 12:58:54,0,0,True
467,kdiba,pin01,one,fet11-01_12-58-54,70.723083,104.865260,SHARED,1.265247,0.4596231501675171,-0.8056240995975373,...,NaN,NaN,109.958889,141.672976,kdiba|pin01|one|fet11-01_12-58-54,kdiba|pin01|one|fet11-01_12-58-54|32,2009-11-01 12:58:54,0,0,True

# 2024-06-12 11:18: - [ ] HACK: reads back in the exported `neuron_replay_stats_table` CSV to fix an issue with pd.NA and np.nan not reading a NaNs and the dtypes of the columns being messed up on load:

In [87]:
_curr_read_path = output_path_dicts['neuron_replay_stats_table']['.csv']
# _curr_read_path = Path('/Users/pho/University of Michigan Dropbox/MED-DibaLabDropbox/Data/Pho/Outputs/output/collected_outputs/2024-06-12_Apogee/neuron_replay_stats_table.csv').resolve()
neuron_replay_stats_table: pd.DataFrame = pd.read_csv(_curr_read_path, na_values=['', 'nan', 'np.nan','<NA>'],
										dtype={
											'long_pf_peak_x': 'float64', 
											'short_pf_peak_x': 'float64',
											'long_LR_pf2D_peak_x': 'float64',
											'long_LR_pf2D_peak_y': 'float64',
											'long_RL_pf2D_peak_x': 'float64',
											'long_RL_pf2D_peak_y': 'float64',
											'short_LR_pf2D_peak_x': 'float64',
											'short_LR_pf2D_peak_y': 'float64',
											'short_RL_pf2D_peak_x': 'float64',
											'short_RL_pf2D_peak_y': 'float64',
											'long_LR_pf1D_peak': 'float64',
											'long_RL_pf1D_peak': 'float64',
											'short_LR_pf1D_peak': 'float64',
											'short_RL_pf1D_peak': 'float64',
											'peak_diff_RL_pf1D_peak': 'float64',
											'peak_diff_LR_pf1D_peak': 'float64'
										}, index_col='neuron_uid')
neuron_replay_stats_table

,Unnamed: 0,format_name,animal,exper_name,session_name,long_pf_peak_x,short_pf_peak_x,track_membership,long_non_replay_mean,short_non_replay_mean,...,long_RL_pf2D_peak_y,short_LR_pf2D_peak_x,short_LR_pf2D_peak_y,short_RL_pf2D_peak_x,short_RL_pf2D_peak_y,session_uid,session_datetime,session_experience_rank,session_experience_orientation_rank,is_novel_exposure
neuron_uid,,,,,,,,,,,,,,,,,,,,,
kdiba|gor01|one|2006-6-08_14-26-15|2,0,kdiba,gor01,one,2006-6-08_14-26-15,217.046702,NaN,LEFT_ONLY,0.433244,0.126691,...,NaN,NaN,NaN,NaN,NaN,kdiba|gor01|one|2006-6-08_14-26-15,2006-06-08 14:26:15,2,1,False
kdiba|gor01|one|2006-6-08_14-26-15|3,1,kdiba,gor01,one,2006-6-08_14-26-15,143.884892,202.414340,SHARED,0.283147,1.411204,...,NaN,NaN,NaN,196.779411,136.087514,kdiba|gor01|one|2006-6-08_14-26-15,2006-06-08 14:26:15,2,1,False
kdiba|gor01|one|2006-6-08_14-26-15|4,2,kdiba,gor01,one,2006-6-08_14-26-15,NaN,182.904524,RIGHT_ONLY,0.119382,0.927001,...,NaN,NaN,NaN,175.055438,141.416338,kdiba|gor01|one|2006-6-08_14-26-15,2006-06-08 14:26:15,2,1,False
kdiba|gor01|one|2006-6-08_14-26-15|5,3,kdiba,gor01,one,2006-6-08_14-26-15,95.110352,109.742714,SHARED,2.381782,2.005995,...,140.515670,202.394818,148.505775,114.398431,143.881681,kdiba|gor01|one|2006-6-08_14-26-15,2006-06-08 14:26:15,2,1,False
kdiba|gor01|one|2006-6-08_14-26-15|6,4,kdiba,gor01,one,2006-6-08_14-26-15,NaN,NaN,SHARED,25.582706,12.679101,...,NaN,NaN,NaN,NaN,NaN,kdiba|gor01|one|2006-6-08_14-26-15,2006-06-08 14:26:15,2,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
kdiba|pin01|one|fet11-01_12-58-54|28,463,kdiba,pin01,one,fet11-01_12-58-54,158.517254,148.762346,SHARED,1.105528,1.360083,...,NaN,157.890100,136.258852,154.439905,145.607477,kdiba|pin01|one|fet11-01_12-58-54,2009-11-01 12:58:54,0,0,True
kdiba|pin01|one|fet11-01_12-58-54|29,464,kdiba,pin01,one,fet11-01_12-58-54,60.968175,104.865260,SHARED,0.930103,0.853956,...,NaN,NaN,NaN,112.693793,143.176885,kdiba|pin01|one|fet11-01_12-58-54,2009-11-01 12:58:54,0,0,True
kdiba|pin01|one|fet11-01_12-58-54|30,465,kdiba,pin01,one,fet11-01_12-58-54,124.375076,129.252530,SHARED,0.868896,0.749638,...,143.188683,NaN,NaN,139.373313,141.233214,kdiba|pin01|one|fet11-01_12-58-54,2009-11-01 12:58:54,0,0,True
kdiba|pin01|one|fet11-01_12-58-54|31,466,kdiba,pin01,one,fet11-01_12-58-54,221.924156,197.536886,SHARED,1.168424,1.064381,...,138.411001,NaN,NaN,NaN,NaN,kdiba|pin01|one|fet11-01_12-58-54,2009-11-01 12:58:54,0,0,True
kdiba|pin01|one|fet11-01_12-58-54|32,467,kdiba,pin01,one,fet11-01_12-58-54,70.723083,104.865260,SHARED,1.265247,0.459623,...,148.882558,NaN,NaN,109.958889,141.672976,kdiba|pin01|one|fet11-01_12-58-54,2009-11-01 12:58:54,0,0,True

In [88]:
# from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.MultiContextComputationFunctions.LongShortTrackComputations import TruncationCheckingResults

# truncation_checking_aclus_dict, jonathan_firing_rate_analysis_result.neuron_replay_stats_df = truncation_checking_result.build_truncation_checking_aclus_dict(neuron_replay_stats_df=jonathan_firing_rate_analysis_result.neuron_replay_stats_df)

# 'is_rate_extrema', 'is_refined_exclusive', 'is_refined_LxC', 'is_refined_SxC'
# 'is_long_peak_left_cap', 'is_long_peak_right_cap', 'is_long_peak_either_cap'

from pyphoplacecellanalysis.SpecificResults.PendingNotebookCode import _add_cell_remapping_category

neuron_replay_stats_df = deepcopy(neuron_replay_stats_table)

neuron_replay_stats_df, (non_disappearing_endcap_cells_df, disappearing_endcap_cells_df, minorly_changed_endcap_cells_df, significant_distant_remapping_endcap_cells_df) = _add_cell_remapping_category(neuron_replay_stats_df=neuron_replay_stats_df,
													   loaded_track_limits = {'long_xlim': np.array([59.0774, 228.69]), 'short_xlim': np.array([94.0156, 193.757]), 'long_ylim': np.array([138.164, 146.12]), 'short_ylim': np.array([138.021, 146.263])},
)
# neuron_replay_stats_df
significant_distant_remapping_endcap_cells_df

loaded_track_limits: {'long_xlim': array([ 59.0774, 228.69  ]), 'short_xlim': array([ 94.0156, 193.757 ]), 'long_ylim': array([138.164, 146.12 ]), 'short_ylim': array([138.021, 146.263])}
num_disappearing_endcap_cells/num_total_endcap_cells: 10/89
num_non_disappearing_endcap_cells/num_total_endcap_cells: 79/89
num_significant_position_remappping_endcap_cells/num_non_disappearing_endcap_cells: 8/79

/gpfs/accounts/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/pyPhoPlaceCellAnalysis/src/pyphoplacecellanalysis/SpecificResults/PendingNotebookCode.py:20496: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_disappearing_endcap_cells_df['has_significant_distance_remapping'] = (np.abs(non_disappearing_endcap_cells_df['LS_pf_peak_x_diff']) >= min_significant_remapping_x_distance) # The most a placefield could translate intwards would be (35 + (pf_width/2.0)) I think.

,Unnamed: 0,format_name,animal,exper_name,session_name,long_pf_peak_x,short_pf_peak_x,track_membership,long_non_replay_mean,short_non_replay_mean,...,session_experience_rank,session_experience_orientation_rank,is_novel_exposure,has_long_pf,has_short_pf,is_long_peak_left_cap,is_long_peak_right_cap,is_long_peak_either_cap,LS_pf_peak_x_diff,has_significant_distance_remapping
neuron_uid,,,,,,,,,,,,,,,,,,,,,
kdiba|gor01|one|2006-6-08_14-26-15|62,60,kdiba,gor01,one,2006-6-08_14-26-15,231.679064,168.272162,SHARED,3.117404,2.067092,...,2,1,False,True,True,False,True,True,63.406902,True
kdiba|gor01|one|2006-6-08_14-26-15|63,61,kdiba,gor01,one,2006-6-08_14-26-15,241.433971,80.477990,SHARED,2.194687,1.551310,...,2,1,False,True,True,False,True,True,160.955981,True
kdiba|gor01|one|2006-6-09_1-22-43|58,164,kdiba,gor01,one,2006-6-09_1-22-43,246.311425,163.394708,SHARED,0.517875,1.224871,...,5,2,False,True,True,False,True,True,82.916717,True
kdiba|gor01|one|2006-6-09_1-22-43|61,167,kdiba,gor01,one,2006-6-09_1-22-43,241.433971,168.272162,SHARED,2.253096,1.847349,...,5,2,False,True,True,False,True,True,73.161810,True
kdiba|gor01|one|2006-6-09_1-22-43|89,195,kdiba,gor01,one,2006-6-09_1-22-43,36.580905,139.007438,SHARED,2.109387,1.451521,...,5,2,False,True,True,True,False,True,-102.426533,True
kdiba|gor01|two|2006-6-07_16-40-19|64,325,kdiba,gor01,two,2006-6-07_16-40-19,241.433971,109.742714,SHARED,2.835882,5.461732,...,1,0,True,True,True,False,True,True,131.691257,True
kdiba|vvp01|two|2006-4-09_16-40-54|21,346,kdiba,vvp01,two,2006-4-09_16-40-54,231.679064,95.110352,SHARED,3.921731,1.256094,...,0,0,True,True,True,False,True,True,136.568711,True
kdiba|pin01|one|fet11-01_12-58-54|26,461,kdiba,pin01,one,fet11-01_12-58-54,41.458359,109.742714,SHARED,2.412247,2.812436,...,0,0,True,True,True,True,False,True,-68.284356,True

In [89]:
neuron_replay_stats_df

,Unnamed: 0,format_name,animal,exper_name,session_name,long_pf_peak_x,short_pf_peak_x,track_membership,long_non_replay_mean,short_non_replay_mean,...,session_datetime,session_experience_rank,session_experience_orientation_rank,is_novel_exposure,has_long_pf,has_short_pf,is_long_peak_left_cap,is_long_peak_right_cap,is_long_peak_either_cap,LS_pf_peak_x_diff
neuron_uid,,,,,,,,,,,,,,,,,,,,,
kdiba|gor01|one|2006-6-08_14-26-15|2,0,kdiba,gor01,one,2006-6-08_14-26-15,217.046702,NaN,LEFT_ONLY,0.433244,0.126691,...,2006-06-08 14:26:15,2,1,False,True,False,False,False,False,NaN
kdiba|gor01|one|2006-6-08_14-26-15|3,1,kdiba,gor01,one,2006-6-08_14-26-15,143.884892,202.414340,SHARED,0.283147,1.411204,...,2006-06-08 14:26:15,2,1,False,True,True,False,False,False,-58.529448
kdiba|gor01|one|2006-6-08_14-26-15|4,2,kdiba,gor01,one,2006-6-08_14-26-15,NaN,182.904524,RIGHT_ONLY,0.119382,0.927001,...,2006-06-08 14:26:15,2,1,False,False,True,False,False,False,NaN
kdiba|gor01|one|2006-6-08_14-26-15|5,3,kdiba,gor01,one,2006-6-08_14-26-15,95.110352,109.742714,SHARED,2.381782,2.005995,...,2006-06-08 14:26:15,2,1,False,True,True,False,False,False,-14.632362
kdiba|gor01|one|2006-6-08_14-26-15|6,4,kdiba,gor01,one,2006-6-08_14-26-15,NaN,NaN,SHARED,25.582706,12.679101,...,2006-06-08 14:26:15,2,1,False,False,False,False,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
kdiba|pin01|one|fet11-01_12-58-54|28,463,kdiba,pin01,one,fet11-01_12-58-54,158.517254,148.762346,SHARED,1.105528,1.360083,...,2009-11-01 12:58:54,0,0,True,True,True,False,False,False,9.754908
kdiba|pin01|one|fet11-01_12-58-54|29,464,kdiba,pin01,one,fet11-01_12-58-54,60.968175,104.865260,SHARED,0.930103,0.853956,...,2009-11-01 12:58:54,0,0,True,True,True,False,False,False,-43.897086
kdiba|pin01|one|fet11-01_12-58-54|30,465,kdiba,pin01,one,fet11-01_12-58-54,124.375076,129.252530,SHARED,0.868896,0.749638,...,2009-11-01 12:58:54,0,0,True,True,True,False,False,False,-4.877454
kdiba|pin01|one|fet11-01_12-58-54|31,466,kdiba,pin01,one,fet11-01_12-58-54,221.924156,197.536886,SHARED,1.168424,1.064381,...,2009-11-01 12:58:54,0,0,True,True,True,False,False,False,24.387270
kdiba|pin01|one|fet11-01_12-58-54|32,467,kdiba,pin01,one,fet11-01_12-58-54,70.723083,104.865260,SHARED,1.265247,0.459623,...,2009-11-01 12:58:54,0,0,True,True,True,False,False,False,-34.142178

In [90]:
# non_disappearing_endcap_cells_df
significant_distant_remapping_endcap_cells_df
# 'track_membership'

,Unnamed: 0,format_name,animal,exper_name,session_name,long_pf_peak_x,short_pf_peak_x,track_membership,long_non_replay_mean,short_non_replay_mean,...,session_experience_rank,session_experience_orientation_rank,is_novel_exposure,has_long_pf,has_short_pf,is_long_peak_left_cap,is_long_peak_right_cap,is_long_peak_either_cap,LS_pf_peak_x_diff,has_significant_distance_remapping
neuron_uid,,,,,,,,,,,,,,,,,,,,,
kdiba|gor01|one|2006-6-08_14-26-15|62,60,kdiba,gor01,one,2006-6-08_14-26-15,231.679064,168.272162,SHARED,3.117404,2.067092,...,2,1,False,True,True,False,True,True,63.406902,True
kdiba|gor01|one|2006-6-08_14-26-15|63,61,kdiba,gor01,one,2006-6-08_14-26-15,241.433971,80.477990,SHARED,2.194687,1.551310,...,2,1,False,True,True,False,True,True,160.955981,True
kdiba|gor01|one|2006-6-09_1-22-43|58,164,kdiba,gor01,one,2006-6-09_1-22-43,246.311425,163.394708,SHARED,0.517875,1.224871,...,5,2,False,True,True,False,True,True,82.916717,True
kdiba|gor01|one|2006-6-09_1-22-43|61,167,kdiba,gor01,one,2006-6-09_1-22-43,241.433971,168.272162,SHARED,2.253096,1.847349,...,5,2,False,True,True,False,True,True,73.161810,True
kdiba|gor01|one|2006-6-09_1-22-43|89,195,kdiba,gor01,one,2006-6-09_1-22-43,36.580905,139.007438,SHARED,2.109387,1.451521,...,5,2,False,True,True,True,False,True,-102.426533,True
kdiba|gor01|two|2006-6-07_16-40-19|64,325,kdiba,gor01,two,2006-6-07_16-40-19,241.433971,109.742714,SHARED,2.835882,5.461732,...,1,0,True,True,True,False,True,True,131.691257,True
kdiba|vvp01|two|2006-4-09_16-40-54|21,346,kdiba,vvp01,two,2006-4-09_16-40-54,231.679064,95.110352,SHARED,3.921731,1.256094,...,0,0,True,True,True,False,True,True,136.568711,True
kdiba|pin01|one|fet11-01_12-58-54|26,461,kdiba,pin01,one,fet11-01_12-58-54,41.458359,109.742714,SHARED,2.412247,2.812436,...,0,0,True,True,True,True,False,True,-68.284356,True

## Required for Interactive Plotting and figure displace

In [91]:
neuron_replay_stats_table.index.unique() #['neuron_uid'].unique()

Index(['kdiba|gor01|one|2006-6-08_14-26-15|2',
       'kdiba|gor01|one|2006-6-08_14-26-15|3',
       'kdiba|gor01|one|2006-6-08_14-26-15|4',
       'kdiba|gor01|one|2006-6-08_14-26-15|5',
       'kdiba|gor01|one|2006-6-08_14-26-15|6',
       'kdiba|gor01|one|2006-6-08_14-26-15|7',
       'kdiba|gor01|one|2006-6-08_14-26-15|8',
       'kdiba|gor01|one|2006-6-08_14-26-15|9',
       'kdiba|gor01|one|2006-6-08_14-26-15|10',
       'kdiba|gor01|one|2006-6-08_14-26-15|11',
       ...
       'kdiba|pin01|one|fet11-01_12-58-54|23',
       'kdiba|pin01|one|fet11-01_12-58-54|24',
       'kdiba|pin01|one|fet11-01_12-58-54|25',
       'kdiba|pin01|one|fet11-01_12-58-54|26',
       'kdiba|pin01|one|fet11-01_12-58-54|27',
       'kdiba|pin01|one|fet11-01_12-58-54|28',
       'kdiba|pin01|one|fet11-01_12-58-54|29',
       'kdiba|pin01|one|fet11-01_12-58-54|30',
       'kdiba|pin01|one|fet11-01_12-58-54|31',
       'kdiba|pin01|one|fet11-01_12-58-54|32'],
      dtype='object', name='neuron_uid', length=468)

In [92]:

from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionsVisualizations

matplotlib_configuration_update(is_interactive=True, backend='Qt5Agg')
num_sessions: int = 10
graphics_output_dict = AcrossSessionsVisualizations.across_sessions_firing_rate_index_figure(long_short_fr_indicies_analysis_results=long_short_fr_indicies_analysis_table, num_sessions=num_sessions, save_figure=True)

num_above_diagonal/total_num_points: 202/468
percent_below_diagonal: 56.1965811965812%
percent_above_diagonal: 43.162393162393165%
WARNING: missing 3 keys from context: ['animal', 'exper_name', 'session_name']. Building path anyway.

/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_fontconfig_pattern.py:88: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_fontconfig_pattern.py:92: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_mathtext.py:2010: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  p.space          = oneOf(self._space_widths)("space")
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_mathtext.py:2015: PyparsingDeprecationWarning: 'leaveWhitespace' deprecated - use 'leave_whitespace'
  p.symbol         = Regex(
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_mathtext.py:1984: PyparsingDeprecationWarning: 'setName' deprecated - use 'set_name'
  val.setName(key)
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_mathtext.py:1987: PyparsingDeprecationWarning: 'setParseAction' deprecated - use 'set_parse_action'
  val.setParseAction(getattr(self, key))
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_mathtext.py:2080: PyparsingDeprecationWarning: 'endQuoteChar' argument is deprecated, use 'end_quote_char'
  p.text = cmd(r"\text", QuotedString('{', '\\', endQuoteChar="}"))
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_mathtext.py:2138: PyparsingDeprecationWarning: 'unquoteResults' argument is deprecated, use 'unquote_results'
  p.math_string   = QuotedString('$', '\\', unquoteResults=False)
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_mathtext.py:2162: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  result = self._expression.parseString(s)
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/pyparsing/util.py:466: PyparsingDeprecationWarning: 'parseAll' argument is deprecated, use 'parse_all'
  return fn(self, *args, **kwargs)
/scratch/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/.venv/lib/python3.9/site-packages/matplotlib/_mathtext.py:2170: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  ParserElement.resetCache()

register_output_file(output_path: /gpfs/accounts/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/EXTERNAL/Screenshots/ProgrammaticDisplayFunctionTesting/2026-09-29/kdiba/10_across_sessions_firing_rate_index.png, ...)
	 saved "file:///gpfs/accounts/kdiba_root/kdiba99/halechr/repos/Spike3D_ExploreEnv/Spike3D/EXTERNAL/Screenshots/ProgrammaticDisplayFunctionTesting/2026-09-29/kdiba/10_across_sessions_firing_rate_index.png"

## Extract output files from all completed sessions:

# 2023-10-04 - Load Saved across-sessions-data, process, and produce figures

In [ ]:
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionsResults, AcrossSessionsVisualizations

# 'collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2024-06-11_GL.pkl'
# across_session_result_long_short_recomputed_inst_firing_rate_file = collected_outputs_path.joinpath('across_session_result_long_short_recomputed_inst_firing_rate_2024-06-11_GL.pkl').resolve()
across_session_result_long_short_recomputed_inst_firing_rate_file = collected_outputs_path.joinpath('across_session_result_long_short_recomputed_inst_firing_rate_2025-06-11_1000.0.pkl').resolve() # "K:\scratch\collected_outputs\across_session_result_long_short_recomputed_inst_firing_rate_2025-06-11_1000.0.pkl"
across_session_result_long_short_recomputed_inst_firing_rate_file.exists()

In [93]:
# When done, `result_handler.across_sessions_instantaneous_fr_dict` is now equivalent to what it would have been before. It can be saved using the normal `.save_across_sessions_data(...)`

## INPUTS: BATCH_DATE_TO_USE, BATCH_DATE_TO_USE
print(f"BATCH_DATE_TO_USE: {BATCH_DATE_TO_USE}")
## Save the instantaneous firing rate results dict: (# Dict[IdentifyingContext] = InstantaneousSpikeRateGroupsComputation)
# AcrossSessionsResults.save_across_sessions_data(across_sessions_instantaneous_fr_dict=across_sessions_instantaneous_fr_dict, global_data_root_parent_path=global_data_root_parent_path,
#                                                  inst_fr_output_filename=f'across_session_result_long_short_inst_firing_rate_{BATCH_DATE_TO_USE}.pkl')

across_session_result_long_short_recomputed_inst_firing_rate_filename: str = f'across_session_result_long_short_recomputed_inst_firing_rate_{BATCH_DATE_TO_USE}.pkl'
# "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2024-10-22_GL.pkl"

# AcrossSessionsResults.save_across_sessions_data(across_sessions_instantaneous_fr_dict=across_sessions_recomputed_instantaneous_fr_dict, global_data_root_parent_path=global_data_root_parent_path,
#                                                  inst_fr_output_filename=across_session_result_long_short_recomputed_inst_firing_rate_filename)

AcrossSessionsResults.save_across_sessions_data(across_sessions_instantaneous_fr_dict=across_sessions_recomputed_instantaneous_fr_dict, global_data_root_parent_path=collected_outputs_path.resolve(),
												 inst_fr_output_filename=across_session_result_long_short_recomputed_inst_firing_rate_filename)


# "/nfs/turbo/umms-kdiba/Data/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2024-09-26_GL.pkl"

# '/nfs/turbo/umms-kdiba/Data/across_session_result_long_short_recomputed_inst_firing_rate_2024-06-10_GL.pkl'
# Path('/nfs/turbo/umms-kdiba/Data/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2024-06-11_GL.pkl').resolve()
# ## Save pickle:
# inst_fr_output_filename=f'across_session_result_long_short_inst_firing_rate_{BATCH_DATE_TO_USE}.pkl'
# global_batch_result_inst_fr_file_path = Path(global_data_root_parent_path).joinpath(inst_fr_output_filename).resolve() # Use Default
# print(f'global_batch_result_inst_fr_file_path: {global_batch_result_inst_fr_file_path}')
# # Save the all sessions instantaneous firing rate dict to the path:
# saveData(global_batch_result_inst_fr_file_path, across_sessions_instantaneous_fr_dict)

BATCH_DATE_TO_USE: 2026-09-29_GL
global_batch_result_inst_fr_file_path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2026-09-29_GL.pkl
Saving (file mode 'w+b') pickle file results : "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2026-09-29_GL.pkl"... 	Saved file size: 53.05 MB
saved pickle file

In [94]:
# output_path_suffix: str = '2024-09-11_GL'
# output_path_suffix: str = '2024-09-26_GL'
output_path_suffix: str = BATCH_DATE_TO_USE
# graphics_output_dict = AcrossSessionsResults.post_compute_all_sessions_processing(global_data_root_parent_path=global_data_root_parent_path, BATCH_DATE_TO_USE=BATCH_DATE_TO_USE, plotting_enabled=True)
graphics_output_dict = AcrossSessionsResults.post_compute_all_sessions_processing(global_data_root_parent_path=collected_outputs_path, output_path_suffix=output_path_suffix, plotting_enabled=True)

global_batch_result_inst_fr_file_path: /nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2026-09-29_GL.pkl
Computing loaded session pickle file results : "/nfs/turbo/umms-kdiba/Pho/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2026-09-29_GL.pkl"... done.
num_sessions: 2

AssertionError: expected values to be tuples Tuple[Context, InstantaneousSpikeRateGroupsComputation, inst_fr_t_bin_size] but were: [{IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-08_14-26-15')>: (IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-08_14-26-15')>, InstantaneousSpikeRateGroupsComputation(instantaneous_time_bin_size_seconds=1000.0, active_identifying_session_ctx=IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-08_14-26-15')>, LxC_aclus=[8, 97, 109], SxC_aclus=[4, 13, 23, 58], AnyC_aclus=array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109]), Fig2_Replay_FR=[SingleBarResult(mean=1.5414245929111965, std=1.2644458339376687, values=array([0.73497759, 3.32684465, 0.56245154]), LxC_aclus=[8, 97, 109], SxC_aclus=[4, 13, 23, 58], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.5830013291979826, std=0.5571349900913404, values=array([1.36662764, 0.12014983, 0.26222651]), LxC_aclus=[8, 97, 109], SxC_aclus=[4, 13, 23, 58], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.24067801938351396, std=0.22310880504052152, values=array([0.        , 0.10158877, 0.27288027, 0.58824304]), LxC_aclus=[8, 97, 109], SxC_aclus=[4, 13, 23, 58], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=2.4562994924393378, std=1.606067683291036, values=array([4.22397266, 0.74461052, 0.96856445, 3.88805034]), LxC_aclus=[8, 97, 109], SxC_aclus=[4, 13, 23, 58], LxC_scatter_props=None, SxC_scatter_props=None)], Fig2_Laps_FR=[SingleBarResult(mean=1.4451697084420954, std=0.4285867882496172, values=array([1.21954784, 2.0451675 , 1.07079378]), LxC_aclus=[8, 97, 109], SxC_aclus=[4, 13, 23, 58], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.0682939519613781, std=0.03315870036629374, values=array([0.11246302, 0.0325687 , 0.05985014]), LxC_aclus=[8, 97, 109], SxC_aclus=[4, 13, 23, 58], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.04973950371811914, std=0.061036644736585356, values=array([0.00927146, 0.01572859, 0.01866381, 0.15529416]), LxC_aclus=[8, 97, 109], SxC_aclus=[4, 13, 23, 58], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=1.7808579871841856, std=1.0489683786226787, values=array([1.66357954, 0.11068331, 2.69200044, 2.65716866]), LxC_aclus=[8, 97, 109], SxC_aclus=[4, 13, 23, 58], LxC_scatter_props=None, SxC_scatter_props=None)]), 1000.0), IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-09_1-22-43')>: (IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-09_1-22-43')>, InstantaneousSpikeRateGroupsComputation(instantaneous_time_bin_size_seconds=1000.0, active_identifying_session_ctx=IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-09_1-22-43')>, LxC_aclus=[3, 5, 29, 103], SxC_aclus=[16, 35, 55], AnyC_aclus=array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104]), Fig2_Replay_FR=[SingleBarResult(mean=2.1851160201257294, std=0.2243656508110564, values=array([1.86798709, 2.08860235, 2.33751288, 2.44636176]), LxC_aclus=[3, 5, 29, 103], SxC_aclus=[16, 35, 55], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=1.2287761807431608, std=0.2709321285083278, values=array([1.1617942 , 1.08161342, 0.98617411, 1.68552299]), LxC_aclus=[3, 5, 29, 103], SxC_aclus=[16, 35, 55], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.5441863715175987, std=0.36736726247415036, values=array([0.6564559 , 0.92735187, 0.04875134]), LxC_aclus=[3, 5, 29, 103], SxC_aclus=[16, 35, 55], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=1.1542989773651515, std=0.6284512680426994, values=array([1.79429294, 1.36837342, 0.30023057]), LxC_aclus=[3, 5, 29, 103], SxC_aclus=[16, 35, 55], LxC_scatter_props=None, SxC_scatter_props=None)], Fig2_Laps_FR=[SingleBarResult(mean=1.9589282392164105, std=0.39903712443621714, values=array([1.74445657, 1.50794223, 2.00345656, 2.57985759]), LxC_aclus=[3, 5, 29, 103], SxC_aclus=[16, 35, 55], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.2239996727584943, std=0.060188711086594, values=array([0.17064807, 0.28585392, 0.28212717, 0.15736953]), LxC_aclus=[3, 5, 29, 103], SxC_aclus=[16, 35, 55], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.10543676842421186, std=0.07867431909124106, values=array([0.12738522, 0.18892508, 0.        ]), LxC_aclus=[3, 5, 29, 103], SxC_aclus=[16, 35, 55], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=2.7011523165168945, std=1.6013624235616333, values=array([0.84128358, 4.75010797, 2.5120654 ]), LxC_aclus=[3, 5, 29, 103], SxC_aclus=[16, 35, 55], LxC_scatter_props=None, SxC_scatter_props=None)]), 1000.0), IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-12_15-55-31')>: (IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-12_15-55-31')>, InstantaneousSpikeRateGroupsComputation(instantaneous_time_bin_size_seconds=1000.0, active_identifying_session_ctx=IdentifyingContext<('kdiba', 'gor01', 'one', '2006-6-12_15-55-31')>, LxC_aclus=[3, 34], SxC_aclus=[30, 33], AnyC_aclus=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53]), Fig2_Replay_FR=[SingleBarResult(mean=6.336279400503827, std=5.427838354594719, values=array([11.76411776,  0.90844105]), LxC_aclus=[3, 34], SxC_aclus=[30, 33], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=2.033864149520112, std=1.7278813233189718, values=array([3.76174547, 0.30598283]), LxC_aclus=[3, 34], SxC_aclus=[30, 33], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.3006583740562667, std=0.3006583740562667, values=array([0.        , 0.60131675]), LxC_aclus=[3, 34], SxC_aclus=[30, 33], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.26435355439739583, std=0.26435355439739583, values=array([0.        , 0.52870711]), LxC_aclus=[3, 34], SxC_aclus=[30, 33], LxC_scatter_props=None, SxC_scatter_props=None)], Fig2_Laps_FR=[SingleBarResult(mean=1.7503456019890193, std=0.062466165192812007, values=array([1.68787944, 1.81281177]), LxC_aclus=[3, 34], SxC_aclus=[30, 33], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.2435077529167962, std=0.13063681998039786, values=array([0.37414457, 0.11287093]), LxC_aclus=[3, 34], SxC_aclus=[30, 33], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.031062437724082702, std=1.941571927094321e-05, values=array([0.03108185, 0.03104302]), LxC_aclus=[3, 34], SxC_aclus=[30, 33], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=2.2113201367262385, std=0.44695646963105873, values=array([2.65827661, 1.76436367]), LxC_aclus=[3, 34], SxC_aclus=[30, 33], LxC_scatter_props=None, SxC_scatter_props=None)]), 1000.0), IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-07_16-40-19')>: (IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-07_16-40-19')>, InstantaneousSpikeRateGroupsComputation(instantaneous_time_bin_size_seconds=1000.0, active_identifying_session_ctx=IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-07_16-40-19')>, LxC_aclus=[], SxC_aclus=[3, 18, 19, 65], AnyC_aclus=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]), Fig2_Replay_FR=[SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[], SxC_aclus=[3, 18, 19, 65], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[], SxC_aclus=[3, 18, 19, 65], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.341043813980355, std=0.44092781061325653, values=array([0.04894464, 1.09719608, 0.02867885, 0.18935569]), LxC_aclus=[], SxC_aclus=[3, 18, 19, 65], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=1.6052401049025091, std=1.336278249089723, values=array([0.89007224, 0.94197542, 3.91327307, 0.67563968]), LxC_aclus=[], SxC_aclus=[3, 18, 19, 65], LxC_scatter_props=None, SxC_scatter_props=None)], Fig2_Laps_FR=[SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[], SxC_aclus=[3, 18, 19, 65], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[], SxC_aclus=[3, 18, 19, 65], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.13130868898911854, std=0.13421002473833693, values=array([0.00699038, 0.20133063, 0.        , 0.31691374]), LxC_aclus=[], SxC_aclus=[3, 18, 19, 65], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=3.7882394255323417, std=3.1885700768674603, values=array([1.54859129, 1.41906938, 9.2086013 , 2.97669573]), LxC_aclus=[], SxC_aclus=[3, 18, 19, 65], LxC_scatter_props=None, SxC_scatter_props=None)]), 1000.0), IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-08_21-16-25')>: (IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-08_21-16-25')>, InstantaneousSpikeRateGroupsComputation(instantaneous_time_bin_size_seconds=1000.0, active_identifying_session_ctx=IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-08_21-16-25')>, LxC_aclus=[90], SxC_aclus=[8], AnyC_aclus=array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103]), Fig2_Replay_FR=[SingleBarResult(mean=0.28056277152933057, std=0.0, values=array([0.28056277]), LxC_aclus=[90], SxC_aclus=[8], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.7984374608164411, std=0.0, values=array([0.79843746]), LxC_aclus=[90], SxC_aclus=[8], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=2.6854358376161866, std=0.0, values=array([2.68543584]), LxC_aclus=[90], SxC_aclus=[8], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=2.907563715891809, std=0.0, values=array([2.90756372]), LxC_aclus=[90], SxC_aclus=[8], LxC_scatter_props=None, SxC_scatter_props=None)], Fig2_Laps_FR=[SingleBarResult(mean=0.9532536139689622, std=0.0, values=array([0.95325361]), LxC_aclus=[90], SxC_aclus=[8], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.008602472489710562, std=0.0, values=array([0.00860247]), LxC_aclus=[90], SxC_aclus=[8], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.14036407876560825, std=0.0, values=array([0.14036408]), LxC_aclus=[90], SxC_aclus=[8], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=1.2886686715766955, std=0.0, values=array([1.28866867]), LxC_aclus=[90], SxC_aclus=[8], LxC_scatter_props=None, SxC_scatter_props=None)]), 1000.0), IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-09_22-24-40')>: (IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-09_22-24-40')>, InstantaneousSpikeRateGroupsComputation(instantaneous_time_bin_size_seconds=1000.0, active_identifying_session_ctx=IdentifyingContext<('kdiba', 'gor01', 'two', '2006-6-09_22-24-40')>, LxC_aclus=[91, 95], SxC_aclus=[], AnyC_aclus=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]), Fig2_Replay_FR=[SingleBarResult(mean=2.602344240449187, std=0.7678089802914473, values=array([1.83453526, 3.37015322]), LxC_aclus=[91, 95], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.500114197113872, std=0.3688010904674576, values=array([0.86891529, 0.13131311]), LxC_aclus=[91, 95], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[91, 95], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[91, 95], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None)], Fig2_Laps_FR=[SingleBarResult(mean=4.363284813303896, std=2.41620763180908, values=array([1.94707718, 6.77949245]), LxC_aclus=[91, 95], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.1498796304896232, std=0.026229347935184028, values=array([0.12365028, 0.17610898]), LxC_aclus=[91, 95], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[91, 95], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[91, 95], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None)]), 1000.0), IdentifyingContext<('kdiba', 'vvp01', 'two', '2006-4-09_16-40-54')>: (IdentifyingContext<('kdiba', 'vvp01', 'two', '2006-4-09_16-40-54')>, InstantaneousSpikeRateGroupsComputation(instantaneous_time_bin_size_seconds=1000.0, active_identifying_session_ctx=IdentifyingContext<('kdiba', 'vvp01', 'two', '2006-4-09_16-40-54')>, LxC_aclus=[12, 14, 17, 25], SxC_aclus=[30], AnyC_aclus=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36]), Fig2_Replay_FR=[SingleBarResult(mean=3.8197662538068817, std=1.942593503697498, values=array([5.50515349, 5.74870909, 1.01219216, 3.01301027]), LxC_aclus=[12, 14, 17, 25], SxC_aclus=[30], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=4.940463104601781, std=6.647988200695198, values=array([ 1.14601695,  1.06349074,  1.09734039, 16.45500434]), LxC_aclus=[12, 14, 17, 25], SxC_aclus=[30], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.4305833333378447, std=0.0, values=array([0.43058333]), LxC_aclus=[12, 14, 17, 25], SxC_aclus=[30], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.6028389940299702, std=0.0, values=array([0.60283899]), LxC_aclus=[12, 14, 17, 25], SxC_aclus=[30], LxC_scatter_props=None, SxC_scatter_props=None)], Fig2_Laps_FR=[SingleBarResult(mean=1.5406326300726807, std=1.1042232413268198, values=array([0.91588085, 1.49650226, 0.41540389, 3.33474352]), LxC_aclus=[12, 14, 17, 25], SxC_aclus=[30], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.08136375960319374, std=0.04410995248089642, values=array([0.12524128, 0.12434943, 0.02704316, 0.04882117]), LxC_aclus=[12, 14, 17, 25], SxC_aclus=[30], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.05888712091347802, std=0.0, values=array([0.05888712]), LxC_aclus=[12, 14, 17, 25], SxC_aclus=[30], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=1.8085263209819697, std=0.0, values=array([1.80852632]), LxC_aclus=[12, 14, 17, 25], SxC_aclus=[30], LxC_scatter_props=None, SxC_scatter_props=None)]), 1000.0), IdentifyingContext<('kdiba', 'vvp01', 'two', '2006-4-10_12-58-3')>: (IdentifyingContext<('kdiba', 'vvp01', 'two', '2006-4-10_12-58-3')>, InstantaneousSpikeRateGroupsComputation(instantaneous_time_bin_size_seconds=1000.0, active_identifying_session_ctx=IdentifyingContext<('kdiba', 'vvp01', 'two', '2006-4-10_12-58-3')>, LxC_aclus=[14, 30, 32], SxC_aclus=[], AnyC_aclus=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]), Fig2_Replay_FR=[SingleBarResult(mean=4.283341333202802, std=1.2812709573328767, values=array([6.08297595, 3.20057774, 3.56647031]), LxC_aclus=[14, 30, 32], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=1.349429573922342, std=0.16065547443561812, values=array([1.12242999, 1.45464295, 1.47121578]), LxC_aclus=[14, 30, 32], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[14, 30, 32], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[14, 30, 32], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None)], Fig2_Laps_FR=[SingleBarResult(mean=1.8187811449664757, std=0.42187806275468304, values=array([1.25142623, 1.9426057 , 2.2623115 ]), LxC_aclus=[14, 30, 32], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=0.008245813474051721, std=0.011661341247802753, values=array([0.02473744, 0.        , 0.        ]), LxC_aclus=[14, 30, 32], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[14, 30, 32], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None), SingleBarResult(mean=None, std=None, values=array([], dtype=float64), LxC_aclus=[14, 30, 32], SxC_aclus=[], LxC_scatter_props=None, SxC_scatter_props=None)]), 1000.0), IdentifyingContext<('kdiba', 'pin01', 'one', '11-03_12-3-25')>: (IdentifyingContext<('kdiba', 'pin01', 'one', '11-03_12-3-25')>, InstantaneousSpikeRateGroupsComputation(instantaneous_time_bin_size_seconds=1000.0, active_identifying_session_ctx=IdentifyingContext<('kdiba', 'pin01', 'one', '11-03_12-3-25')>, LxC_aclus=[8, 24, 25], SxC_aclus=[13, 22, 28], AnyC_aclus=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,

In [95]:
from PendingNotebookCode import build_and_merge_all_sessions_joined_neruon_fri_df

all_sessions_joined_neruon_fri_df, out_path = build_and_merge_all_sessions_joined_neruon_fri_df(global_data_root_parent_path, BATCH_DATE_TO_USE, included_session_contexts=included_session_contexts)

joined_neruon_fri_df: concatenating dataframes from 0

ValueError: No objects to concatenate

In [96]:
from neuropy.core.user_annotations import UserAnnotationsManager, SessionCellExclusivityRecord
from neuropy.utils.result_context import IdentifyingContext

annotation_man = UserAnnotationsManager()

LxC_uids = []
SxC_uids = []

for a_ctxt in included_session_contexts:
	session_uid = a_ctxt.get_description(separator="|", include_property_names=False)
	session_uid
	session_cell_exclusivity: SessionCellExclusivityRecord = annotation_man.annotations[a_ctxt].get('session_cell_exclusivity', None)
	LxC_uids.extend([f"{session_uid}|{aclu}" for aclu in session_cell_exclusivity.LxC])
	SxC_uids.extend([f"{session_uid}|{aclu}" for aclu in session_cell_exclusivity.SxC])
	
# [a_ctxt.get_description(separator="|", include_property_names=False) for a_ctxt in included_session_contexts]

long_short_fr_indicies_analysis_table['XxC_status'] = 'Shared'
long_short_fr_indicies_analysis_table.loc[np.isin(long_short_fr_indicies_analysis_table.neuron_uid, LxC_uids), 'XxC_status'] = 'LxC'
long_short_fr_indicies_analysis_table.loc[np.isin(long_short_fr_indicies_analysis_table.neuron_uid, SxC_uids), 'XxC_status'] = 'SxC'

long_short_fr_indicies_analysis_table
## 2023-10-11 - Get the long peak location

long_short_fr_indicies_analysis_table['long_pf_peak_x'] = neuron_replay_stats_table['long_pf_peak_x']
long_short_fr_indicies_analysis_table

## SAVE:
# long_short_fr_indicies_analysis_table_filename = 'output/2023-10-07_long_short_fr_indicies_analysis_table.csv'
long_short_fr_indicies_analysis_table_filename: str = f'output/{BATCH_DATE_TO_USE}_long_short_fr_indicies_analysis_table.csv'
long_short_fr_indicies_analysis_table.to_csv(long_short_fr_indicies_analysis_table_filename)
print(f'saved: {long_short_fr_indicies_analysis_table_filename}')

'kdiba|gor01|one|2006-6-08_14-26-15'

'kdiba|gor01|one|2006-6-09_1-22-43'

'kdiba|gor01|one|2006-6-12_15-55-31'

'kdiba|gor01|two|2006-6-07_16-40-19'

'kdiba|gor01|two|2006-6-09_22-24-40'

'kdiba|gor01|two|2006-6-12_16-53-46'

'kdiba|vvp01|two|2006-4-09_16-40-54'

'kdiba|vvp01|two|2006-4-10_12-58-3'

'kdiba|pin01|one|11-03_12-3-25'

'kdiba|pin01|one|fet11-01_12-58-54'

,format_name,animal,exper_name,session_name,index,neuron_uid,session_uid,aclu,x_frs_index,y_frs_index,session_datetime,session_experience_rank,session_experience_orientation_rank,is_novel_exposure,point_colors,edgecolors,XxC_status
0,kdiba,gor01,one,2006-6-08_14-26-15,0,kdiba|gor01|one|2006-6-08_14-26-15|2,kdiba|gor01|one|2006-6-08_14-26-15,2,0.955279,1.000000,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,Shared
1,kdiba,gor01,one,2006-6-08_14-26-15,1,kdiba|gor01|one|2006-6-08_14-26-15|3,kdiba|gor01|one|2006-6-08_14-26-15,3,-0.854322,-0.523112,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,Shared
2,kdiba,gor01,one,2006-6-08_14-26-15,2,kdiba|gor01|one|2006-6-08_14-26-15|4,kdiba|gor01|one|2006-6-08_14-26-15,4,-0.991201,-1.000000,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,SxC
3,kdiba,gor01,one,2006-6-08_14-26-15,3,kdiba|gor01|one|2006-6-08_14-26-15|5,kdiba|gor01|one|2006-6-08_14-26-15,5,0.187296,-0.052675,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,Shared
4,kdiba,gor01,one,2006-6-08_14-26-15,4,kdiba|gor01|one|2006-6-08_14-26-15|6,kdiba|gor01|one|2006-6-08_14-26-15,6,0.454566,0.460559,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,Shared
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,kdiba,pin01,one,fet11-01_12-58-54,26,kdiba|pin01|one|fet11-01_12-58-54|28,kdiba|pin01|one|fet11-01_12-58-54,28,-0.670490,-0.268126,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared
464,kdiba,pin01,one,fet11-01_12-58-54,27,kdiba|pin01|one|fet11-01_12-58-54|29,kdiba|pin01|one|fet11-01_12-58-54,29,-0.156788,0.207129,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared
465,kdiba,pin01,one,fet11-01_12-58-54,28,kdiba|pin01|one|fet11-01_12-58-54|30,kdiba|pin01|one|fet11-01_12-58-54,30,-0.246892,-0.030002,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared
466,kdiba,pin01,one,fet11-01_12-58-54,29,kdiba|pin01|one|fet11-01_12-58-54|31,kdiba|pin01|one|fet11-01_12-58-54,31,0.190640,0.147769,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared
467,kdiba,pin01,one,fet11-01_12-58-54,30,kdiba|pin01|one|fet11-01_12-58-54|32,kdiba|pin01|one|fet11-01_12-58-54,32,0.472088,0.366805,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared

,format_name,animal,exper_name,session_name,index,neuron_uid,session_uid,aclu,x_frs_index,y_frs_index,session_datetime,session_experience_rank,session_experience_orientation_rank,is_novel_exposure,point_colors,edgecolors,XxC_status,long_pf_peak_x
0,kdiba,gor01,one,2006-6-08_14-26-15,0,kdiba|gor01|one|2006-6-08_14-26-15|2,kdiba|gor01|one|2006-6-08_14-26-15,2,0.955279,1.000000,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,Shared,NaN
1,kdiba,gor01,one,2006-6-08_14-26-15,1,kdiba|gor01|one|2006-6-08_14-26-15|3,kdiba|gor01|one|2006-6-08_14-26-15,3,-0.854322,-0.523112,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,Shared,NaN
2,kdiba,gor01,one,2006-6-08_14-26-15,2,kdiba|gor01|one|2006-6-08_14-26-15|4,kdiba|gor01|one|2006-6-08_14-26-15,4,-0.991201,-1.000000,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,SxC,NaN
3,kdiba,gor01,one,2006-6-08_14-26-15,3,kdiba|gor01|one|2006-6-08_14-26-15|5,kdiba|gor01|one|2006-6-08_14-26-15,5,0.187296,-0.052675,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,Shared,NaN
4,kdiba,gor01,one,2006-6-08_14-26-15,4,kdiba|gor01|one|2006-6-08_14-26-15|6,kdiba|gor01|one|2006-6-08_14-26-15,6,0.454566,0.460559,2006-06-08 14:26:15,2,1,False,#33333333,#33333300,Shared,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,kdiba,pin01,one,fet11-01_12-58-54,26,kdiba|pin01|one|fet11-01_12-58-54|28,kdiba|pin01|one|fet11-01_12-58-54,28,-0.670490,-0.268126,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared,NaN
464,kdiba,pin01,one,fet11-01_12-58-54,27,kdiba|pin01|one|fet11-01_12-58-54|29,kdiba|pin01|one|fet11-01_12-58-54,29,-0.156788,0.207129,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared,NaN
465,kdiba,pin01,one,fet11-01_12-58-54,28,kdiba|pin01|one|fet11-01_12-58-54|30,kdiba|pin01|one|fet11-01_12-58-54,30,-0.246892,-0.030002,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared,NaN
466,kdiba,pin01,one,fet11-01_12-58-54,29,kdiba|pin01|one|fet11-01_12-58-54|31,kdiba|pin01|one|fet11-01_12-58-54,31,0.190640,0.147769,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared,NaN
467,kdiba,pin01,one,fet11-01_12-58-54,30,kdiba|pin01|one|fet11-01_12-58-54|32,kdiba|pin01|one|fet11-01_12-58-54,32,0.472088,0.366805,2009-11-01 12:58:54,0,0,True,#33333333,#33333300,Shared,NaN

saved: output/2026-09-29_GL_long_short_fr_indicies_analysis_table.csv

# Loading

In [97]:
## Load the saved across-session results:
# inst_fr_output_filename = 'long_short_inst_firing_rate_result_handlers_2023-07-12.pkl'
# inst_fr_output_filename = 'across_session_result_long_short_inst_firing_rate.pkl'
# inst_fr_output_filename='across_session_result_long_short_inst_firing_rate_2023-07-21.pkl'
# inst_fr_output_filename=f'across_session_result_handler_{BATCH_DATE_TO_USE}.pkl'
# inst_fr_output_filename='across_session_result_long_short_inst_firing_rate_2023-08-09_Test.pkl'
# inst_fr_output_filename='across_session_result_long_short_inst_firing_rate_2023-10-04-GL.pkl'
# inst_fr_output_filename='across_session_result_long_short_recomputed_inst_firing_rate_2023-10-04-GL-Recomp.pkl'
# inst_fr_output_filename='across_session_result_long_short_recomputed_inst_firing_rate_2023-10-07.pkl'
# inst_fr_output_filename: str = f'across_session_result_long_short_recomputed_inst_firing_rate_{BATCH_DATE_TO_USE}.pkl'
# inst_fr_output_load_filepath: Path = Path('/nfs/turbo/umms-kdiba/Data/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2024-06-11_GL.pkl').resolve()
# inst_fr_output_load_filepath: Path = collected_outputs_path.joinpath('across_session_result_long_short_recomputed_inst_firing_rate_2024-06-11_GL.pkl').resolve()
# inst_fr_output_load_filepath: Path = collected_outputs_path.joinpath('across_session_result_long_short_recomputed_inst_firing_rate_2024-09-26_GL.pkl').resolve()
inst_fr_output_load_filepath = deepcopy(across_session_result_long_short_recomputed_inst_firing_rate_file)
# "/nfs/turbo/umms-kdiba/Data/Output/collected_outputs/across_session_result_long_short_recomputed_inst_firing_rate_2024-09-26_GL.pkl"
assert inst_fr_output_load_filepath.exists()
inst_fr_output_filename: str = inst_fr_output_load_filepath.name
# across_session_inst_fr_computation, across_sessions_instantaneous_fr_dict, across_sessions_instantaneous_frs_list = AcrossSessionsResults.load_across_sessions_data(global_data_root_parent_path=global_data_root_parent_path, inst_fr_output_filename=inst_fr_output_filename)
across_session_inst_fr_computation, across_sessions_instantaneous_fr_dict, across_sessions_instantaneous_frs_list = AcrossSessionsResults.load_across_sessions_data(global_data_root_parent_path=inst_fr_output_load_filepath.parent, inst_fr_output_filename=inst_fr_output_filename)
# across_sessions_instantaneous_fr_dict = loadData(global_batch_result_inst_fr_file_path)
num_sessions = len(across_sessions_instantaneous_fr_dict)
print(f'num_sessions: {num_sessions}')

NameError: name 'across_session_result_long_short_recomputed_inst_firing_rate_file' is not defined

In [ ]:
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionTables
 
## Load all across-session tables from the pickles:
# output_path_suffix: str = f'{BATCH_DATE_TO_USE}'
# output_path_suffix: str = '2024-09-03_GL'
# output_path_suffix: str = '2025-06-11'
output_path_suffix: str = '2026-09-29'

# neuron_identities_table, long_short_fr_indicies_analysis_table, neuron_replay_stats_table = AcrossSessionTables.load_all_combined_tables(override_output_parent_path=global_data_root_parent_path, output_path_suffix=output_path_suffix) # output_path_suffix=f'2023-10-04-GL-Recomp'
neuron_identities_table, long_short_fr_indicies_analysis_table, neuron_replay_stats_table = AcrossSessionTables.load_all_combined_tables(override_output_parent_path=collected_outputs_path, output_path_suffix=output_path_suffix)
num_sessions = len(neuron_replay_stats_table.session_uid.unique().to_numpy())
print(f'num_sessions: {num_sessions}')

### 2023-11-15 - For manual testing

In [ ]:
# ## Load the saved across-session results:
# Outputs: across_session_inst_fr_computation, across_sessions_instantaneous_fr_dict, across_sessions_instantaneous_frs_list, neuron_identities_table, long_short_fr_indicies_analysis_table, neuron_replay_stats_table

inst_fr_output_filename: str = f'across_session_result_long_short_recomputed_inst_firing_rate_{BATCH_DATE_TO_USE}.pkl'
across_session_inst_fr_computation, across_sessions_instantaneous_fr_dict, across_sessions_instantaneous_frs_list = AcrossSessionsResults.load_across_sessions_data(global_data_root_parent_path=global_data_root_parent_path, inst_fr_output_filename=inst_fr_output_filename)
# across_sessions_instantaneous_fr_dict = loadData(global_batch_result_inst_fr_file_path)
num_sessions = len(across_sessions_instantaneous_fr_dict)
print(f'num_sessions: {num_sessions}')
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionTables

## Load all across-session tables from the pickles:
output_path_suffix: str = f'{BATCH_DATE_TO_USE}'
neuron_identities_table, long_short_fr_indicies_analysis_table, neuron_replay_stats_table = AcrossSessionTables.load_all_combined_tables(override_output_parent_path=global_data_root_parent_path, output_path_suffix=output_path_suffix) # output_path_suffix=f'2023-10-04-GL-Recomp'
num_sessions = len(neuron_replay_stats_table.session_uid.unique().to_numpy())
print(f'num_sessions: {num_sessions}')
# neuron_replay_stats_table

In [ ]:
across_sessions_instantaneous_frs_list

# KDiba Session Discovery - Determines contexts to process - 2024-09-19

In [ ]:
# from pathlib import Path
# from neuropy.core.session.Formats.Specific.KDibaOldDataSessionFormat import KDibaOldDataSessionFormatRegisteredClass
# from neuropy.utils.result_context import print_identifying_context_array_code

# known_global_data_root_parent_paths = [Path(r'/nfs/turbo/umms-kdiba/Data'), Path(r'W:\Data'), Path(r'/home/halechr/cloud/turbo/Data'), Path(r'/media/halechr/MAX/Data'), Path(r'/Volumes/MoverNew/data')] # , Path(r'/home/halechr/FastData'), Path(r'/home/halechr/turbo/Data'), Path(r'W:\Data'), Path(r'/home/halechr/cloud/turbo/Data')
# global_data_root_parent_path = find_first_extant_path(known_global_data_root_parent_paths)
# assert global_data_root_parent_path.exists(), f"global_data_root_parent_path: {global_data_root_parent_path} does not exist! Is the right computer's config commented out above?"
sessions_df, export_folder_path = KDibaOldDataSessionFormatRegisteredClass.find_build_and_save_sessions_experiment_datetime_df_csv(
																			# global_data_root_parent_path=global_data_root_parent_path,
																			export_csv_path=Path('EXTERNAL/PhoDibaPaper2024Book/data/sessions_experiment_datetime_df.csv').resolve(),
																			# bad_sessions_csv_path=Path('EXTERNAL/PhoDibaPaper2024Book/data/2024-09-23_bad_sessions_table.csv').resolve(),
                                                                            bad_sessions_csv_path=Path('EXTERNAL/PhoDibaPaper2024Book/data/2026-09-29_bad_sessions_table.csv').resolve(),
)
sessions_df = sessions_df.reset_index(drop=True, inplace=False)
sessions_df

In [ ]:
# old_included_session_contexts = [
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-08_14-26-15'), 
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-09_1-22-43'), 
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-12_15-55-31'), # 
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-07_16-40-19'), 
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-08_21-16-25'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-09_22-24-40'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-12_16-53-46'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-09_17-29-30'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-10_12-25-50'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-09_16-40-54'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-10_12-58-3'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-02_17-46-44'), #
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-02_19-28-0'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-03_12-3-25'),
#     # IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='fet11-01_12-58-54'), #
# ]
	
# new_included_session_contexts = [
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-09_16-40-54'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-09_17-29-30'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-10_12-25-50'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-10_12-58-3'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-10_19-11-57'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-10_21-2-40'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-11_12-48-38'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-11_15-16-59'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-11_16-2-46'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-12_14-39-31'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-12_14-59-23'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-12_15-25-59'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-12_17-53-55'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-16_14-49-24'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-16_15-12-23'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-16_18-47-52'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-17_12-33-47'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-17_12-52-15'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-18_13-6-1'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-18_13-28-57'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-18_15-23-32'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-18_15-38-2'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-19_13-34-40'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-19_13-50-7'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-19_16-37-40'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-19_16-48-9'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-21_10-24-35'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-21_11-19-2'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-25_13-20-55'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-25_14-28-51'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-25_17-17-6'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-25_17-33-28'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-26_13-22-13'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-26_13-51-50'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-27_14-43-12'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-27_18-21-57'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-28_12-17-27'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-28_12-38-13'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-28_16-48-29'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-28_17-6-14'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-07_11-26-53'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-07_16-40-19'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-08_14-26-15'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-08_15-46-47'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-08_21-16-25'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-09_1-22-43'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-09_3-23-37'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-09_22-24-40'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-12_15-55-31'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-12_16-53-46'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-13_14-42-6'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-13_15-22-3'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='fet11-01_12-58-54'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-02_17-46-44'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-02_19-28-0'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='fet11-03_11-0-53'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-03_12-3-25'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='fet11-03_20-28-3'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-03_21-26-8'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='fet11-04_21-20-3'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-05_19-26-43'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-09_11-43-50'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-09_12-15-3'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-09_21-17-16'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-09_22-4-5'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-19_12-35-59'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-19_13-2-0'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-19_13-55-7'),
# ]

# completely_new_included_session_contexts = [
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-25_14-28-51'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-28_16-48-29'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-18_13-28-57'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-10_19-11-57'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-26_13-22-13'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-09_3-23-37'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-25_17-33-28'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-28_17-6-14'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='fet11-03_11-0-53'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-18_13-6-1'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-09_11-43-50'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-27_18-21-57'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-09_21-17-16'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-19_13-34-40'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-27_14-43-12'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-19_13-50-7'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-25_13-20-55'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-21_10-24-35'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-12_17-53-55'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-09_22-4-5'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-17_12-52-15'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-19_16-37-40'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-11_15-16-59'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-19_16-48-9'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-19_13-2-0'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-16_18-47-52'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-19_13-55-7'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-28_12-38-13'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-12_14-59-23'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-21_11-19-2'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-09_12-15-3'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-10_21-2-40'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-12_14-39-31'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-25_17-17-6'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-08_15-46-47'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-11_16-2-46'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-18_15-38-2'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-13_15-22-3'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-05_19-26-43'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-17_12-33-47'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-12_15-25-59'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-03_21-26-8'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='fet11-01_12-58-54'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-16_14-49-24'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-11_12-48-38'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-28_12-17-27'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-13_14-42-6'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-16_15-12-23'),
#     IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-07_11-26-53'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='two',session_name='2006-4-26_13-51-50'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='fet11-04_21-20-3'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='11-19_12-35-59'),
#     IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-18_15-23-32'),
#     IdentifyingContext(format_name='kdiba',animal='pin01',exper_name='one',session_name='fet11-03_20-28-3'),
# ]

In [ ]:
completely_new_included_session_contexts = set(new_included_session_contexts) - set(old_included_session_contexts)
print_identifying_context_array_code(completely_new_included_session_contexts, array_name='completely_new_included_session_contexts')

# Old File Cleanup

In [ ]:
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import OldFileArchiver

""" 
20240911133516-loadedSessPickle.pkl
20240911131815-loadedSessPickle.pkl
20240911131513-loadedSessPickle.pkl
"""

# deleted_file_list = OldFileArchiver.remove_backup_files_from_session_data_folders(good_session_concrete_folders=all_known_session_concrete_folders, is_dryrun=True)
always_delete_patterns = {
	'.pkltmp': '*.pkltmp',
	'.pkl.bak': '*.pkl.bak',
}
# always_delete_patterns = {} # disable non-conditional deletes while the pipeline is running in batch

# Define patterns to conditionally delete
conditional_delete_patterns = {
	# '.pkl': '*.pkl',
	'pipeline.pkl': '*loadedSessPickle*.pkl',
	'global.pkl': '*global_computation_results*.pkl',
	## Numpy files:
	'position.npy': '*.position.npy',
	'mua.npy': '*.mua.npy',
	'pbe.npy': '*.pbe.npy',
	'non_pbe.npy': '*.non_pbe.npy',
	'interpolated_spike_positions.npy': '*.interpolated_spike_positions.npy',
	'non_pbe.npy': '*.non_pbe.npy',
}

## Numpy files:
numpy_files_patterns = {
	'position.npy': '*.position.npy',
	'mua.npy': '*.mua.npy',
	'pbe.npy': '*.pbe.npy',
	'non_pbe.npy': '*.non_pbe.npy',
	'interpolated_spike_positions.npy': '*.interpolated_spike_positions.npy',
	'non_pbe.npy': '*.non_pbe.npy',
	'ripple.npy': '*.ripple.npy'
}


mat_files_patterns = {
    'epochs_info.mat':'*.epochs_info.mat',
    'laps_info.mat': '*.laps_info.mat',
    'position_info.mat': '*.position_info.mat',
    'spikes.mat': '*.spikes.mat',
}


# always_delete_patterns = always_delete_patterns | numpy_files_patterns

# Define the cutoff date
# conditional_delete_files_cutoff_date = datetime(2023, 9, 1)  # Example cutoff date
# conditional_delete_files_cutoff_date = datetime(2025, 8, 1)
# conditional_delete_files_cutoff_date = datetime(2025, 2, 20)
# conditional_delete_files_cutoff_date = datetime(2025, 3, 20)
conditional_delete_files_cutoff_date = None

# deleted_file_list = OldFileArchiver.remove_backup_files_from_session_data_folders(good_session_concrete_folders=all_known_session_concrete_folders, conditional_delete_files_cutoff_date=conditional_delete_files_cutoff_date, is_dryrun=True)
deleted_file_list = OldFileArchiver.remove_backup_files_from_session_data_folders(good_session_concrete_folders=all_known_session_concrete_folders,
																				  always_delete_patterns=always_delete_patterns,
																				  conditional_delete_patterns=conditional_delete_patterns,
																				   conditional_delete_files_cutoff_date=conditional_delete_files_cutoff_date,
																				   is_dryrun=True,
																				#    is_dryrun=False,
																				   )
deleted_file_list

In [ ]:
# '2025-04-05_0500PM-kdiba_gor01_two_2006-6-12_16-53-46_normal_computed_[1, 2, 4, 6, 7, 8, 9]_5.0-(FAT)_tbin-0.025.csv':'2025-04-05_0500PM-kdiba_gor01_two_2006-6-12_16-53-46_normal_computed_[1, 2, 4, 6, 7, 8, 9]_5.0-(FAT)_tbin-0.025.csv'

# Correctly parsed filename: "2025-03-04_0410AM-kdiba_pin01_one_11-03_12-3-25__withNormalComputedReplays-qclu_[1, 2]-frateThresh_5.0-(ripple_all_scores_merged_df)_tbin-0.025.csv"

rename_parts_dict = {'normal_computed':'_withNormalComputedReplays',
}

In [ ]:
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import OldFileArchiver

## INPUTS: collected_outputs_path, excluded_or_outdated_files_list
archive_folder = OldFileArchiver.archive_old_files(collected_outputs_path=collected_outputs_path, excluded_or_outdated_files_list=excluded_or_outdated_files_list, is_dry_run=True)

archive_folder