# DANDI 001695 HighDensityCrossBrain → NeuroPy pipeline

Loads locally downloaded [DANDI 001695 — High-density Hippocampal-Cortical dynamics](https://dandiarchive.org/dandiset/001695) NWB files from `HighDensityCrossBrain/001695` via registered `DANDI001695NWBDataSessionFormat` / `DataSessionLoader.dandi_nwb_001695_session`, then runs the NeuroPy pipeline (flattened spikes, position QC, sleep-state epochs, placefields, decoding).

**Workflow:**
1. **Initialize session** — load NWB → write export cache under `HighDensityCrossBrain/export/001695/{M01}/{ses-id}/`
2. **POSTLOAD** — activity epochs, laps, PBE/non-PBE
3. **Pipeline** — `NeuropyPipeline` + computations; saves `basedir/loadedSessPickle.pkl`

**Paths:** `sess.basepath` is the subject folder under `001695/`; export cache is under `HighDensityCrossBrain/export/001695/{M01}/{ses-id}/`.

**Install:** `uv sync --all-extras --python 3.10`

**Note:** The ecephys-only NWB (`2024-03-08`) has no position data. Use a `behavior+ecephys` file via `NWB_FILENAME`.

### Session Info
Seems to only have one epoch named 'MAZE3' which is a linear track
I see the animal correctly running laps on the linear track though

In [1]:
%config IPCompleter.use_jedi = False
# %xmode Verbose
# %xmode context
%pdb off
%load_ext autoreload
%autoreload 3

import sys
from pathlib import Path

# required to enable non-blocking interaction:
%gui qt5

import importlib
from copy import deepcopy
from numba import jit
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
# pd.options.mode.dtype_backend = 'pyarrow' # use new pyarrow backend instead of numpy
from attrs import define, field, fields, Factory, make_class
import tables as tb
from datetime import datetime, timedelta

# Pho's Formatting Preferences
import builtins

import IPython
from IPython.core.formatters import PlainTextFormatter
from IPython import get_ipython

from pyphocorehelpers.preferences_helpers import set_pho_preferences, set_pho_preferences_concise, set_pho_preferences_verbose
set_pho_preferences_concise()
# Jupyter-lab enable printing for any line on its own (instead of just the last one in the cell)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
from pyphocorehelpers.gui.Jupyter.AsyncExecutionHelper import run_async

# BEGIN PPRINT CUSTOMIZATION ___________________________________________________________________________________________ #

## IPython pprint
from pyphocorehelpers.pprint import wide_pprint, wide_pprint_ipython, wide_pprint_jupyter, MAX_LINE_LENGTH
# Override default pprint
builtins.pprint = wide_pprint

ip = get_ipython()

from pyphocorehelpers.ipython_helpers import CustomFormatterMagics

# Register the magic
get_ipython().register_magics(CustomFormatterMagics)

text_formatter: PlainTextFormatter = ip.display_formatter.formatters['text/plain']
text_formatter.max_width = MAX_LINE_LENGTH
text_formatter.for_type(object, wide_pprint_jupyter)


# END PPRINT CUSTOMIZATION ___________________________________________________________________________________________ #

from pyphocorehelpers.print_helpers import get_now_time_str, get_now_day_str
from pyphocorehelpers.indexing_helpers import get_dict_subset

## Pho's Custom Libraries:
from pyphocorehelpers.Filesystem.path_helpers import find_first_extant_path, file_uri_from_path
from pyphocorehelpers.Filesystem.open_in_system_file_manager import reveal_in_system_file_manager
import pyphocorehelpers.programming_helpers as programming_helpers

# NeuroPy (Diba Lab Python Repo) Loading
# from neuropy import core
from typing import Dict, List, Tuple, Optional, Callable, Union, Any
from typing_extensions import TypeAlias
from nptyping import NDArray
import neuropy.utils.type_aliases as types

from neuropy.analyses.placefields import PlacefieldComputationParameters
from neuropy.core.epoch import NamedTimerange, Epoch
from neuropy.core.ratemap import Ratemap
from neuropy.core.session.Formats.BaseDataSessionFormats import DataSessionFormatRegistryHolder, DataSessionFormatBaseRegisteredClass
from neuropy.core.session.Formats.BaseDataSessionFormats import HardcodedProcessingParameters
from neuropy.core.session.Formats.Specific.NWBDataSessionFormat import NWBDataSessionFormatRegisteredClass

from neuropy.utils.matplotlib_helpers import matplotlib_file_only, matplotlib_configuration, matplotlib_configuration_update
from neuropy.core.neuron_identities import NeuronIdentityTable, neuronTypesList, neuronTypesEnum
from neuropy.utils.mixins.AttrsClassHelpers import AttrsBasedClassHelperMixin, serialized_field, serialized_attribute_field, non_serialized_field, custom_define
from neuropy.utils.mixins.HDF5_representable import HDF_DeserializationMixin, post_deserialize, HDF_SerializationMixin, HDFMixin, HDF_Converter

## For computation parameters:
from neuropy.analyses.placefields import PlacefieldComputationParameters
from neuropy.utils.dynamic_container import DynamicContainer
from neuropy.utils.result_context import IdentifyingContext
from neuropy.core.session.Formats.BaseDataSessionFormats import find_local_session_paths
from neuropy.core.user_annotations import UserAnnotationsManager

from pyphocorehelpers.print_helpers import print_object_memory_usage, print_dataframe_memory_usage, print_value_overview_only, DocumentationFilePrinter, print_keys_if_possible, generate_html_string, document_active_variables
from pyphocorehelpers.programming_helpers import metadata_attributes
from pyphocorehelpers.function_helpers import function_attributes
## Pho Programming Helpers:
from pyphocorehelpers.print_helpers import DocumentationFilePrinter, TypePrintMode, print_keys_if_possible, debug_dump_object_member_shapes, print_value_overview_only, document_active_variables
from pyphocorehelpers.programming_helpers import IPythonHelpers, PythonDictionaryDefinitionFormat, MemoryManagement, inspect_callable_arguments, get_arguments_as_optional_dict, GeneratedClassDefinitionType, CodeConversion
from pyphocorehelpers.notebook_helpers import NotebookCellExecutionLogger
from pyphocorehelpers.gui.Qt.TopLevelWindowHelper import TopLevelWindowHelper, print_widget_hierarchy
from pyphocorehelpers.indexing_helpers import reorder_columns, reorder_columns_relative, dict_to_full_array
from pyphocorehelpers.DataStructure.RenderPlots.MatplotLibRenderPlots import MatplotlibRenderPlots

# pyPhoPlaceCellAnalysis:
from pyphoplacecellanalysis.General.Pipeline.NeuropyPipeline import NeuropyPipeline # get_neuron_identities
from pyphoplacecellanalysis.General.Mixins.ExportHelpers import export_pyqtgraph_plot
from pyphoplacecellanalysis.General.Batch.NonInteractiveProcessing import batch_load_session, batch_extended_computations, batch_evaluate_required_computations
from pyphoplacecellanalysis.General.Pipeline.NeuropyPipeline import PipelineSavingScheme # used in perform_pipeline_save
from pyphoplacecellanalysis.GUI.IPyWidgets.pipeline_ipywidgets import PipelineJupyterHelpers, CustomProcessingPhases
from pyphocorehelpers.assertion_helpers import Assert

import pyphoplacecellanalysis.External.pyqtgraph as pg

from pyphocorehelpers.exception_helpers import ExceptionPrintingContext, CapturedException
from pyphoplacecellanalysis.General.Batch.NonInteractiveProcessing import batch_perform_all_plots
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.MultiContextComputationFunctions.LongShortTrackComputations import JonathanFiringRateAnalysisResult
from pyphoplacecellanalysis.General.Mixins.CrossComputationComparisonHelpers import _find_any_context_neurons
from pyphoplacecellanalysis.General.Batch.runBatch import BatchSessionCompletionHandler # for `post_compute_validate(...)`
from pyphoplacecellanalysis.Analysis.Decoder.reconstruction import BasePositionDecoder
from pyphoplacecellanalysis.SpecificResults.AcrossSessionResults import AcrossSessionsResults
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.SpikeAnalysis import SpikeRateTrends # for `_perform_long_short_instantaneous_spike_rate_groups_analysis`
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.MultiContextComputationFunctions.LongShortTrackComputations import SingleBarResult, InstantaneousSpikeRateGroupsComputation, TruncationCheckingResults # for `BatchSessionCompletionHandler`, `AcrossSessionsAggregator`
from pyphoplacecellanalysis.General.Mixins.CrossComputationComparisonHelpers import SplitPartitionMembership
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.MultiContextComputationFunctions.DirectionalPlacefieldGlobalComputationFunctions import DirectionalPlacefieldGlobalComputationFunctions, DirectionalLapsResult, TrackTemplates, DecoderDecodedEpochsResult
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.MultiContextComputationFunctions.RankOrderComputations import RankOrderGlobalComputationFunctions,  RankOrderComputationsContainer, RankOrderResult, RankOrderAnalyses
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.MultiContextComputationFunctions.DirectionalPlacefieldGlobalComputationFunctions import TrackTemplates
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.ComputationFunctionRegistryHolder import ComputationFunctionRegistryHolder, computation_precidence_specifying_function, global_function
from pyphocorehelpers.Filesystem.path_helpers import set_posix_windows
from pyphoplacecellanalysis.Analysis.Decoder.reconstruction import BasePositionDecoder, DecodedFilterEpochsResult, SingleEpochDecodedResult

from pyphocorehelpers.assertion_helpers import Assert

# Plotting
# import pylustrator # customization of figures
import matplotlib
import matplotlib as mpl
import matplotlib.pyplot as plt
_bak_rcParams = mpl.rcParams.copy()

matplotlib.use('Qt5Agg')
# %matplotlib inline
# %matplotlib auto

# _restore_previous_matplotlib_settings_callback = matplotlib_configuration_update(is_interactive=True, backend='Qt5Agg')
_restore_previous_matplotlib_settings_callback = matplotlib_configuration_update(is_interactive=True, backend='Qt5Agg')

import seaborn as sns

# import pylustrator # call `pylustrator.start()` before creating your first figure in code.
from pyphoplacecellanalysis.Pho2D.matplotlib.visualize_heatmap import visualize_heatmap, visualize_heatmap_pyqtgraph # used in `plot_kourosh_activity_style_figure`
from pyphoplacecellanalysis.General.Pipeline.Stages.DisplayFunctions.SpikeRasters import plot_multiple_raster_plot, plot_raster_plot
from pyphoplacecellanalysis.General.Mixins.DataSeriesColorHelpers import UnitColoringMode, DataSeriesColorHelpers
from pyphoplacecellanalysis.General.Pipeline.Stages.DisplayFunctions.SpikeRasters import _build_default_tick, build_scatter_plot_kwargs
from pyphoplacecellanalysis.GUI.PyQtPlot.Widgets.Mixins.Render2DScrollWindowPlot import Render2DScrollWindowPlotMixin, ScatterItemData
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.SpikeAnalysis import SpikeRateTrends
from pyphoplacecellanalysis.General.Mixins.SpikesRenderingBaseMixin import SpikeEmphasisState
from pyphoplacecellanalysis.General.Model.SpecificComputationParameterTypes import ComputationKWargParameters
from pyphoplacecellanalysis.SpecificResults.PhoDiba2023Paper import PAPER_FIGURE_figure_1_add_replay_epoch_rasters, PAPER_FIGURE_figure_1_full, PAPER_FIGURE_figure_3, main_complete_figure_generations
# from pyphoplacecellanalysis.SpecificResults.fourthYearPresentation import *

# Jupyter Widget Interactive
import ipywidgets as widgets
from IPython.display import display, HTML
from pyphocorehelpers.Filesystem.open_in_system_file_manager import reveal_in_system_file_manager
from pyphoplacecellanalysis.GUI.IPyWidgets.pipeline_ipywidgets import interactive_pipeline_widget, interactive_pipeline_files
from pyphocorehelpers.gui.Jupyter.simple_widgets import fullwidth_path_widget, render_colors

from datetime import datetime, date, timedelta
from pyphocorehelpers.print_helpers import get_now_day_str, get_now_rounded_time_str


known_data_session_type_properties_dict = DataSessionFormatRegistryHolder.get_registry_known_data_session_type_dict()
active_data_session_types_registered_classes_dict = DataSessionFormatRegistryHolder.get_registry_data_session_type_class_name_dict()

DAY_DATE_STR: str = date.today().strftime("%Y-%m-%d")
DAY_DATE_TO_USE = f'{DAY_DATE_STR}' # used for filenames throught the notebook
print(f'DAY_DATE_STR: {DAY_DATE_STR}, DAY_DATE_TO_USE: {DAY_DATE_TO_USE}')

NOW_DATETIME: str = get_now_rounded_time_str()
NOW_DATETIME_TO_USE = f'{NOW_DATETIME}' # used for filenames throught the notebook
print(f'NOW_DATETIME: {NOW_DATETIME}, NOW_DATETIME_TO_USE: {NOW_DATETIME_TO_USE}')

def get_global_variable(var_name):
    """ used by `PipelineJupyterHelpers._build_pipeline_custom_processing_mode_selector_widget(...)` to update the notebook's variables """
    return globals()[var_name]
    
def update_global_variable(var_name, value):
    """ used by `PipelineJupyterHelpers._build_pipeline_custom_processing_mode_selector_widget(...)` to update the notebook's variables """
    globals()[var_name] = value

from pyphocorehelpers.gui.Jupyter.simple_widgets import build_global_data_root_parent_path_selection_widget
all_paths = [Path(r'H:\Data'), Path(r'I:\Data'), Path(r'/home/halechr/FastData'), Path('/Volumes/SwapSSD/Data'), Path('/Users/pho/data'), Path(r'/media/halechr/MAX/Data'), Path(r'W:\Data'), Path(r'/home/halechr/cloud/turbo/Data'), Path(r'/Volumes/MoverNew/data'), Path(r'/home/halechr/turbo/Data'), Path(r'/Users/pho/cloud/turbo/Data')] # Path('/Volumes/FedoraSSD/FastData'), 
global_data_root_parent_path = None
def on_user_update_path_selection(new_path: Path):
    global global_data_root_parent_path
    new_global_data_root_parent_path = new_path.resolve()
    global_data_root_parent_path = new_global_data_root_parent_path
    print(f'global_data_root_parent_path changed to {global_data_root_parent_path}')
    assert global_data_root_parent_path.exists(), f"global_data_root_parent_path: {global_data_root_parent_path} does not exist! Is the right computer's config commented out above?"
            
global_data_root_parent_path_widget = build_global_data_root_parent_path_selection_widget(all_paths, on_user_update_path_selection)
global_data_root_parent_path_widget

Automatic pdb calling has been turned OFF

H:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\NeuroPy\neuropy\utils\mixins\time_slicing.py:405: UserWarning: registration of accessor <class 'neuropy.utils.mixins.time_slicing.TimePointEventAccessor'> under name 'time_point_event' for type <class 'pandas.core.frame.DataFrame'> is overriding a preexisting attribute with the same name.
  class TimePointEventAccessor(TimeColumnAliasesProtocol, TimeSlicableObjectProtocol, DataframeMetadataProtocol):
h:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\Spike3D\.venv\lib\site-packages\replay_trajectory_classification\likelihoods\multiunit_likelihood.py:9: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm
h:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\Spike3D\.venv\lib\site-packages\hdf5storage\utilities.py:44: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version

field.name: "merged_directional_placefields", variable_name: "merged_directional_placefields"
field.name: "rank_order_shuffle_analysis", variable_name: "rank_order_shuffle_analysis"
field.name: "directional_decoders_decode_continuous", variable_name: "directional_decoders_decode_continuous"
field.name: "directional_decoders_evaluate_epochs", variable_name: "directional_decoders_evaluate_epochs"
field.name: "directional_decoders_epoch_heuristic_scoring", variable_name: "directional_decoders_epoch_heuristic_scoring"
field.name: "directional_train_test_split", variable_name: "directional_train_test_split"
field.name: "long_short_decoding_analyses", variable_name: "long_short_decoding_analyses"
field.name: "long_short_rate_remapping", variable_name: "long_short_rate_remapping"
field.name: "long_short_inst_spike_rate_groups", variable_name: "long_short_inst_spike_rate_groups"
field.name: "wcorr_shuffle_analysis", variable_name: "wcorr_shuffle_analysis"
field.name: "non_pbe_epochs_results", variable_name: "non_pbe_epochs_results"
field.name: "position_decoding", variable_name: "position_decoding"
field.name: "perform_specific_epochs_decoding", variable_name: "perform_specific_epochs_decoding"
field.name: "DEP_ratemap_peaks", variable_name: "DEP_ratemap_peaks"
field.name: "ratemap_peaks_prominence2d", variable_name: "ratemap_peaks_prominence2d"
DAY_DATE_STR: 2026-07-09, DAY_DATE_TO_USE: 2026-07-09
NOW_DATETIME: 2026-07-09_1155AM, NOW_DATETIME_TO_USE: 2026-07-09_1155AM
global_data_root_parent_path changed to H:\Data

ToggleButtons(description='Data Root:', layout=Layout(width='auto'), options=(WindowsPath('H:/Data'), WindowsPath('I:/Data'), WindowsPath('W:/Data')), style=ToggleButtonsStyle(button_width='max-content'), tooltip='global_data_root_parent_path', value=WindowsPath('H:/Data'))

In [2]:
from pynwb import NWBHDF5IO
from neuropy.core.session.data_session_loader import DataSessionLoader
from neuropy.core.session.Formats.BaseDataSessionFormats import DataSessionFormatRegistryHolder
from neuropy.core.session.Formats.Specific.DANDI001695NWBDataSessionFormat import DANDI001695NWBDataSessionFormatRegisteredClass
from pyphoplacecellanalysis.General.Pipeline.NeuropyPipeline import NeuropyPipeline, PipelineSavingScheme
from pyphoplacecellanalysis.SpecificResults.PendingNotebookCode import final_process_bapun_all_comps, build_proper_epoch_intervals

In [3]:
REPO_ROOT = Path(r"H:\Data\DANDI\HighDensityCrossBrain").resolve()
DATA_ROOT = REPO_ROOT / '001695'
EXPORT_ROOT = REPO_ROOT / 'export'
# SUBJECT = 'M01'
# NWB_FILENAME = 'sub-M01_ses-20240312T100000_behavior+ecephys.nwb'
# NWB_FILENAME = 'sub-M01_ses-20240313T100000_behavior+ecephys.nwb'


SUBJECT = 'M02'
NWB_FILENAME = 'sub-M02_ses-20240318T100000_behavior+ecephys.nwb'

SESSION_BASEDIR = DATA_ROOT / f'sub-{SUBJECT}'



UNIT_LOCATION_FILTER = 'CA1'
PLOT_SUBSAMPLE = 25
active_data_mode_name = 'dandi_nwb_001695'
basedir = SESSION_BASEDIR.resolve()
# force_reload = False
force_reload = True
saving_mode = PipelineSavingScheme.TEMP_THEN_OVERWRITE

override_parameters_flat_keypaths_dict = {
    'nwb.nwb_filename': NWB_FILENAME,
    'nwb.unit_location_filter': UNIT_LOCATION_FILTER,
    'nwb.export_root': str(EXPORT_ROOT),
    'preprocessing.epoch_estimation_parameters.laps.use_direction_dependent_laps': False,
}

assert DATA_ROOT.is_dir(), f'Missing data root: {DATA_ROOT}'
assert SESSION_BASEDIR.is_dir(), f'Missing subject dir: {SESSION_BASEDIR}'
print('REPO_ROOT:', REPO_ROOT)
print('DATA_ROOT:', DATA_ROOT)
print('SESSION_BASEDIR:', SESSION_BASEDIR)
print('NWB_FILENAME:', NWB_FILENAME)
print('active_data_mode_name:', active_data_mode_name)
print('export cache root:', EXPORT_ROOT / '001695' / SUBJECT)

REPO_ROOT: H:\Data\DANDI\HighDensityCrossBrain
DATA_ROOT: H:\Data\DANDI\HighDensityCrossBrain\001695
SESSION_BASEDIR: H:\Data\DANDI\HighDensityCrossBrain\001695\sub-M02
NWB_FILENAME: sub-M02_ses-20240318T100000_behavior+ecephys.nwb
active_data_mode_name: dandi_nwb_001695
export cache root: H:\Data\DANDI\HighDensityCrossBrain\export\001695\M02

In [4]:
nwb_files = sorted(SESSION_BASEDIR.glob('*.nwb'))
print(f'Found {len(nwb_files)} NWB files under {SESSION_BASEDIR}')
for p in nwb_files:
    tag = ' (ecephys-only: no position)' if 'behavior' not in p.name else ''
    print(' -', p.name, tag)

nwb_path = DANDI001695NWBDataSessionFormatRegisteredClass.find_nwb_file(SESSION_BASEDIR, nwb_filename=NWB_FILENAME)
print('Selected NWB:', nwb_path)

Found 6 NWB files under H:\Data\DANDI\HighDensityCrossBrain\001695\sub-M02
 - sub-M02_ses-20240226T100000_ecephys.nwb  (ecephys-only: no position)
 - sub-M02_ses-20240307T100000_ecephys.nwb  (ecephys-only: no position)
 - sub-M02_ses-20240312T100000_behavior+ecephys.nwb
 - sub-M02_ses-20240313T100000_behavior+ecephys.nwb
 - sub-M02_ses-20240314T100000_behavior+ecephys.nwb
 - sub-M02_ses-20240318T100000_behavior+ecephys.nwb
Selected NWB: H:\Data\DANDI\HighDensityCrossBrain\001695\sub-M02\sub-M02_ses-20240318T100000_behavior+ecephys.nwb

In [5]:
with NWBHDF5IO(str(nwb_path), mode='r') as io:
    nwbf = io.read()
    print('session_description:', nwbf.session_description)
    if nwbf.intervals and 'SleepStates' in nwbf.intervals:
        ss = nwbf.intervals['SleepStates']
        print('SleepStates:', len(ss), '| cols:', list(ss.colnames))
        display(ss.to_dataframe().head())
    if nwbf.processing and 'behavior' in nwbf.processing and 'AnimalPosition' in nwbf.processing['behavior'].data_interfaces:
        pos_iface = nwbf.processing['behavior']['AnimalPosition']
        pos_series = pos_iface.spatial_series['Position'] if 'Position' in pos_iface.spatial_series else list(pos_iface.spatial_series.values())[0]
        print('position shape:', pos_series.data.shape)
    else:
        print('No behavior position in this NWB file.')
    udf = nwbf.units.to_dataframe()
    print('units:', len(udf), '| cell_area counts:\n', udf['cell_area'].value_counts())

session_description: Novel Maze Session with Pre and Post sleep
SleepStates: 2068 | cols: ['start_time', 'stop_time', 'state']

    start_time  stop_time   state
id
0       1.0000   899.0000    WAKE
1     389.6800   389.7088  Ripple
2     410.9632   410.9984  Ripple
3     452.4240   452.4760  Ripple
4     452.6024   452.6272  Ripple

[5 rows x 3 columns]

position shape: (67722, 2)
units: 150 | cell_area counts:
 CA1    98
RSC    27
CA3    25
Name: cell_area, Length: 3, dtype: int64

## Initialize session from NWB

First load builds NeuroPy export cache (`.npy` under `export/001695/M01/ses-…/`). Re-running uses the cache unless you delete those files or change `NWB_FILENAME`.

In [6]:
sess = DataSessionLoader.dandi_nwb_001695_session(SESSION_BASEDIR, override_parameters_flat_keypaths_dict=override_parameters_flat_keypaths_dict)
print('context:', sess.get_context())
print('neurons:', sess.neurons.n_neurons, '| position samples:', len(sess.position.time))
print('epochs:', sess.epochs.get_unique_labels().tolist())
print('ripples:', len(sess.ripple.to_dataframe()) if sess.ripple is not None else 0)
print('filePrefix:', sess.filePrefix)
for cache_suffix in ['.neurons.npy', '.position.npy', '.paradigm.npy', '.flattened.spikes.npy', '.interpolated_spike_positions.npy']:
    cache_path = sess.filePrefix.with_suffix(cache_suffix)
    print(f'  {cache_path.name}:', 'OK' if cache_path.exists() else 'MISSING', '->', cache_path)
sess

	 Loading success: .interpolated_spike_positions.npy.
externally computed ripple_df.pkl not found. Falling back to .ripple.npy...
Failure loading .ripple.npy. Must recompute.

computing ripple epochs for session...

Computation failed with error 'NoneType' object has no attribute 'get_signal'. Skipping .ripple
Loading success: .mua.npy.
Loading success: .pbe.npy.
Loading success: .non_pbe.npy.
Computing spikes_df PBEs column results : "spikes_df"... encounter KeyError 't_rel_seconds' when attempting to access spk_df using its spk_df.spikes.time_variable_name variable. Original spk_df.spikes.time_variable_name: "t_rel_seconds". Changing it to "t_seconds" and proceeding forward

WARNING: SpikesAccessor.set_time_variable_name(new_time_variable_name: t_seconds) has been called. Be careful!
	 time variable changed from 't_rel_seconds' to 't_seconds'.

	 time variable changed!
done.
Computing added spike scISI column results : "spikes_df"... done.
context: dandi_nwb_001695_M02_001695_ses-20240318T100000
neurons: 98 | position samples: 67722

DataSession(configured from manual recinfo: DynamicContainer({'source_file': None, 'channel_groups': None, 'skipped_channels': None, 'discarded_channels': None, 'n_channels': None, 'dat_sampling_rate': None, 'eeg_sampling_rate': None}))

In [7]:
DANDI001695NWBDataSessionFormatRegisteredClass.POSTLOAD_estimate_laps_and_replays(sess)
print('epochs after POSTLOAD:', sess.epochs.get_unique_labels().tolist())
print('laps:', len(sess.laps.to_dataframe()) if sess.laps is not None else 0)
sess.epochs.to_dataframe().head(10)

POSTLOAD_estimate_laps_and_replays()...
fixing up DANDI 001695 session computation epochs...
	done. new epochs:
2069 epochs
array([[0.9965, 898.996],
       [389.677, 389.705],
       [410.96, 410.995],
       ...,
       [11528.2, 11528.2],
       [11538.6, 11538.6],
       [11541.9, 11542]])


computing PBE epochs for session...

computing estimated replay epochs for session...

	 using KnownFilterEpochs.PBE as surrogate replays...

H:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\NeuroPy\neuropy\core\session\Formats\Specific\DANDI001695NWBDataSessionFormat.py:597: UserWarning: Could not estimate replays for DANDI 001695 session dandi_nwb_001695_M02_001695_ses-20240318T100000: 'DataFrame' object has no attribute 'to_dataframe'
  warnings.warn(f'Could not estimate replays for DANDI 001695 session {sess.get_context()}: {e}')

computing non_PBE epochs for session...

H:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\NeuroPy\neuropy\core\epoch.py:2188: UserWarning: curr_epochs already empty prior to any filtering
  warn(f'curr_epochs already empty prior to any filtering')

Saving non_pbe results results : "H:/Data/DANDI/HighDensityCrossBrain/export/M02/ses-20240318T100000.non_pbe.npy"... ses-20240318T100000.non_pbe.npy saved
done.

DataSession(configured from manual recinfo: DynamicContainer({'source_file': None, 'channel_groups': None, 'skipped_channels': None, 'discarded_channels': None, 'n_channels': None, 'dat_sampling_rate': None, 'eeg_sampling_rate': None}))

epochs after POSTLOAD: ['WAKE0', 'Ripple0', 'Ripple1', 'Ripple2', 'Ripple3', 'Ripple4', 'Ripple5', 'Ripple6', 'Ripple7', 'Ripple8', 'Ripple9', 'Ripple10', 'Ripple11', 'Ripple12', 'Ripple13', 'Ripple14', 'Ripple15', 'Ripple16', 'Ripple17', 'Ripple18', 'Ripple19', 'Ripple20', 'Ripple21', 'Ripple22', 'Ripple23', 'Ripple24', 'Ripple25', 'Ripple26', 'Ripple27', 'Ripple28', 'Ripple29', 'Ripple30', 'Ripple31', 'Ripple32', 'Ripple33', 'Ripple34', 'Ripple35', 'Ripple36', 'NREM0', 'Ripple37', 'Ripple38', 'Ripple39', 'Ripple40', 'Ripple41', 'Ripple42', 'Ripple43', 'Ripple44', 'WAKE1', 'Ripple45', 'Ripple46', 'Ripple47', 'NREM1', 'Ripple48', 'Ripple49', 'Ripple50', 'Ripple51', 'Ripple52', 'Ripple53', 'Ripple54', 'WAKE2', 'Ripple55', 'Ripple56', 'Ripple57', 'Ripple58', 'Ripple59', 'Ripple60', 'Ripple61', 'Ripple62', 'Ripple63', 'Ripple64', 'Ripple65', 'Ripple66', 'Ripple67', 'Ripple68', 'Ripple69', 'NREM2', 'Ripple70', 'Ripple71', 'Ripple72', 'Ripple73', 'Ripple74', 'Ripple75', 'Ripple76', 'Ripple77', 'Ripple78', 'Ripple79', 'Ripple80', 'Ripple81', 'Ripple82', 'Ripple83', 'Ripple84', 'Ripple85', 'Ripple86', 'Ripple87', 'Ripple88', 'Ripple89', 'Ripple90', 'Ripple91', 'Ripple92', 'Ripple93', 'Ripple94', 'Ripple95', 'Ripple96', 'Ripple97', 'Ripple98', 'Ripple99', 'Ripple100', 'Ripple101', 'Ripple102', 'Ripple103', 'Ripple104', 'Ripple105', 'Ripple106', 'Ripple107', 'Ripple108', 'Ripple109', 'Ripple110', 'Ripple111', 'Ripple112', 'Ripple113', 'Ripple114', 'Ripple115', 'Ripple116', 'Ripple117', 'Ripple118', 'Ripple119', 'Ripple120', 'Ripple121', 'Ripple122', 'Ripple123', 'Ripple124', 'Ripple125', 'Ripple126', 'Ripple127', 'Ripple128', 'Ripple129', 'Ripple130', 'Ripple131', 'Ripple132', 'Ripple133', 'Ripple134', 'Ripple135', 'Ripple136', 'Ripple137', 'Ripple138', 'Ripple139', 'Ripple140', 'Ripple141', 'Ripple142', 'Ripple143', 'Ripple144', 'Ripple145', 'Ripple146', 'Ripple147', 'Ripple148', 'Ripple149', 'Ripple150', 'Ripple151', 'Ripple152', 'Ripple153', 'Ripple154', 'Ripple155', 'Ripple156', 'Ripple157', 'Ripple158', 'Ripple159', 'Ripple160', 'Ripple161', 'Ripple162', 'Ripple163', 'Ripple164', 'Ripple165', 'Ripple166', 'Ripple167', 'Ripple168', 'Ripple169', 'WAKE3', 'Ripple170', 'Ripple171', 'Ripple172', 'Ripple173', 'NREM3', 'Ripple174', 'Ripple175', 'Ripple176', 'Ripple177', 'Ripple178', 'Ripple179', 'Ripple180', 'Ripple181', 'Ripple182', 'Ripple183', 'Ripple184', 'Ripple185', 'Ripple186', 'WAKE4', 'Ripple187', 'NREM4', 'Ripple188', 'Ripple189', 'Ripple190', 'Ripple191', 'Ripple192', 'Ripple193', 'Ripple194', 'Ripple195', 'Ripple196', 'Ripple197', 'Ripple198', 'Ripple199', 'Ripple200', 'Ripple201', 'Ripple202', 'Ripple203', 'Ripple204', 'Ripple205', 'Ripple206', 'Ripple207', 'Ripple208', 'Ripple209', 'Ripple210', 'Ripple211', 'Ripple212', 'Ripple213', 'Ripple214', 'Ripple215', 'Ripple216', 'Ripple217', 'Ripple218', 'Ripple219', 'Ripple220', 'Ripple221', 'Ripple222', 'Ripple223', 'Ripple224', 'Ripple225', 'Ripple226', 'Ripple227', 'Ripple228', 'Ripple229', 'Ripple230', 'Ripple231', 'Ripple232', 'Ripple233', 'Ripple234', 'Ripple235', 'Ripple236', 'Ripple237', 'Ripple238', 'Ripple239', 'Ripple240', 'Ripple241', 'Ripple242', 'Ripple243', 'Ripple244', 'Ripple245', 'Ripple246', 'Ripple247', 'Ripple248', 'Ripple249', 'Ripple250', 'Ripple251', 'Ripple252', 'Ripple253', 'Ripple254', 'Ripple255', 'Ripple256', 'Ripple257', 'Ripple258', 'Ripple259', 'Ripple260', 'Ripple261', 'Ripple262', 'Ripple263', 'Ripple264', 'Ripple265', 'Ripple266', 'Ripple267', 'Ripple268', 'Ripple269', 'Ripple270', 'Ripple271', 'Ripple272', 'Ripple273', 'Ripple274', 'Ripple275', 'Ripple276', 'Ripple277', 'Ripple278', 'Ripple279', 'Ripple280', 'Ripple281', 'Ripple282', 'Ripple283', 'Ripple284', 'Ripple285', 'Ripple286', 'Ripple287', 'Ripple288', 'Ripple289', 'Ripple290', 'Ripple291', 'Ripple292', 'Ripple293', 'Ripple294', 'Ripple295', 'Ripple296', 'Ripple297', 'Ripple298', 'Ripple299', 'Ripple300', 'Ripple301', 'Ripple302', 'Ripple303', 'Ripple304', 'Ripple305', 'Ripple306', 'Ripple307', 'Ripple308', 'Ripple309', 'Ripple310', 'Ripple311', 'Ripple312', 'Ripple313', 'Ripple314', 'Ripple315', 'Ripple316', 'Ripple317', 'Ripple318', 'Ripple319', 'Ripple320', 'Ripple321', 'Ripple322', 'Ripple323', 'Ripple324', 'Ripple325', 'Ripple326', 'Ripple327', 'WAKE5', 'NREM5', 'Ripple328', 'Ripple329', 'Ripple330', 'Ripple331', 'Ripple332', 'Ripple333', 'Ripple334', 'Ripple335', 'Ripple336', 'Ripple337', 'Ripple338', 'Ripple339', 'Ripple340', 'Ripple341', 'Ripple342', 'Ripple343', 'Ripple344', 'Ripple345', 'Ripple346', 'Ripple347', 'Ripple348', 'Ripple349', 'Ripple350', 'Ripple351', 'Ripple352', 'Ripple353', 'Ripple354', 'Ripple355', 'Ripple356', 'Ripple357', 'Ripple358', 'Ripple359', 'Ripple360', 'Ripple361', 'Ripple362', 'Ripple363', 'Ripple364', 'Ripple365', 'Ripple366', 'Ripple367', 'Ripple368', 'Ripple369', 'Ripple370', 'Ripple371', 'Ripple372', 'Ripple373', 'Ripple374', 'Ripple375', 'Ripple376', 'Ripple377', 'Ripple378', 'Ripple379', 'Ripple380', 'WAKE6', 'Ripple381', 'Ripple382', 'Ripple383', 'Ripple384', 'NREM6', 'Ripple385', 'Ripple386', 'Ripple387', 'Ripple388', 'Ripple389', 'Ripple390', 'Ripple391', 'WAKE7', 'Ripple392', 'NREM7', 'Ripple393', 'Ripple394', 'Ripple395', 'Ripple396', 'Ripple397', 'Ripple398', 'Ripple399', 'Ripple400', 'Ripple401', 'Ripple402', 'Ripple403', 'Ripple404', 'Ripple405', 'Ripple406', 'Ripple407', 'Ripple408', 'Ripple409', 'Ripple410', 'Ripple411', 'Ripple412', 'Ripple413', 'Ripple414', 'Ripple415', 'Ripple416', 'Ripple417', 'Ripple418', 'Ripple419', 'Ripple420', 'Ripple421', 'Ripple422', 'Ripple423', 'Ripple424', 'Ripple425', 'Ripple426', 'Ripple427', 'Ripple428', 'Ripple429', 'Ripple430', 'Ripple431', 'Ripple432', 'Ripple433', 'Ripple434', 'Ripple435', 'Ripple436', 'Ripple437', 'Ripple438', 'Ripple439', 'Ripple440', 'Ripple441', 'Ripple442', 'Ripple443', 'Ripple444', 'Ripple445', 'Ripple446', 'Ripple447', 'Ripple448', 'Ripple449', 'Ripple450', 'Ripple451', 'Ripple452', 'Ripple453', 'Ripple454', 'Ripple455', 'Ripple456', 'Ripple457', 'Ripple458', 'Ripple459', 'Ripple460', 'Ripple461', 'Ripple462', 'Ripple463', 'Ripple464', 'Ripple465', 'Ripple466', 'Ripple467', 'Ripple468', 'Ripple469', 'Ripple470', 'Ripple471', 'Ripple472', 'Ripple473', 'Ripple474', 'Ripple475', 'Ripple476', 'Ripple477', 'Ripple478', 'Ripple479', 'Ripple480', 'Ripple481', 'Ripple482', 'Ripple483', 'Ripple484', 'Ripple485', 'Ripple486', 'REM0', 'WAKE8', 'NREM8', 'Ripple487', 'Ripple488', 'Ripple489', 'Ripple490', 'Ripple491', 'Ripple492', 'Ripple493', 'Ripple494', 'Ripple495', 'Ripple496', 'Ripple497', 'Ripple498', 'Ripple499', 'Ripple500', 'Ripple501', 'Ripple502', 'Ripple503', 'Ripple504', 'Ripple505', 'Ripple506', 'Ripple507', 'Ripple508', 'Ripple509', 'Ripple510', 'Ripple511', 'Ripple512', 'Ripple513', 'Ripple514', 'Ripple515', 'Ripple516', 'Ripple517', 'Ripple518', 'Ripple519', 'Ripple520', 'Ripple521', 'Ripple522', 'Ripple523', 'Ripple524', 'Ripple525', 'Ripple526', 'Ripple527', 'Ripple528', 'Ripple529', 'Ripple530', 'Ripple531', 'Ripple532', 'Ripple533', 'Ripple534', 'Ripple535', 'Ripple536', 'Ripple537', 'Ripple538', 'Ripple539', 'Ripple540', 'Ripple541', 'Ripple542', 'Ripple543', 'Ripple544', 'Ripple545', 'Ripple546', 'Ripple547', 'Ripple548', 'Ripple549', 'Ripple550', 'Ripple551', 'Ripple552', 'WAKE9', 'Ripple553', 'Ripple554', 'Ripple555', 'Ripple556', 'Ripple557', 'Ripple558', 'Ripple559', 'Ripple560', 'Ripple561', 'Ripple562', 'Ripple563', 'Ripple564', 'Ripple565', 'Ripple566', 'Ripple567', 'Ripple568', 'Ripple569', 'NREM9', 'Ripple570', 'Ripple571', 'Ripple572', 'Ripple573', 'Ripple574', 'Ripple575', 'Ripple576', 'Ripple577', 'Ripple578', 'Ripple579', 'Ripple580', 'Ripple581', 'Ripple582', 'Ripple583', 'Ripple584', 'Ripple585', 'Ripple586', 'Ripple587', 'Ripple588', 'Ripple589', 'Ripple590', 'Ripple591', 'Ripple592', 'Ripple593', 'Ripple594', 'Ripple595', 'Ripple596', 'Ripple597', 'Ripple598', 'Ripple599', 'Ripple600', 'Ripple601', 'Ripple602', 'Ripple603', 'Ripple604', 'Ripple605', 'Ripple606', 'Ripple607', 'Ripple608', 'Ripple609', 'Ripple610', 'Ripple611', 'Ripple612', 'Ripple613', 'Ripple614', 'Ripple615', 'Ripple616', 'Ripple617', 'Ripple618', 'Ripple619', 'Ripple620', 'Ripple621', 'Ripple622', 'Ripple623', 'Ripple624', 'Ripple625', 'Ripple626', 'Ripple627', 'Ripple628', 'Ripple629', 'Ripple630', 'Ripple631', 'Ripple632', 'Ripple633', 'Ripple634', 'Ripple635', 'Ripple636', 'Ripple637', 'Ripple638', 'Ripple639', 'Ripple640', 'Ripple641', 'Ripple642', 'Ripple643', 'Ripple644', 'Ripple645', 'Ripple646', 'Ripple647', 'Ripple648', 'Ripple649', 'Ripple650', 'Ripple651', 'Ripple652', 'Ripple653', 'Ripple654', 'Ripple655', 'Ripple656', 'Ripple657', 'Ripple658', 'Ripple659', 'Ripple660', 'Ripple661', 'Ripple662', 'Ripple663', 'Ripple664', 'Ripple665', 'Ripple666', 'Ripple667', 'Ripple668', 'Ripple669', 'Ripple670', 'Ripple671', 'Ripple672', 'Ripple673', 'Ripple674', 'Ripple675', 'Ripple676', 'Ripple677', 'Ripple678', 'Ripple679', 'Ripple680', 'Ripple681', 'Ripple682', 'Ripple683', 'Ripple684', 'Ripple685', 'Ripple686', 'Ripple687', 'Ripple688', 'Ripple689', 'Ripple690', 'Ripple691', 'Ripple692', 'Ripple693', 'Ripple694', 'Ripple695', 'Ripple696', 'Ripple697', 'Ripple698', 'Ripple699', 'Ripple700', 'Ripple701', 'Ripple702', 'Ripple703', 'Ripple704', 'Ripple705', 'Ripple706', 'Ripple707', 'Ripple708', 'Ripple709', 'Ripple710', 'Ripple711', 'Ripple712', 'Ripple713', 'Ripple714', 'Ripple715', 'Ripple716', 'Ripple717', 'Ripple718', 'Ripple719', 'Ripple720', 'Ripple721', 'Ripple722', 'Ripple723', 'Ripple724', 'Ripple725', 'Ripple726', 'Ripple727', 'Ripple728', 'Ripple729', 'Ripple730', 'Ripple731', 'Ripple732', 'Ripple733', 'Ripple734', 'Ripple735', 'Ripple736', 'Ripple737', 'Ripple738', 'Ripple739', 'Ripple740', 'Ripple741', 'Ripple742', 'Ripple743', 'Ripple744', 'Ripple745', 'Ripple746', 'Ripple747', 'Ripple748', 'Ripple749', 'Ripple750', 'Ripple751', 'Ripple752', 'Ripple753', 'Ripple754', 'Ripple755', 'Ripple756', 'Ripple757', 'Ripple758', 'Ripple759', 'Ripple760', 'Ripple761', 'Ripple762', 'Ripple763', 'Ripple764', 'Ripple765', 'Ripple766', 'Ripple767', 'Ripple768', 'Ripple769', 'Ripple770', 'Ripple771', 'Ripple772', 'Ripple773', 'Ripple774', 'Ripple775', 'Ripple776', 'Ripple777', 'Ripple778', 'Ripple779', 'Ripple780', 'Ripple781', 'Ripple782', 'Ripple783', 'Ripple784', 'WAKE10', 'Ripple785', 'Ripple786', 'Ripple787', 'NREM10', 'Ripple788', 'Ripple789', 'Ripple790', 'Ripple791', 'Ripple792', 'Ripple793', 'Ripple794', 'Ripple795', 'Ripple796', 'Ripple797', 'Ripple798', 'Ripple799', 'Ripple800', 'Ripple801', 'Ripple802', 'Ripple803', 'Ripple804', 'Ripple805', 'Ripple806', 'Ripple807', 'Ripple808', 'Ripple809', 'Ripple810', 'Ripple811', 'Ripple812', 'Ripple813', 'Ripple814', 'Ripple815', 'Ripple816', 'Ripple817', 'Ripple818', 'Ripple819', 'Ripple820', 'Ripple821', 'Ripple822', 'Ripple823', 'Ripple824', 'Ripple825', 'Ripple826', 'Ripple827', 'Ripple828', 'Ripple829', 'Ripple830', 'Ripple831', 'Ripple832', 'Ripple833', 'Ripple834', 'Ripple835', 'Ripple836', 'Ripple837', 'Ripple838', 'Ripple839', 'Ripple840', 'Ripple841', 'Ripple842', 'Ripple843', 'Ripple844', 'Ripple845', 'Ripple846', 'Ripple847', 'Ripple848', 'Ripple849', 'Ripple850', 'Ripple851', 'Ripple852', 'Ripple853', 'Ripple854', 'Ripple855', 'Ripple856', 'Ripple857', 'Ripple858', 'Ripple859', 'Ripple860', 'Ripple861', 'Ripple862', 'Ripple863', 'Ripple864', 'Ripple865', 'Ripple866', 'Ripple867', 'Ripple868', 'Ripple869', 'Ripple870', 'Ripple871', 'Ripple872', 'Ripple873', 'Ripple874', 'REM1', 'activity_GLOBAL', 'WAKE11', 'Ripple875', 'Ripple876', 'Ripple877', 'Ripple878', 'Ripple879', 'Ripple880', 'Ripple881', 'Ripple882', 'Ripple883', 'Ripple884', 'Ripple885', 'Ripple886', 'Ripple887', 'Ripple888', 'Ripple889', 'Ripple890', 'Ripple891', 'Ripple892', 'Ripple893', 'Ripple894', 'Ripple895', 'Ripple896', 'Ripple897', 'Ripple898', 'Ripple899', 'Ripple900', 'Ripple901', 'Ripple902', 'Ripple903', 'Ripple904', 'Ripple905', 'Ripple906', 'Ripple907', 'Ripple908', 'Ripple909', 'Ripple910', 'Ripple911', 'Ripple912', 'Ripple913', 'Ripple914', 'Ripple915', 'Ripple916', 'Ripple917', 'Ripple918', 'Ripple919', 'Ripple920', 'Ripple921', 'Ripple922', 'Ripple923', 'Ripple924', 'Ripple925', 'Ripple926', 'Ripple927', 'Ripple928', 'Ripple929', 'Ripple930', 'Ripple931', 'Ripple932', 'Ripple933', 'Ripple934', 'Ripple935', 'Ripple936', 'Ripple937', 'Ripple938', 'Ripple939', 'Ripple940', 'Ripple941', 'Ripple942', 'Ripple943', 'Ripple944', 'Ripple945', 'Ripple946', 'Ripple947', 'Ripple948', 'Ripple949', 'Ripple950', 'Ripple951', 'Ripple952', 'Ripple953', 'Ripple954', 'NREM11', 'Ripple955', 'Ripple956', 'Ripple957', 'Ripple958', 'Ripple959', 'Ripple960', 'Ripple961', 'Ripple962', 'Ripple963', 'Ripple964', 'Ripple965', 'Ripple966', 'Ripple967', 'Ripple968', 'Ripple969', 'Ripple970', 'Ripple971', 'Ripple972', 'Ripple973', 'Ripple974', 'Ripple975', 'Ripple976', 'Ripple977', 'Ripple978', 'Ripple979', 'Ripple980', 'Ripple981', 'WAKE12', 'Ripple982', 'Ripple983', 'Ripple984', 'Ripple985', 'Ripple986', 'Ripple987', 'Ripple988', 'Ripple989', 'Ripple990', 'Ripple991', 'Ripple992', 'Ripple993', 'Ripple994', 'Ripple995', 'Ripple996', 'Ripple997', 'Ripple998', 'Ripple999', 'Ripple1000', 'Ripple1001', 'Ripple1002', 'NREM12', 'Ripple1003', 'Ripple1004', 'Ripple1005', 'Ripple1006', 'Ripple1007', 'Ripple1008', 'Ripple1009', 'Ripple1010', 'Ripple1011', 'Ripple1012', 'Ripple1013', 'Ripple1014', 'Ripple1015', 'Ripple1016', 'Ripple1017', 'Ripple1018', 'Ripple1019', 'Ripple1020', 'Ripple1021', 'Ripple1022', 'Ripple1023', 'Ripple1024', 'Ripple1025', 'Ripple1026', 'Ripple1027', 'Ripple1028', 'Ripple1029', 'Ripple1030', 'Ripple1031', 'Ripple1032', 'Ripple1033', 'Ripple1034', 'Ripple1035', 'Ripple1036', 'Ripple1037', 'Ripple1038', 'Ripple1039', 'Ripple1040', 'Ripple1041', 'Ripple1042', 'Ripple1043', 'Ripple1044', 'Ripple1045', 'Ripple1046', 'Ripple1047', 'Ripple1048', 'Ripple1049', 'Ripple1050', 'Ripple1051', 'Ripple1052', 'Ripple1053', 'Ripple1054', 'Ripple1055', 'Ripple1056', 'Ripple1057', 'Ripple1058', 'Ripple1059', 'Ripple1060', 'Ripple1061', 'Ripple1062', 'Ripple1063', 'Ripple1064', 'Ripple1065', 'Ripple1066', 'Ripple1067', 'Ripple1068', 'Ripple1069', 'Ripple1070', 'Ripple1071', 'Ripple1072', 'Ripple1073', 'Ripple1074', 'Ripple1075', 'Ripple1076', 'Ripple1077', 'Ripple1078', 'Ripple1079', 'Ripple1080', 'Ripple1081', 'Ripple1082', 'Ripple1083', 'Ripple1084', 'Ripple1085', 'Ripple1086', 'Ripple1087', 'Ripple1088', 'Ripple1089', 'Ripple1090', 'Ripple1091', 'Ripple1092', 'Ripple1093', 'Ripple1094', 'Ripple1095', 'Ripple1096', 'Ripple1097', 'Ripple1098', 'Ripple1099', 'Ripple1100', 'Ripple1101', 'Ripple1102', 'Ripple1103', 'Ripple1104', 'Ripple1105', 'Ripple1106', 'Ripple1107', 'Ripple1108', 'Ripple1109', 'Ripple1110', 'Ripple1111', 'Ripple1112', 'Ripple1113', 'Ripple1114', 'Ripple1115', 'Ripple1116', 'Ripple1117', 'Ripple1118', 'Ripple1119', 'Ripple1120', 'Ripple1121', 'Ripple1122', 'Ripple1123', 'Ripple1124', 'Ripple1125', 'Ripple1126', 'Ripple1127', 'Ripple1128', 'Ripple1129', 'Ripple1130', 'Ripple1131', 'Ripple1132', 'Ripple1133', 'Ripple1134', 'Ripple1135', 'Ripple1136', 'Ripple1137', 'Ripple1138', 'Ripple1139', 'Ripple1140', 'Ripple1141', 'Ripple1142', 'Ripple1143', 'Ripple1144', 'Ripple1145', 'Ripple1146', 'Ripple1147', 'Ripple1148', 'Ripple1149', 'Ripple1150', 'Ripple1151', 'Ripple1152', 'Ripple1153', 'Ripple1154', 'Ripple1155', 'Ripple1156', 'Ripple1157', 'Ripple1158', 'Ripple1159', 'Ripple1160', 'Ripple1161', 'Ripple1162', 'Ripple1163', 'Ripple1164', 'Ripple1165', 'Ripple1166', 'Ripple1167', 'Ripple1168', 'Ripple1169', 'Ripple1170', 'Ripple1171', 'Ripple1172', 'Ripple1173', 'Ripple1174', 'Ripple1175', 'Ripple1176', 'Ripple1177', 'Ripple1178', 'Ripple1179', 'Ripple1180', 'Ripple1181', 'Ripple1182', 'Ripple1183', 'Ripple1184', 'Ripple1185', 'Ripple1186', 'Ripple1187', 'Ripple1188', 'Ripple1189', 'Ripple1190', 'Ripple1191', 'Ripple1192', 'Ripple1193', 'Ripple1194', 'Ripple1195', 'Ripple1196', 'Ripple1197', 'Ripple1198', 'Ripple1199', 'Ripple1200', 'Ripple1201', 'Ripple1202', 'Ripple1203', 'Ripple1204', 'Ripple1205', 'Ripple1206', 'Ripple1207', 'Ripple1208', 'Ripple1209', 'Ripple1210', 'Ripple1211', 'Ripple1212', 'Ripple1213', 'Ripple1214', 'Ripple1215', 'Ripple1216', 'Ripple1217', 'Ripple1218', 'Ripple1219', 'Ripple1220', 'Ripple1221', 'Ripple1222', 'Ripple1223', 'Ripple1224', 'Ripple1225', 'Ripple1226', 'Ripple1227', 'Ripple1228', 'Ripple1229', 'Ripple1230', 'Ripple1231', 'Ripple1232', 'Ripple1233', 'Ripple1234', 'Ripple1235', 'Ripple1236', 'Ripple1237', 'Ripple1238', 'Ripple1239', 'Ripple1240', 'Ripple1241', 'Ripple1242', 'Ripple1243', 'Ripple1244', 'Ripple1245', 'Ripple1246', 'Ripple1247', 'Ripple1248', 'Ripple1249', 'Ripple1250', 'Ripple1251', 'Ripple1252', 'Ripple1253', 'Ripple1254', 'Ripple1255', 'Ripple1256', 'Ripple1257', 'Ripple1258', 'Ripple1259', 'Ripple1260', 'Ripple1261', 'Ripple1262', 'Ripple1263', 'Ripple1264', 'Ripple1265', 'Ripple1266', 'Ripple1267', 'Ripple1268', 'Ripple1269', 'Ripple1270', 'Ripple1271', 'Ripple1272', 'Ripple1273', 'Ripple1274', 'Ripple1275', 'Ripple1276', 'Ripple1277', 'Ripple1278', 'Ripple1279', 'Ripple1280', 'Ripple1281', 'Ripple1282', 'Ripple1283', 'Ripple1284', 'Ripple1285', 'Ripple1286', 'Ripple1287', 'Ripple1288', 'Ripple1289', 'Ripple1290', 'Ripple1291', 'Ripple1292', 'Ripple1293', 'Ripple1294', 'Ripple1295', 'Ripple1296', 'Ripple1297', 'Ripple1298', 'Ripple1299', 'Ripple1300', 'Ripple1301', 'Ripple1302', 'Ripple1303', 'Ripple1304', 'Ripple1305', 'Ripple1306', 'Ripple1307', 'Ripple1308', 'Ripple1309', 'Ripple1310', 'Ripple1311', 'Ripple1312', 'Ripple1313', 'Ripple1314', 'Ripple1315', 'Ripple1316', 'Ripple1317', 'Ripple1318', 'Ripple1319', 'Ripple1320', 'Ripple1321', 'Ripple1322', 'Ripple1323', 'Ripple1324', 'Ripple1325', 'Ripple1326', 'Ripple1327', 'Ripple1328', 'Ripple1329', 'Ripple1330', 'Ripple1331', 'Ripple1332', 'Ripple1333', 'Ripple1334', 'Ripple1335', 'Ripple1336', 'Ripple1337', 'Ripple1338', 'Ripple1339', 'Ripple1340', 'Ripple1341', 'Ripple1342', 'Ripple1343', 'Ripple1344', 'Ripple1345', 'Ripple1346', 'Ripple1347', 'Ripple1348', 'Ripple1349', 'Ripple1350', 'Ripple1351', 'Ripple1352', 'Ripple1353', 'Ripple1354', 'Ripple1355', 'Ripple1356', 'Ripple1357', 'Ripple1358', 'Ripple1359', 'Ripple1360', 'Ripple1361', 'Ripple1362', 'Ripple1363', 'Ripple1364', 'Ripple1365', 'Ripple1366', 'Ripple1367', 'Ripple1368', 'Ripple1369', 'Ripple1370', 'Ripple1371', 'Ripple1372', 'Ripple1373', 'Ripple1374', 'Ripple1375', 'Ripple1376', 'Ripple1377', 'Ripple1378', 'Ripple1379', 'Ripple1380', 'Ripple1381', 'Ripple1382', 'Ripple1383', 'Ripple1384', 'Ripple1385', 'Ripple1386', 'Ripple1387', 'Ripple1388', 'Ripple1389', 'Ripple1390', 'Ripple1391', 'Ripple1392', 'Ripple1393', 'Ripple1394', 'Ripple1395', 'Ripple1396', 'Ripple1397', 'Ripple1398', 'Ripple1399', 'Ripple1400', 'Ripple1401', 'Ripple1402', 'Ripple1403', 'Ripple1404', 'Ripple1405', 'Ripple1406', 'Ripple1407', 'Ripple1408', 'Ripple1409', 'Ripple1410', 'Ripple1411', 'Ripple1412', 'Ripple1413', 'Ripple1414', 'Ripple1415', 'Ripple1416', 'Ripple1417', 'Ripple1418', 'Ripple1419', 'Ripple1420', 'Ripple1421', 'Ripple1422', 'Ripple1423', 'Ripple1424', 'Ripple1425', 'Ripple1426', 'Ripple1427', 'Ripple1428', 'Ripple1429', 'Ripple1430', 'Ripple1431', 'Ripple1432', 'Ripple1433', 'Ripple1434', 'Ripple1435', 'Ripple1436', 'Ripple1437', 'Ripple1438', 'Ripple1439', 'Ripple1440', 'Ripple1441', 'Ripple1442', 'Ripple1443', 'Ripple1444', 'Ripple1445', 'Ripple1446', 'Ripple1447', 'Ripple1448', 'Ripple1449', 'Ripple1450', 'Ripple1451', 'Ripple1452', 'Ripple1453', 'Ripple1454', 'Ripple1455', 'Ripple1456', 'Ripple1457', 'Ripple1458', 'Ripple1459', 'Ripple1460', 'Ripple1461', 'Ripple1462', 'Ripple1463', 'Ripple1464', 'Ripple1465', 'REM2', 'WAKE13', 'NREM13', 'Ripple1466', 'Ripple1467', 'Ripple1468', 'Ripple1469', 'Ripple1470', 'Ripple1471', 'Ripple1472', 'Ripple1473', 'Ripple1474', 'Ripple1475', 'Ripple1476', 'Ripple1477', 'Ripple1478', 'Ripple1479', 'Ripple1480', 'Ripple1481', 'Ripple1482', 'Ripple1483', 'Ripple

      start      stop    label  duration
0    0.9965  898.9965    WAKE0  898.0000
1  389.6765  389.7053  Ripple0    0.0288
2  410.9597  410.9949  Ripple1    0.0352
3  452.4205  452.4725  Ripple2    0.0520
4  452.5989  452.6237  Ripple3    0.0248
5  452.8605  452.8933  Ripple4    0.0328
6  453.7525  453.7885  Ripple5    0.0360
7  458.0829  458.1061  Ripple6    0.0232
8  464.1189  464.1453  Ripple7    0.0264
9  464.5317  464.5645  Ripple8    0.0328

[10 rows x 4 columns]

## Load NeuroPy pipeline

Wraps the initialized session for downstream computations. Saves `basedir/loadedSessPickle.pkl` after a successful fresh load.

In [8]:
# known_data_session_type_properties_dict = DataSessionFormatRegistryHolder.get_registry_known_data_session_type_dict()
known_data_session_type_properties_dict = DataSessionFormatRegistryHolder.get_registry_known_data_session_type_dict(
    override_parameters_flat_keypaths_dict=override_parameters_flat_keypaths_dict
)
active_data_session_types_registered_classes_dict = DataSessionFormatRegistryHolder.get_registry_data_session_type_class_name_dict()
active_data_mode_type_properties = known_data_session_type_properties_dict[active_data_mode_name]

print(f'basedir: {basedir} | force_reload: {force_reload}')

override_parameters_flat_keypaths_dict = (override_parameters_flat_keypaths_dict or {}) | {'nwb.nwb_filename': NWB_FILENAME}
curr_active_pipeline = NeuropyPipeline.try_init_from_saved_pickle_or_reload_if_needed(active_data_mode_name, active_data_mode_type_properties, override_basepath=Path(basedir), force_reload=force_reload, override_parameters_flat_keypaths_dict=override_parameters_flat_keypaths_dict, skip_save_on_initial_load=False)
print('pipeline session context:', curr_active_pipeline.sess.get_context())
print('pickle path:', basedir / 'loadedSessPickle.pkl')

basedir: H:\Data\DANDI\HighDensityCrossBrain\001695\sub-M02 | force_reload: True
Skipping loading from pickled file because force_reload == True.
build_logger(full_logger_string="2026-07-09_11-07-15.Apogee.dandi_nwb_001695_pipeline.dandi_nwb_001695", file_logging_dir: None):
	 Loading success: .interpolated_spike_positions.npy.
externally computed ripple_df.pkl not found. Falling back to .ripple.npy...
Failure loading .ripple.npy. Must recompute.

computing ripple epochs for session...

Computation failed with error 'NoneType' object has no attribute 'get_signal'. Skipping .ripple
Loading success: .mua.npy.
Loading success: .pbe.npy.
Loading success: .non_pbe.npy.
Computing spikes_df PBEs column results : "spikes_df"... done.
Computing added spike scISI column results : "spikes_df"... done.
POSTLOAD_estimate_laps_and_replays()...
fixing up DANDI 001695 session computation epochs...
	done. new epochs:
2069 epochs
array([[0.9965, 898.996],
       [389.677, 389.705],
       [410.96, 410.995],
       ...,
       [11528.2, 11528.2],
       [11538.6, 11538.6],
       [11541.9, 11542]])


computing PBE epochs for session...

computing estimated replay epochs for session...

	 using KnownFilterEpochs.PBE as surrogate replays...

H:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\NeuroPy\neuropy\core\session\Formats\Specific\DANDI001695NWBDataSessionFormat.py:597: UserWarning: Could not estimate replays for DANDI 001695 session dandi_nwb_001695_M02_001695_ses-20240318T100000: 'DataFrame' object has no attribute 'to_dataframe'
  warnings.warn(f'Could not estimate replays for DANDI 001695 session {sess.get_context()}: {e}')

computing non_PBE epochs for session...

H:\TEMP\Spike3DEnv_ExploreUpgrade\Spike3DWorkEnv\NeuroPy\neuropy\core\epoch.py:2188: UserWarning: curr_epochs already empty prior to any filtering
  warn(f'curr_epochs already empty prior to any filtering')

Saving non_pbe results results : "H:/Data/DANDI/HighDensityCrossBrain/export/M02/ses-20240318T100000.non_pbe.npy"... ses-20240318T100000.non_pbe.npy saved
done.
Updated preprocessing parameter: preprocessing.epoch_estimation_parameters.laps.use_direction_dependent_laps -> epoch_estimation_parameters.laps.use_direction_dependent_laps = False
WARN: PipelineWithComputedPipelineStageMixin.update_parameters(...): too early to set the computation_config override_parameters, not yet at the computation stage!!
  - Computation parameters can only be updated after the pipeline reaches the computed stage.
  - Preprocessing parameters can be updated at any stage.
Saving (file mode 'w+b') pickle file results : "H:/Data/DANDI/HighDensityCrossBrain/001695/sub-M02/loadedSessPickle.pkl"... 	moving new output at 'H:\Data\DANDI\HighDensityCrossBrain\001695\sub-M02\20260709115920-loadedSessPickle.pkltmp' -> to desired location: 'H:\Data\DANDI\HighDensityCrossBrain\001695\sub-M02\loadedSessPickle.pkl'
	Saved file size: 526.21 MB
saved pickle file
pipeline session context: dandi_nwb_001695_M02_001695_ses-20240318T100000
pickle path: H:\Data\DANDI\HighDensityCrossBrain\001695\sub-M02\loadedSessPickle.pkl

In [9]:
pos_df = curr_active_pipeline.sess.position.to_dataframe().position.compute_speed_info()
print('position duration (s):', pos_df['t'].max() - pos_df['t'].min())
print('x range:', pos_df['x'].min(), pos_df['x'].max())
print('y range:', pos_df['y'].min(), pos_df['y'].max())
pos_df.iloc[::PLOT_SUBSAMPLE].plot.scatter(x='x', y='y', c='speed', s=4, cmap='viridis', figsize=(6, 5))

position duration (s): 2827.8629555555553
x range: 6.1052452188391895 116.69142245734311
y range: 10.40262848127758 20.942789475717543

In [10]:
DANDI001695NWBDataSessionFormatRegisteredClass.session_fixup_epochs(curr_active_pipeline.sess, enable_global_epoch=True)
curr_active_pipeline = final_process_bapun_all_comps(curr_active_pipeline=curr_active_pipeline, active_data_mode_name=active_data_mode_name, posthoc_save=False, time_bin_size=0.500, overwrite_extant=False, fail_on_exception=True, active_computation_functions_name_includelist=['pf_computation', 'pfdt_computation', 'position_decoding'])

WARN: already fixedup session epochs.
	restoring backed up epochs:
	done. new epochs:
2069 epochs
array([[0.9965, 898.996],
       [389.677, 389.705],
       [410.96, 410.995],
       ...,
       [11528.2, 11528.2],
       [11538.6, 11538.6],
       [11541.9, 11542]])

           start        stop       label  duration
0         0.9965    898.9965       WAKE0  898.0000
1       389.6765    389.7053     Ripple0    0.0288
2       410.9597    410.9949     Ripple1    0.0352
3       452.4205    452.4725     Ripple2    0.0520
4       452.5989    452.6237     Ripple3    0.0248
5       452.8605    452.8933     Ripple4    0.0328
...          ...         ...         ...       ...
2062  11307.3981  11307.4381  Ripple2022    0.0400
2063  11475.0717  11475.1325  Ripple2023    0.0608
2064  11493.8013  11493.8349  Ripple2024    0.0336
2065  11528.1765  11528.2069  Ripple2025    0.0304
2066  11538.6109  11538.6469  Ripple2026    0.0360
2067  11541.9445  11541.9805  Ripple2027    0.0360

[2069 rows x 4 columns]

hardcoded_params.decoder_building_session_names: ['WAKE0', 'activity_GLOBAL']
hardcoded_params.non_global_activity_session_names: ['WAKE0']
active_data_session_types_registered_classes_dict: {'dandi_nwb': <class 'neuropy.core.session.Formats.Specific.NWBDataSessionFormat.NWBDataSessionFormatRegisteredClass'>, 'kdiba': <class 'neuropy.core.session.Formats.Specific.KDibaOldDataSessionFormat.KDibaOldDataSessionFormatRegisteredClass'>, 'dandi_nwb_001695': <class 'neuropy.core.session.Formats.Specific.DANDI001695NWBDataSessionFormat.DANDI001695NWBDataSessionFormatRegisteredClass'>, 'bapun': <class 'neuropy.core.session.Formats.Specific.BapunDataSessionFormat.BapunDataSessionFormatRegisteredClass'>, 'rachel': <class 'neuropy.core.session.Formats.Specific.RachelDataSessionFormat.RachelDataSessionFormat'>}
WARN: already fixedup session epochs.
	done. new epochs:
2069 epochs
array([[0.9965, 898.996],
       [389.677, 389.705],
       [410.96, 410.995],
       ...,
       [11528.2, 11528.2],
       [11538.6, 11538.6],
       [11541.9, 11542]])



WARNING: SpikesAccessor.set_time_variable_name(new_time_variable_name: t_seconds) has been called. Be careful!
	 no change in time_variable_name. It will remain t_seconds.

Applying session filter named "WAKE11"...

WARNING: SpikesAccessor.set_time_variable_name(new_time_variable_name: t_seconds) has been called. Be careful!
	 no change in time_variable_name. It will remain t_seconds.

	hardcoded_params.grid_bin_bounds: ((0.0, 100.0), (0.0, 100.0))
beginning compute...
i: 0, active_epoch_names: ['WAKE11']
updating computation_results...
done.
Performing perform_action_for_all_contexts with action EvaluationActions.EVALUATE_COMPUTATIONS on filtered_session with filter named "WAKE11"...
curr_active_computation_params.pf_params.computation_epochs: 1 epochs
array([[4601, 8269]])

due to includelist, including only 3 out of 18 registered computation functions.
Performing _execute_computation_functions(...) with 3 registered_computation_functions...
Recomputing active_epoch_placefields1D... 	 done.
Recomputing active_epoch_placefields2D... 	 done.
Recomputing active_epoch_time_dependent_placefields... 	 done.
Recomputing active_epoch_time_dependent_placefields2D... 	 done.
_execute_computation_functions(...):
	accumulated_errors: None
	computation_times: {'_perform_baseline_placefield_computation': datetime.datetime(2026, 7, 9, 11, 59, 38, 420143), '_perform_position_decoding_computation': datetime.datetime(2026, 7, 9, 11, 59, 41, 442742), '_perform_time_dependent_placefield_computation': datetime.datetime(2026, 7, 9, 11, 59, 44, 487608)}
updating computation_results...
done.
i: 1, active_epoch_names: ['activity_GLOBAL']
Performing perform_action_for_all_contexts with action EvaluationActions.EVALUATE_COMPUTATIONS on filtered_session with filter named "activity_GLOBAL"...
curr_active_computation_params.pf_params.computation_epochs: 1 epochs
array([[4601, 8269]])

due to includelist, including only 3 out of 18 registered computation functions.
Performing _execute_computation_functions(...) with 3 registered_computation_functions...
Recomputing active_epoch_placefields1D... 	 done.
Recomputing active_epoch_placefields2D... 	 done.
Recomputing active_epoch_time_dependent_placefields... 	 done.
Recomputing active_epoch_time_dependent_placefields2D... 	 done.
_execute_computation_functions(...):
	accumulated_errors: None
	computation_times: {'_perform_baseline_placefield_computation': datetime.datetime(2026, 7, 9, 11, 59, 47, 885779), '_perform_position_decoding_computation': datetime.datetime(2026, 7, 9, 11, 59, 50, 767047), '_perform_time_dependent_placefield_computation': datetime.datetime(2026, 7, 9, 11, 59, 53, 830386)}
updating computation_results...
done.
updating computation_results...
done.
	compute done!

In [ ]:
curr_active_pipeline.save_pipeline(active_pickle_filename=basedir / 'loadedSessPickle.pkl', saving_mode=saving_mode)
print('Saved pipeline pickle to', basedir / 'loadedSessPickle.pkl')
print('Session export cache remains at', curr_active_pipeline.sess.filePrefix.parent)

finalized_loaded_sess_pickle_path: H:\Data\DANDI\HighDensityCrossBrain\001695\sub-M02\loadedSessPickle.pkl
Saving (file mode 'w+b') pickle file results : "H:/Data/DANDI/HighDensityCrossBrain/001695/sub-M02/20260709115957-loadedSessPickle.pkl"...

# 🎨 2024-02-06 - Other Plotting

In [ ]:
from pyphoplacecellanalysis.Pho2D.PyQtPlots.TimeSynchronizedPlotters.TimeSynchronizedPlacefieldsPlotter import TimeSynchronizedPlacefieldsPlotter

_restore_previous_matplotlib_settings_callback = matplotlib_configuration_update(is_interactive=True, backend='Qt5Agg')

#  Create a new `SpikeRaster2D` instance using `_display_spike_raster_pyqtplot_2D` and capture its outputs:
curr_active_pipeline.reload_default_display_functions()
curr_active_pipeline.prepare_for_display()

## `LauncherWidget`: GUI

In [ ]:
from pyphoplacecellanalysis.General.Pipeline.Stages.Display import DisplayFunctionItem
from pyphocorehelpers.gui.Qt.tree_helpers import find_tree_item_by_text
from pyphoplacecellanalysis.GUI.Qt.MainApplicationWindows.LauncherWidget.LauncherWidget import LauncherWidget

widget = LauncherWidget()
treeWidget = widget.mainTreeWidget # QTreeWidget
widget.build_for_pipeline(curr_active_pipeline=curr_active_pipeline)
widget.show()

## ✅ 2025-09-19 - Clean programmmatic figure outputs

In [ ]:
from pyphocorehelpers.plotting.figure_management import PhoActiveFigureManager2D, capture_new_figures_decorator
fig_man = PhoActiveFigureManager2D(name=f'fig_man') # Initialize a new figure manager
from pyphoplacecellanalysis.GUI.PyQtPlot.Widgets.DockAreaWrapper import DockAreaWrapper
from pyphoplacecellanalysis.General.Mixins.ExportHelpers import programmatic_render_to_file, programmatic_display_to_PDF, extract_figures_from_display_function_output
from neuropy.core.session.Formats.BaseDataSessionFormats import HardcodedProcessingParameters
from neuropy.core.session.Formats.Specific.NWBDataSessionFormat import NWBDataSessionFormatRegisteredClass

In [ ]:

hardcoded_params: HardcodedProcessingParameters = NWBDataSessionFormatRegisteredClass._get_session_specific_parameters(session_context=curr_active_pipeline.get_session_context())
# hardcoded_params

# hardcoded_params.decoder_building_session_names
# hardcoded_params.non_global_activity_session_names

fig_man.close_all()

# subset_includelist = ['maze1', 'maze2', 'maze_GLOBAL'] # Day5TwoNovel
# subset_includelist = ['roam', 'sprinkle'] # Day4

In [ ]:

# subset_includelist = hardcoded_params.decoder_building_session_names
subset_includelist = None
print(f'subset_includelist: {subset_includelist}')

In [ ]:
display_fn_kwargs = dict(subplots=(None, 9),
    fig_column_width=None,   # key fix — uses data aspect ratio for width
    fig_row_height=1.0,
    resolution_multiplier=1.0,
)

# display_fn_kwargs = dict(subplots=(None, 5))

# _out = dict()
# _out['_display_2d_placefield_result_plot_ratemaps_2D'] = curr_active_pipeline.display(display_function='_display_2d_placefield_result_plot_ratemaps_2D', active_session_configuration_context=IdentifyingContext(format_name='bapun',animal='RatS',session_name='Day5TwoNovel',filter_name='maze1'), **display_fn_kwargs) # _display_2d_placefield_result_plot_ratemaps_2D
# _out['_display_2d_placefield_result_plot_ratemaps_2D'] = curr_active_pipeline.display(display_function='_display_2d_placefield_result_plot_ratemaps_2D', active_session_configuration_context=IdentifyingContext(format_name='bapun',animal='RatS',session_name='Day5TwoNovel',filter_name='maze2'), **display_fn_kwargs) # _display_2d_placefield_result_plot_ratemaps_2D

In [ ]:
_out_list = programmatic_render_to_file(curr_active_pipeline=curr_active_pipeline, curr_display_function_name='_display_2d_placefield_result_plot_ratemaps_2D', subset_includelist=subset_includelist, 
                                        write_vector_format=True, write_png=True, debug_print=True, **display_fn_kwargs)

In [ ]:
_out_list = programmatic_render_to_file(curr_active_pipeline=curr_active_pipeline, curr_display_function_name='_display_2d_placefield_occupancy', subset_includelist=subset_includelist, 
                                        write_vector_format=True, write_png=True, debug_print=True)

In [ ]:
_out_list = programmatic_render_to_file(curr_active_pipeline=curr_active_pipeline, curr_display_function_name='_display_1d_placefields', subset_includelist=subset_includelist, 
                                        write_vector_format=True, write_png=True, debug_print=True, **display_fn_kwargs)

In [ ]:
_out_list = programmatic_render_to_file(curr_active_pipeline=curr_active_pipeline, curr_display_function_name='_display_1d_placefield_validations', subset_includelist=subset_includelist, 
                                        write_vector_format=True, write_png=True, debug_print=True, **display_fn_kwargs)